### ISSUE TITLE
add Memoize support

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#100]
I didn't see this as an existing issue when searching just now, but morelinq seems like a good place for a Memoize extension method.

The goal is to allow callers to iterate over a sequence multiple times, but caching the results so the inner/original sequence is still only iterated once.

The most common use case I've seen for this is when interacting with sql queries. If you use ToList/ToArray or the like (as many people do), you end up forcing your code to wait until all the results have been pulled into memory from the server.  Memoize improves this situation by allowing you to start pulling from the queryable immediately, but without having to incur the penalty if you end up needing to iterate over it multiple times (as the data gets cached as it's been pulled from the source).

An example gist can be found here to get across the idea:

https://gist.github.com/thomaslevesque/3345186

---

Originally reported on Google Code with ID 100

Reported by @jamesmanning on 2015-05-01 14:40:32

**Comment by fsateler** [comment]
There is a fairly good implementation here:

http://community.bartdesmet.net/blogs/bart/archive/2009/09/12/taming-your-sequence-s-side-effects-through-ienumerable-let.aspx

Unfortunately the license for this code was not clarified :(

**Comment by fsateler** [comment]
I also found an implementation in the interactive extensions:

http://rx.codeplex.com/SourceControl/latest#Ix.NET/Source/System.Interactive/EnumerableEx.Buffering.cs

Perhaps no need to integrate here?

**Comment by JamesFaix** [comment]
Is there anything wrong with an implementation as simple as this?

```
public class MemoizedSequence<T> : IEnumerable<T> {

    private IEnumerable<T> source;
    private List<T> cache;

    public MemoizedSequence(IEnumerable<T> source) {
        if (source == null) throw new ArgumentNullException("source");
        this.source = source;
    }

    public IEnumerator<T> GetEnumerator() {
        //Cache will only be null on the first iteration
        //If there's no cache, create one; otherwise, iterate cache
        return (cache == null) 
            ? CacheSource()
             : cache.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator() { return GetEnumerator(); }

    private IEnumerator<T> CacheSource() {
        //Create cache
        this.cache = new List<T>();
        
        //Fill and yield cache
        foreach (var element in source) {
            this.cache.Add(element);
            yield return element;
        }

        //Dispose of source
        this.source = null;
    }
}

```

**Comment by fsateler** [comment]
That implementation might use a partial list if the memo has not been fully
iterated when the second iteration is started.

**Comment by jamesmanning** [comment]
@JamesFaix yeah, unfortunately it's pretty important to only enumerate as far as you have to.  Thankfully, the examples linked seem to all do so, we'd just need to  grab one with compatible licensing (or author willing to allow relicensing or whatever)

**Comment by jamesmanning** [comment]
@atifaziz it looks like [Reactive Extensions uses the same Apache 2.0 license](http://rx.codeplex.com/SourceControl/latest#Ix.NET/Source/license.txt) as MoreLINQ does (assuming the 'LICENSE' link from https://www.nuget.org/packages/morelinq/ is still accurate, I didn't see a license file in the project root here on github), so we should be ok adding their implementation to MoreLINQ AFAICT?  Would you be ok with that? Or would you feel better to leave Memoize out of MoreLINQ and just point people to using the Reactive Extensions NuGet package if they want Memoize?

**Comment by JamesFaix** [comment]
It looks like there is an implementation in the F# core library.  
`SeqModule.Cache{T}(this IEnumerable{T})`
