### ISSUE TITLE
Hide `CountBy` in net9+

### ISSUE THREAD

**Issue by viceroypenguin** [morelinq/MoreLINQ#1020]
net9.0 has added `CountBy()` overloads that overlap the MoreLinq versions. We should hide them in net9+. Similar to #749.

See: https://github.com/dotnet/runtime/pull/91507

**Comment by atifaziz** [comment]
Something to note is that the name for the key comparer parameter differs (`keyComparer` vs `comparer`) and while it may not present a binary compatibility issue, it will be a source compatibility one if someone decides to name the argument at the call site.
