### ISSUE TITLE
F# countBy analogue

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#104]
Similar to the group by, but in the result values are integers, instead of sequences

https://msdn.microsoft.com/en-us/library/ee340317.aspx

---

Originally reported on Google Code with ID 104

Reported by @marhoily on 2015-06-23 14:21:00

**Comment by R2-Miao** [comment]
Hello @atifaziz, I would like to try my hand at implementing this.

**Comment by atifaziz** [comment]
@R2-Miao By all means. Thanks for volunteering. Please fork, branch and send a PR. We'll take it from there.

**Comment by atifaziz** [comment]
X-ref PR #146
