### ISSUE TITLE
Async versions of OrderedMerge and GroupAdjacent

### ISSUE THREAD

**Issue by danielearwicker** [morelinq/MoreLINQ#1060]
I really like the `GroupAdjacent` and `OrderedMerge`, as in combination they can do an ordered full join on sequences that have already been sorted by the same key, powerful for processing/updating/comparing large sorted data sets.

Great to see an async version of `Merge` - any interest in async versions of `GroupAdjacent` and `OrderedMerge`?

**Comment by viceroypenguin** [comment]
@danielearwicker, these operators exist in [SuperLinq.Async](https://github.com/viceroypenguin/SuperLinq?tab=readme-ov-file), as [ConcurrentMerge](https://viceroypenguin.github.io/SuperLinq/api/SuperLinq.Async.AsyncSuperEnumerable.ConcurrentMerge.html), [GroupAdjacent](https://viceroypenguin.github.io/SuperLinq/api/SuperLinq.Async.AsyncSuperEnumerable.GroupAdjacent.html), and [SortedMerge](https://viceroypenguin.github.io/SuperLinq/api/SuperLinq.Async.AsyncSuperEnumerable.SortedMerge.html). SuperLinq.Async also has most of the other operators in async version as well.

**Comment by atifaziz** [comment]
@danielearwicker [`OrderedMerge` is implemented & maintained](https://github.com/i3arnon/MoreAsyncLINQ/blob/e0905e27361d82b26a00dc12923c468fc7f254d2/src/MoreAsyncLINQ/Operators/OrderedMerge.cs) by @i3arnon as part of [MoreAsyncLINQ](https://github.com/i3arnon/MoreAsyncLINQ). Unfortunately, looks like [`GroupAdjacent` has been added yet](https://github.com/i3arnon/MoreAsyncLINQ/issues/3) (perhaps you may want to contribute there?). You could use [SuperLinq](https://github.com/viceroypenguin/SuperLinq) that offers both, but that's a complete separate fork.

**Comment by danielearwicker** [comment]
Cool, thanks for the pointers
