### ISSUE TITLE
Hide `CountBy` that's being added in .NET 9

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#1079]
.NET 9 will add [`CountBy`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.countby?view=net-9.0) and will cause conflicts for users importing the `MoreLinq` namespace directly. Once .NET 9 is released, MoreLINQ should hide all method overloads (note that .NET 9 offers only one) from a targeted build. This will maintain binary and source compatability.

**Comment by viceroypenguin** [comment]
Duplicate of #1020

**Comment by atifaziz** [comment]
> Duplicate of #1020

Indeed. I lost track. 😅 Thanks!
