### ISSUE TITLE
CanBeNull attribute breaks source packages

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#111]
`CanBeNull` (introduced in 646e4424767ab2055731d5134bedd50a99451868 and with PR #109) is somewhat problematic. While it's not publicly exposed, it will break solutions that use the *source* packages.

The [null test case generator](https://github.com/morelinq/MoreLINQ/blob/b4bc5a7dd504c526642ef73afad828e9e64e36e1/MoreLinq.Test/NullArgumentTest.cs#L70-L81) that uses it should instead enforce the policy that all comparer type of parameters should be nullable, otherwise it's a bug. That covers the 90% uses of the attribute. The remaining are overloads of `ToDelimitedString` where the delimiter parameter can be null. We can (unfortunately) hard-wire that exception unless there's a better alternative altogether to using a marker attribute.

**Comment by yln** [comment]
How about creating another source package for the attribute and have the others (which use [CanBeNull]) depend on it?
I like the attribute because it also acts as documentation (and the correctness is even checked by tests!)

**Comment by atifaziz** [comment]
Yes, I agree about all the benefits, doc-wise and so on, but my suggested course is one of practicality. In the same spirit as you went with an automated and generated test case strategy for null arg checking, I think that `CanBeNull` is not needed for the 90% cases because all custom comparison parameters should be optional and nullable. There's no added value of `CanBeNull` there and it's the expectation from all LINQ operators. For the remaining 10% (and I'm being generous here :smile:) that is the `ToDelimitedString` method group, I think publishing a new package and hand-maintaining dependencies as it stands today, across all source packages, is not worth the effort. That is why I am inclined to tip the balance and say that we special-case `ToDelimitedString` within the test case generator. As for `CanBeNull` being a source of documentation, I'm not sure that argument works because it's not surface in IntelliSense so it requires that people dip their noses into the sources. In fact, something in the types along the lines of `Optional<T>` provides better transparency and self-documentation.

If you want to wrap up another package for the attribute and help me setup the dependencies in the relevant packages then I'd be happy to throw you some rope. Bear in mind, though, that the current focus is to stabilise and release 2.0 and I feel that `CanBeNull` (for all its good and intent and purpose, no doubt) might just be adding work without new and additional benefits.

Thoughts?

**Comment by yln** [comment]
Okay, I will remove the attribute and adapt the test case generator.

**Comment by JulianLettner** [comment]
`Optional<T>`: I agree, this would be even better! Now we don't even have to rely on tests, instead the compiler proofs correctness to us via the type system. Unfortunately, it is "just not the .NET way" of doing things. I would do it in a private project, but not in something as general as MoreLinq. It also makes an API a bit more tedious/foreign to consume (in .NET).

IntelliSense: works for me (don't know if this is ReSharper or VS).
![inellisense](https://cloud.githubusercontent.com/assets/13023319/9768913/aa692a44-56db-11e5-8eed-c664ef59ec01.png)

**Comment by yln** [comment]
`Optional<T>`: I agree, this would be even better! Now we don't even have to rely on tests, instead the compiler proofs correctness to us via the type system. Unfortunately, it is "just not the .NET way" of doing things. I would do it in a private project, but not in something as general as MoreLinq. It also makes an API a bit more tedious/foreign to consume (in .NET).

IntelliSense: works for me (don't know if this is ReSharper or VS).
![inellisense](https://cloud.githubusercontent.com/assets/13023319/9768913/aa692a44-56db-11e5-8eed-c664ef59ec01.png)

**Comment by atifaziz** [comment]
> it is "just not the .NET way"

I agree because even if we have `Option<T>` in the BCL like [the `Tuple` family][tuples], it's a lot of noise unless C# makes it as native and intuitive as [F#][fsoption].

> IntelliSense: works for me (don't know if this is ReSharper or VS).

I stand corrected & probably I never paid attention.

  [fsoption]: https://msdn.microsoft.com/en-us/library/dd233245.aspx
  [tuples]: https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx

**Comment by yln** [comment]
Since this and the other issues tagged as bugs are now fixed, what is needed to make a stable 2.x release?

**Comment by atifaziz** [comment]
@yln So yes, this bug is resolved, thanks. This issue will help to make a v1.2 release, that I'll go ahead and do. Then #110 is still pending because the work needs to be merged into v2. That will then fail some tests there because some of your fixes need to re-applied from the origin [EquiZip-null-check](https://github.com/yln/MoreLINQ/tree/EquiZip-null-check) branch.

**Comment by atifaziz** [comment]
@yln I have released [1.2](https://www.nuget.org/packages/morelinq/1.2.0), including the [portable version](https://www.nuget.org/packages/MoreLinq.Portable/1.2.0). For 2.0, see my [follow-on comment](https://github.com/morelinq/MoreLINQ/issues/110#issuecomment-140719202) for  #110.
