### ISSUE TITLE
Implement SingleOrNew

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#12]
Implement SingleOrNew as per http://stackoverflow.com/questions/561762/what-about-a-singleornew-method-instead-of-singleordefault-in-linq/561787#561787

---
Originally reported on Google Code with ID 12

Reported by @jskeet on 2009-02-18 16:19:03

**Comment by fsateler** [comment]
This is already implemented as `SingleOrFallback`

**Comment by fsateler** [comment]
I think that `SingleOrFallback` should not exist, and instead provide `FallbackIfEmpty`, the same way that `SingleOrDefault` does not provide a way to specify the default value.

**Comment by atifaziz** [comment]
@fsateler Agree and this has been dormant for almost 7 years anyway! Closing this as addition of `FallbackIfEmpty` is now being followed-up in #122.
