### ISSUE TITLE
Unique / Duplicate operators

### ISSUE THREAD

**Issue by JamesFaix** [morelinq/MoreLINQ#125]
There are several variations on the theme of duplicate record detection that I find myself needing quite often when validating Excel files.

The first method, UniqueKeys just returns all keys (from a given key selector delegate) that only occur once in a collection.

```
 public static IEnumerable<TKey> UniqueKeys<TSource, TKey>(this IEnumerable<TSource> me,
        Func<TSource, TKey> keySelector, IEqualityComparer<TKey> keyComparer) {
        //check for null arguments

        return me.GroupBy(keySelector, keyComparer)
            .Where(g => g.Count() == 1)
            .Select(g => g.Key);
    }
```

Likewise, a DuplicateKeys method would be the same, just with "Where(g => g.Count() == 1)" replaced with "Where(g => g.Count() > 1)".

Building on these, are UniqueElements and DuplicateElements methods,

```
 public static IEnumerable<TSource> DuplicateElements<TSource, TKey>(this IEnumerable<TSource> me,
        Func<TSource, TKey> keySelector, IEqualityComparer<TKey> keyComparer) {
         //check for null args
        return me.ExceptByAll(me.UniqueKeys(keySelector, keyComparer), keySelector, keyComparer);
    }
```

The DuplicateKeys method can be used, for example, to find a distinct list of ID numbers that are used more than once, while DuplicateElements can be used to return a full list of rows where duplicate ID numbers are used.

The "Elements" methods are dependent on ExceptAll or ExceptByAll being implemented.  (see #124 )

**Comment by atifaziz** [comment]
This is now covered by [`CountBy`](http://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_CountBy.htm) since [2.0](https://github.com/morelinq/MoreLINQ/releases/tag/v2.0.0), e.g.:

```c#
var xs = new[] { 7, 4, 6, 5, 1, 2, 3, 8, 6, 4, 5, 1, 2 };

var duplicates = // 4, 6, 5, 1, 2
    from e in xs.CountBy(x => x)
    where e.Value > 1
    select e.Key;
    
var unique = // 7, 3, 8
    from e in xs.CountBy(x => x)
    where e.Value == 1
    select e.Key;
```
