### ISSUE TITLE
EquiZip overloads missing return value documentation

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#147]
Warnings running `builddocs.cmd` on cc6932f74cfcc7476bcc99db10f450bfdcb010c0:

```
BuildAssembler : warning : ShowMissingComponent: [M:MoreLinq.MoreEnumerable.EquiZip``5(System.Collections.Generic.IEnumerable{``0},System.Collections.Generic.IEnumerable{``1},System.Collections.Generic.IEnumerable{``2},System.Collections.Generic.IEnumerable{``3},System.Func{``0,``1,``2,``3,``4})] Missing <returns> documentation [A:\MoreLINQ\main\docs\api\Working\BuildReferenceTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:MoreLinq.MoreEnumerable.EquiZip``4(System.Collections.Generic.IEnumerable{``0},System.Collections.Generic.IEnumerable{``1},System.Collections.Generic.IEnumerable{``2},System.Func{``0,``1,``2,``3})] Missing <returns> documentation [A:\MoreLINQ\main\docs\api\Working\BuildReferenceTopics.proj]
```

**Comment by atifaziz** [comment]
@ErikSchierboom Published via morelinq/morelinq.github.io@12da6d18c1981e5fbbd70e90a58b1ee3a4987f02:

- [`EquiZip<T1, T2, T3, TResult>(IEnumerable<T1>, IEnumerable<T2>, IEnumerable<T3>, Func<T1, T2, T3, TResult>)`](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_EquiZip__4.htm)
- [`EquiZip<T1, T2, T3, T4, TResult>(IEnumerable<T1>, IEnumerable<T2>, IEnumerable<T3>, IEnumerable<T4>, Func<T1, T2, T3, T4, TResult>)`](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_EquiZip__5.htm)

**Comment by ErikSchierboom** [comment]
Wow, that's incredibly fast!
