### ISSUE TITLE
Windowed returns partial window when source length < window size

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#152]
Suppose:

``` c#
var ns = Enumerable.Range(1, 10);

Console.WriteLine(ns.Windowed(5)
                    .Select(w => w.ToDelimitedString(","))
                    .ToDelimitedString(Environment.NewLine));

Console.WriteLine(ns.Take(3)
                    .Windowed(5) // NOTE: window size > source length
                    .Select(w => w.ToDelimitedString(","))
                    .ToDelimitedString(Environment.NewLine));
```

The first console output is correct:

```
1,2,3,4,5
2,3,4,5,6
3,4,5,6,7
4,5,6,7,8
5,6,7,8,9
6,7,8,9,10
```

The second one should have been blank but instead prints: `1,2,3`

Tested against [MoreLINQ 2.0 beta 3](https://www.nuget.org/packages/morelinq/2.0.0-beta03).

**Comment by fsateler** [comment]
Hmm. the xmldoc says:

> This operator is guaranteed to return at least one result, even if the source sequence is smaller than the window size

So I'd say it was a feature, not a bug...

**Comment by atifaziz** [comment]
>> This operator is guaranteed to return at least one result, even if the source sequence is smaller than the window size

> So I'd say it was a feature, not a bug...

Perhaps it was a feature for the original contributor but could be a bug depending on the user. I found it to be a bug when expecting it to behave just like F#'s version, especially if it's going to go by the same name…

```
Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> [1..5] |> Seq.windowed 3;;
val it : seq<int []> = seq [[|1; 2; 3|]; [|2; 3; 4|]; [|3; 4; 5|]]
> [1..2] |> Seq.windowed 3;;
val it : seq<int []> = seq []
```

Aligning it means lesser of an element of surprise (e.g. LINQ's `Take` & F#'s `take` differ; the latter throws if there are more elements than you asked whereas `truncate` works more like `Take`). I'm not saying partial windows are wrong to expect but perhaps that needs to be an option or another method.

I forgot to update the doc summary so thanks for spotting that.

**Comment by fsateler** [comment]
I'm not particularly attached to either behavior per se, but I worry that this is a backwards-incompatible change. [Windowed is part of linq since the first 2.0 beta](https://github.com/morelinq/MoreLINQ/commit/c9902d2e40a01337892055a1f39410e86d708606), and as of this writing has [over 15000 downloads](https://www.nuget.org/packages/morelinq/) . It would be a shame if people were depending on this behavior, and then a new version changes it. The worst part is that the behavior changes silently; with a crash or failure to build at least the issue will not go undetected.

**Comment by atifaziz** [comment]
> I worry that this is a backwards-incompatible change.

I'm glad to learn someone else cares about that too 😄 but frankly 2.0's been a _beta_ all along (for far too long & something I'm trying to change) and that does mean that authors reserve the right to change things that still needs attention or fixing.

If we cannot afford a breaking change to this beta then it makes #209 hopeless.

> The worst part is that the behavior changes silently; with a crash or failure to build at least the issue will not go undetected.

Are you suggesting to change the name just to crash builds? Perhaps mentioning the behavioural change in the release notes is better?

> I'm not particularly attached to either behavior per se

Have you looked at #153?
