### ISSUE TITLE
Pairwise Documentation example is invalid.

### ISSUE THREAD

**Issue by pjmagee** [morelinq/MoreLINQ#159]
The example source [found here] (https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Pairwise__2.htm) has invalid example code.

```c#
int[] numbers = { 123, 456, 789 };
IEnumerable<int> result = numbers.Pairwise(5, (a, b) => a + b);
```

should be

```c#
int[] numbers = { 123, 456, 789 };
IEnumerable<int> result = numbers.Pairwise((a, b) => a + b);
```

**Comment by atifaziz** [comment]
@pjmagee Thanks. Do you want to try and submit a PR to [fix that](https://github.com/morelinq/MoreLINQ/blob/v1/MoreLinq/Pairwise.cs#L46)? Then credit's to you otherwise I can do it.

**Comment by atifaziz** [comment]
Published:

* [MoreEnumerable.Pairwise (1.x)](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Pairwise__2.htm)
* [MoreEnumerable.Pairwise (2.0)](https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Pairwise__2.htm)
