### ISSUE TITLE
AdjacentDistinct and AdjacentDistinctBy

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#162]
These operators would be for `Distinct` and `DistinctBy` what `GroupAdjacent` is to `GroupBy`.

The idea is that by only grouping adjacents, there is no need to store seen objects, and thus memory is saved.

I have a local implementation here, and I could clean them up for submission, if these operators make sense to you. I'm unsure about the naming though: Locally I have them named `DistinctUntilChanged`. However, this loses the relation to `GroupAdjacent`. I would prefer to have names that are easily correlated and discoverable. But `AdjacentDistinct` does not make much sense to me, and neither does `DistinctAdjacent`. Suggestions?

**Comment by fsateler** [comment]
I see now that I probably stole the name `DistinctUntilChanged` from the [Reactive Extensions](https://msdn.microsoft.com/en-us/library/hh229494(v=vs.103).aspx)

**Comment by atifaziz** [comment]
@fsateler In addition to stealing the name, why not just use [the implementation in Ix][DistinctUntilChanged] too? 😉 

[DistinctUntilChanged]: https://github.com/Reactive-Extensions/Rx.NET/blob/22674716024e09d425678df54a8b6aaeab4558a1/Ix.NET/Source/System.Interactive/EnumerableEx.Single.cs#L348-L440

**Comment by fsateler** [comment]
@atifaziz oh, I somehow missed that IX had this as well. However, there is still the By variant missing.

Should this issue be closed then (and possibly file a new one against IX), or is this something worth having in MoreLINQ?

**Comment by atifaziz** [comment]
> and possibly file a new one against IX

I think given that IX is open source too, this would be the most natural cause as well.

> or is this something worth having in MoreLINQ?

Could be but then we'd have to come up with a distinct name (which feels silly) to avoid conflicts in projects using IX and MoreLINQ. Each time an issue of naming conflict comes up, I'm convinced that a [“no-conflict” approach via namespaces](https://github.com/morelinq/MoreLINQ/issues/60#issuecomment-133518416) is more and more the right approach (which I've [tried in another project](https://github.com/atifaziz/AngryArrays) and has proved to work well).

**Comment by atifaziz** [comment]
> However, there is still the By variant missing.

Are you sure? Looking again, I think [it's there](https://github.com/Reactive-Extensions/Rx.NET/blob/22674716024e09d425678df54a8b6aaeab4558a1/Ix.NET/Source/System.Interactive/EnumerableEx.Single.cs#L397-L416).

**Comment by fsateler** [comment]
@atifaziz thanks for looking that up. Sorry for not seeing it before, I blame using the same name for both variants.

I guess we can close this now.
