### ISSUE TITLE
Operator like 'SingleOrDefault' that returns default if count != 1

### ISSUE THREAD

**Issue by JamesFaix** [morelinq/MoreLINQ#167]
I would like to add an operator that returns the only elements in a sequence, if there is only one, or a default value if there are zero or more than one elements.  Its a `Single` type method that cannot throw an exception, other than `ArgumentNullException` for null sequences.

The implementation would be basically this:
`public static T SingleSafe<T>(this IEnumerable<T> sequence, T fallback) {`
`    return (sequence.Count() == 1) ? sequence.Single() : fallback; }`

This operator could have a new name, or it could possibly be an overload of SingleOrFallback.

`T SingleOrFallback<T>(this IEnumerable<T> sequence, T fallback, bool fallbackIfMultiple)`
`T SingleOrFallback<T>(this IEnumerable<T> sequence, Func<T> fallback, bool fallbackIfMultiple)`

**Comment by fsateler** [comment]
I don't quite see the use case, but if this is added it should definitely not be an overload of SinglerOrFallback, as the meaning is entirely different.

**Comment by JamesFaix** [comment]
I've had to wrap a call to `SingleOrDefault` in a `try`/`catch` block on several occasions, because a collection that "should" only ever have one item had two.  This makes it easier to chain functions together without exception handling clutter.

**Comment by atifaziz** [comment]
@JamesFaix I agree with @fsateler that the use case doesn't seem general enough. You've described what it should do and how it would help but not really the problem set it helps to solve. I can probably imagine something but that would be a wild guess. I would recommend instead using [`Catch`](https://github.com/Reactive-Extensions/Rx.NET/blob/22674716024e09d425678df54a8b6aaeab4558a1/Ix.NET/Source/System.Interactive/EnumerableEx.Exceptions.cs#L10) from [Ix (Interactive Extensions)](https://www.nuget.org/packages/Ix-Main/) together with `SingleOrDefault` if you're purpose is chaining and reducing exception handling clutter. You could implement your overload locally in a single line with Ix + LINQ (no need for MoreLINQ there).

I'm going to close this and happy reconsider if there's a strong case in favour of adding it.

**Comment by JamesFaix** [comment]
Thanks for the tip about Ix.
