### ISSUE TITLE
RandomImpl perpetual while

### ISSUE THREAD

**Issue by vbjay** [morelinq/MoreLINQ#176]
We know you want a set of random numbers.  Instead of using while(true), why not use enumerable.range?

return Enumerable.Range(0,size).Select(n=> rand.next());

**Comment by atifaziz** [comment]
Because there is no `size` or `count` argument to the `Random` overloads and adding one would be somewhat of a superficial limitation. Capping the sequence to a specific count can be achieved by simply composing with `Take`

**Comment by vbjay** [comment]
This was my point.  http://stackoverflow.com/questions/2740001/how-to-handle-an-infinite-ienumerable  I know take will make it lazy but it should have a limit.  If you do call a greedy method it will cause issues.

**Comment by atifaziz** [comment]
>  If you do call a greedy method it will cause issues.

Which is why [the doc](https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Random.htm) clearly states “Returns an infinite sequence of random…”.
