### ISSUE TITLE
SelectWithPreviousResult

### ISSUE THREAD

**Issue by devuxer** [morelinq/MoreLINQ#178]
Perhaps there's an elegant way to do this already, but I'm seeking a way to feed the result of the previous projection into the projection func.

Example implementation

```
public static IEnumerable<TResult> SelectWithPreviousResult<TSource, TResult>(
    this IEnumerable<TSource> sequence,
    TResult defaultResult,
    Func<TSource, TResult, TResult> func)
{
    var previousResult = defaultResult;
    foreach (var item in sequence)
    {
        var result = func(item, previousResult);
        previousResult = result;
        yield return result;
    }
}
```

**Comment by atifaziz** [comment]
Have a look at [`Scan`](https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Scan.htm).

**Comment by devuxer** [comment]
These don't look the same to me:

- `Scan` takes an `IEnumerable<TSource>` and returns an `IEnumerable<TSource>`.
- `SelectWithPreviousResult` takes an `IEnumerable<TSource>` and returns an `IEnumerable<TResult>`.

**Comment by atifaziz** [comment]
Have you looked at the [second overload](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Scan__2.htm)?

```c#
public static IEnumerable<TState> Scan<TSource, TState>(
	this IEnumerable<TSource> source,
	TState seed,
	Func<TState, TSource, TState> transformation
)
```

Like your `SelectWithPreviousResult` proposal, takes a sequence of `TSource` and returns a sequence of `TState` (`TResult`  in your case).

Here's an example showing a _running total_ produced using `SelectWithPreviousResult` and `Scan`.

```c#
var xs = Enumerable.Range(1, 10);
Console.WriteLine(xs.SelectWithPreviousResult(10, (x, a) => a + x)
                    .ToDelimitedString(", ")); 
// output:
// 11, 13, 16, 20, 25, 31, 38, 46, 55, 65

Console.WriteLine(xs.Scan(10, (x, a) => a + x)
                    .Skip(1) // skip seed
                    .ToDelimitedString(", "));
// output:
// 11, 13, 16, 20, 25, 31, 38, 46, 55, 65
```

They produce identical results. One difference is that `Scan` will also yield the initial seed value, which is the same as `defaultResult` in your case except you don't yield it in the result. To make `Scan` then identical to `SelectWithPreviousResult`, you just need to compose it with `Skip(1)`.

Hope this clears it up.

**Comment by devuxer** [comment]
I didn't notice the second overload. Thanks for pointing that out.

By the way, I didn't realize there was a documentation site. It would be great if you put a link to that in the README and Wiki home page.

**Comment by atifaziz** [comment]
> I didn't realize there was a documentation site. It would be great if you put a link to that in the README and Wiki home page.

The link to the project home page is right there at the top of the repo:

![image](https://cloud.githubusercontent.com/assets/20511/15665417/581a96fa-270b-11e6-852f-012063ea5f3b.png)

I agree though that the README & Wiki need a bit of TLC and use a link to the docs so feel free to open an issue for that. :wink:
