### ISSUE TITLE
Trace methods should only work on TRACE define

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#18]
As with other `Trace` methods, the MoreLINQ `Trace` methods should not operate if the `TRACE` define is not specified.

---
Originally reported on Google Code with ID 18

Reported by `jeffmagic` on 2009-03-11 04:34:30

**Comment by VladimirRybalko** [comment]
Hi. Seems that bug has already fixed. 
Look at this:
`return source
#if !NO_TRACING
                .Pipe(x => System.Diagnostics.Trace.WriteLine(formatter(x)))
#endif
                ;`

This peace of code assures that nothing happens if 'TRACE' define is specified because **System.Diagnostics.Trace.WriteLine** method has conditional attribute with TRACE parameter.

**Comment by atifaziz** [comment]
This is actually working as always originally intended so it's not a bug. The `Trace` method _unconditionally_ sends to `System.Diagnostics.Trace`. It cannot be made conditional because it returns a value.
