### ISSUE TITLE
FullGroupJoin: should provide a default selector

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#181]
Much like `GroupJoin` has overloads that return an `IGrouping`, `FullGroupJoin` should offer overloads that provide a default return aggregator:

``` csharp
public static IEnumerable<FullGrouping<TKey, TFirst, TSecond>> FullGroupJoin<TFirst, TSecond, TKey, TResult>(this IEnumerable<TFirst> first, IEnumerable<TSecond> second, Func<TFirst, TKey> firstKeySelector, Func<TSecond, TKey> secondKeySelector) {
    // Null checks
    return MoreEnumerable.FullGroupJoin(first, second, firstKeySelector, secondKeySelector, (k, ga, gb) => new FullGrouping<TK, TA, TB>(k, ga, gb));
}

// another overload with equality comparer

public class FullGrouping<TKey, TLeft, TRight>
{
    public TKey Key { get; }
    public IEnumerable<TLeft> Left { get; }
    public IEnumerable<TRight> Right { get; }

    public FullGrouping(TKey key, IEnumerable<TLeft> left, IEnumerable<TRight> right)
    {
        Key = key;
        Left = left;
        Right = right;
    }
}
```

What do you think? I can propose a PR if this sounds reasonble.

**Comment by atifaziz** [comment]
I think this would introduce a new type that adds very marginal value because its implementation is too trivial (something that can be added to a project using MoreLINQ without it feeling too ugly). `IGrouping` is already part of the .NET so making sense out of re-using it is a little easier. We should wait out and see how tuples in C# 7 (dotnet/roslyn#347) could help with such overloads more simply without introducing new (essentially small record) types.

**Comment by fsateler** [comment]
> I think this would introduce a new type that adds very marginal value because its implementation is too trivial (something that can be added to a project using MoreLINQ without it feeling too ugly).

Indeed, I already have it in my projects. I was hoping to avoid more copy paste :wink: 

> We should wait out and see how tuples in C# 7 (dotnet/roslyn#347) could help with such overloads more simply without introducing new (essentially small record) types.

Ack. I hope it proves useful.

**Comment by atifaziz** [comment]
> Ack

Cool, so we can close this now & revisit this (along with probably many other operators that could use reasonable default selector) when C# 7 is out?

**Comment by fsateler** [comment]
On 16 September 2016 at 10:47, Atif Aziz <notifications@github.com> wrote:

> Ack
>
> Cool, so we can close this now & revisit this (along with probably many
> other operators that could use reasonable default selector) when C# 7 is
> out?
>

I'd suggest instead applying a label (eg, postponed/cs-7 or something like
that) so that these issues can be easily skipped, but are not forgotten
once C#7 is out.

-- 

Saludos,
Felipe Sateler

**Comment by atifaziz** [comment]
I think this is do-able now:

```c#
static IEnumerable<(TKey Key, IEnumerable<TFirst> First, IEnumerable<TSecond> Second)>
    FullGroupJoin<TFirst, TSecond, TKey, TResult>(
        this IEnumerable<TFirst> first,
        IEnumerable<TSecond> second,
        Func<TFirst, TKey> firstKeySelector,
        Func<TSecond, TKey> secondKeySelector) =>
    first.FullGroupJoin(second, firstKeySelector, secondKeySelector, ValueTuple.Create);
```

**Comment by fsateler** [comment]
Indeed!

**Comment by atifaziz** [comment]
@fsateler Go for a PR whenever you get a chance!
