### ISSUE TITLE
A question about the Acquire operator

### ISSUE THREAD

**Issue by Sathyaish** [morelinq/MoreLINQ#185]
In the `Acquire` operator, you add the received source enumerable to a `List<TSource>`, the assumption being that no resource that has been disposed off will be added to the list.

This is new to me and I want to know where I can read about the fact that a list will disallow disposed off elements to be added to it?

Or if I have misunderstood it, could you please explain how you find out whether or not a resource has been disposed off?

**Comment by atifaziz** [comment]
@Sathyaish There is no list magic going on here. The `Acquire` method does not attempt to detect if an element of the source has been disposed off or not. In general, [`IDisposable.Dispose`][IDisposable.Dispose] implementations should be written in such a way that calling `IDisposable.Dispose` on an already disposed object should have not effect.

`Acquire` only makes sense and is able to do it's job (i.e. provide the guarantee that _all_ source disposables have been acquired or none at all) _if_ `source` _streams_ the disposable elements. The [`List<T>.AddRange`][ListT.AddRange] [call][ListT.AddRange()] causes the `source` to be iterated. As the source yields each disposable, it is _assumed_ that the disposable initialized or was acquired successfully and is added to the list. If the yielding of one of the disposables throws then the [catch block][onerror] disposes those already in the list and then simply [re-throws][rethrow].

Have a look at this [brilliant answer][http://stackoverflow.com/a/21483127/6682] to the question “[MoreLinq Acquire. What does it do?][http://stackoverflow.com/questions/21483023/morelinq-acquire-what-does-it-do]” on StackOverflow and the example in there should make it clear (shame on me for not having the example in the docs).


[IDisposable.Dispose]: https://msdn.microsoft.com/en-us/library/system.idisposable.dispose%28v=vs.110%29.aspx
[ListT.AddRange]: https://msdn.microsoft.com/en-us/library/z883w3dc%28v=vs.110%29.aspx
[ListT.AddRange()]: https://github.com/morelinq/MoreLINQ/blob/c16f499397fc90c51cea7b6c9ef3c594ca6a04a1/MoreLinq/Acquire.cs#L49
[onerror]: https://github.com/morelinq/MoreLINQ/blob/c16f499397fc90c51cea7b6c9ef3c594ca6a04a1/MoreLinq/Acquire.cs#L52
[rethrow]: https://github.com/morelinq/MoreLINQ/blob/c16f499397fc90c51cea7b6c9ef3c594ca6a04a1/MoreLinq/Acquire.cs#L56

**Comment by Sathyaish** [comment]
@atifaziz  Beautiful. Thank you very much.
