### ISSUE TITLE
Installed the latest stable version - not consistent with the homepage?

### ISSUE THREAD

**Issue by dsaf** [morelinq/MoreLINQ#186]
It would be nice to add an "```Available Since Version```" column to let users know that methods like ```Incremental``` and ```Segment``` are not available for production code.

**Comment by atifaziz** [comment]
The master branch is the latest development branch. If you consult the [`README` corresponding to v1](https://github.com/morelinq/MoreLINQ/blob/v1/README.md) then it should be consistent with the latest stable version you installed.

Also, the [home page](https://morelinq.github.io/) clearly points to the docs for the [latest stable release (1.4 at this time)](https://morelinq.github.io/1.x/ref/api/) and [2.0 beta](https://morelinq.github.io/2.0/ref/api/).

**Comment by dsaf** [comment]
Fair enough.
