### ISSUE TITLE
Top/TopBy sorts inverted?

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#187]
Given the following sequence:

```csharp
new [] {1,2,3,4,5}.Top(3)
```

I expected the result to be `{ 5, 4, 3 }`, yet the result is `{ 1, 2, 3 }`.

**Comment by atifaziz** [comment]
The result is correct [per documentation](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Top__1.htm):

> Combines `OrderBy<TSource, TKey>(IEnumerable<TSource>, Func<TSource, TKey>)`, where each element is its key, and `Take<TSource>(IEnumerable<TSource> , Int32)` in a single operation.

Returns:

> A sequence containing at most top count elements from source, in their ascending order.

Note sure why you expect the result to be `{5, 4, 3}`.

**Comment by jskeet** [comment]
Well, I think it's a reasonable expectation, in that new[] { 1, 2, 3, 4, 5
}.OrderBy(x => x).Take(3) would give { 1, 2, 3 } and new[] { 1, 2, 3, 4, 5
}.OrderByDescending(x => x).Take(3) would give { 5, 4, 3 }.

It seems odd to put them in *ascending* order despite returning the
*highest* items.

Jon

**Comment by atifaziz** [comment]
> …in that `new[] { 1, 2, 3, 4, 5 }.OrderBy(x => x).Take(3)` would give `{ 1, 2, 3 }` …

And therefore `Top` returns the same. May be I haven't had my ☕ yet but what am I missing to see?

**Comment by jskeet** [comment]
My mistake. I misread the original post as saying it was giving the right
results in the wrong order.

I think the problem here is that "top" implies "greatest" - suggesting
OrderByDescending rather than OrderBy.
Tricky.

Jon

**Comment by fsateler** [comment]
On 27 Jul 2016 2:25 a.m., "Jon Skeet" <notifications@github.com> wrote:
>
> I think the problem here is that "top" implies "greatest" - suggesting
> OrderByDescending rather than OrderBy.
> Tricky.

Exactly.  Sorry for being unclear.

Top (3) returning the bottom 3 numbers is confusing. Maybe the confusion
can be resolved by adding an OrderByDirectiom parameter?

**Comment by atifaziz** [comment]
[Naming is hard](http://martinfowler.com/bliki/TwoHardThings.html) and [we've struggled in the past too](https://github.com/morelinq/MoreLINQ/issues/10). When words are borrowed from human languages to name methods, they can have ambiguous meanings without context & phrasing. The best one can do then is look around first for inspiration from others/elsewhere before going off a cliff on one's own and `Top` was taken from T-SQL. It's a natural choice given that much of LINQ's query syntax takes inspiration from SQL as well. The documentation then clearly states what the method does. You can't expect to embody the entire operational & logical semantics of method in its name.

And before you shoot me down for choosing `Top`, just think how poor [`SelectMany`][SelectMany] is compared to [`collect`][collect] and [`concat`][concat]. :smile: And if someone has never seen them before, I bet most will incorrectly guess what they do based on just the method name (looking at `Zip` here too) and without looking up the doc.


[SelectMany]: https://msdn.microsoft.com/en-us/library/system.linq.enumerable.selectmany.aspx
[collect]: https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.collect%5B%27t,%27u%5D-function-%5Bfsharp%5D
[concat]: https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.concat%5b't%5d-function-%5bfsharp%5d

**Comment by fsateler** [comment]
Indeed, [we've struggled in the past with names](https://github.com/morelinq/MoreLINQ/issues/131) :smile: . However, I hope I can convince you to change this one (either the name or the signature).

> `Top` was taken from T-SQL

I imagined so. One problem with this is that T-SQL `TOP` does not imply ordering. The ordering has to be given explicitly in a separate `ORDER BY` clause. 
BTW, I think `Top` is a reasonable name, but not for this behavior.

> The documentation then clearly states what the method does.

Well, I'm not particularly fond of how LINQ `OrderBy` implies direction without encoding it in the name. I very much prefer the [MoreLINQ version](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_OrderBy__2.htm), as it has an explicit parameter to specify it, thus making mistakes a bit harder. 
The problem with implicitness is that it is easy to forget and is not evident. As you can probably guess, when I read the documentation, it totally escaped me that `OrderBy` implies ascending order, and thus it would select the lowest `count` elements.

> You can't expect to embody the entire operational & logical semantics of method in its name.

Of course not. But we can try to at least not conflict expectations. A contradicting name is worse than a meaningless name.

So, I suggest to either:

1. Change the name to something that doesn't imply sort direction (or that implies to the correct direction). `BottomBy` comes to mind but is kind of ugly. At the same time, add a  note to the documentation making explicit the `OrderBy` direction implication.
2. Change the signature so that direction becomes explicit, and thus leaving no room for misinterpretation.

I would favor option 2. If you think that is acceptable, I can post a PR.

**Comment by fsateler** [comment]
Hmm. It seems I have several times missed that the return value documents the order. So change (1) above to "also add a note to the Remarks or Summary section"

**Comment by atifaziz** [comment]
In general most sorting APIs I've encountered where the comparer is optional assume ascending order. Even LINQ query syntax does so with the [`orderby`](https://msdn.microsoft.com/en-us/library/bb383982.aspx) clause without the `ascending` qualification. I'm afraid it's a lost battle because while we could fix that for `Top`, it can't be done for `OrderBy`. For someone with reasonable LINQ experience, there's no element of surprise.

> Change the signature so that direction becomes explicit, and thus leaving no room for misinterpretation.

That's the same as removing [the overload that make the comparer optional](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Top__1.htm) and that's not cool.

It would help if you could look around other libraries, environments & literature for inspiration on a good replacement for `Top` if the name bothers and naturally implies ranking by value rather than order. This is otherwise know as [partial sorting](https://en.wikipedia.org/wiki/Partial_sorting), so I would only give `PartialOrderBy` (ugly) or `PartialSort` (preferred) any thought at this time.

**Comment by fsateler** [comment]
> > Change the signature so that direction becomes explicit, and thus leaving no room for misinterpretation.

>That's the same as removing the overload that make the comparer optional and that's not cool.

I changed my mind, you are correct it is not cool (although I still do not like the name). Although having an additional overload with the direction would be useful as well.

> It would help if you could look around other libraries, environments & literature for inspiration on a good replacement for Top if the name bothers and naturally implies ranking by value rather than order. This is otherwise know as partial sorting, so I would only give PartialOrderBy (ugly) or PartialSort (preferred) any thought at this time.

I looked around . [Haskell uses partialSort](https://hackage.haskell.org/package/vector-algorithms-0.7.0.1/docs/Data-Vector-Algorithms-Intro.html#g:3), [C++ too](http://en.cppreference.com/w/cpp/algorithm/partial_sort) although it is slightly different because it apparently operates on the source sequence. For other languages I only found gists or stackoverflow answers.

What do you think about `PartialSort` and `PartialSortBy` ?  This name would not imply descending order, which helps in not breaking expectations.

I'll post  a PR changing the name and adding an overload with an `OrderByDirection` parameter.

**Comment by atifaziz** [comment]
With #188 merged, this is now released as part of [2.0 beta 4][2.0-beta4] (including [portable][2.0-beta4-pcl]):

- [`PartialSort`][PartialSort]
- [`PartialSortBy`][PartialSortBy]

[2.0-beta4]: https://www.nuget.org/packages/morelinq/2.0.0-beta04
[2.0-beta4-pcl]: https://www.nuget.org/packages/MoreLinq.Portable/2.0.0-beta04
[PartialSort]: https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_PartialSort.htm
[PartialSortBy]: https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_PartialSortBy.htm
