### ISSUE TITLE
The source code files that have individual operators do not load

### ISSUE THREAD

**Issue by Sathyaish** [morelinq/MoreLINQ#198]
I am running Visual Studio 2015 Update 3.

I just forked the project and when I opened **MoreLinq.sln** from my fork, it doesn't show any of the source code files that contain the individual operators.

![I don't see the files that contain source code for individual operators](https://raw.githubusercontent.com/Sathyaish/Temp/master/MoreLinq.png "I don't see the files that contain source code for individual operators")

Do I need to do something to load them in the project?

I opened the **MoreLinq.sln** file in notepad and it includes **MoreLinq\MoreLinq.csproj** file alright and the **MoreLinq\MoreLinq.csproj** file lists all the source files correctly.

Has anyone else had this issue?

**Comment by atifaziz** [comment]
If you expand the `MoreEnumerable.cs` node in the solution explorer, then you'll find the operators as files nested under as show in the screen shot below:

![capture](https://cloud.githubusercontent.com/assets/20511/18874560/844fda18-84c2-11e6-9d41-a318d08ff565.png)

**Comment by Sathyaish** [comment]
Thank you.
