### ISSUE TITLE
Sequence to array by index

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#202]
Turns a sequence to an array where each element of the sequence takes a position in the array based on the element's index (determined by a function of the element).

``` c#
static partial class MoreEnumerable
{
    public static T[] ToArrayByIndex<T>(this IEnumerable<T> source,
        Func<T, int> indexSelector) =>
        source.ToArrayByIndex(indexSelector, (e, _) => e);

    public static TResult[] ToArrayByIndex<T, TResult>(this IEnumerable<T> source,
        Func<T, int> indexSelector, Func<T, TResult> resultSelector) =>
        source.ToArrayByIndex(indexSelector, (e, _) => resultSelector(e));

    public static TResult[] ToArrayByIndex<T, TResult>(this IEnumerable<T> source,
        Func<T, int> indexSelector, Func<T, int, TResult> resultSelector)
    {
        var indexed = source.Select(e => new KeyValuePair<int, T>(indexSelector(e), e)).ToArray();
        var array = new TResult[indexed.Max(e => e.Key) + 1];
        foreach (var e in indexed)
            array[e.Key] = resultSelector(e.Value, e.Key);
        return array;
    }

    public static T[] ToArrayByIndex<T>(this IEnumerable<T> source, int length,
        Func<T, int> indexSelector) =>
        source.ToArrayByIndex(length, indexSelector, (e, _) => e);

    public static TResult[] ToArrayByIndex<T, TResult>(this IEnumerable<T> source, int length,
        Func<T, int> indexSelector, Func<T, TResult> resultSelector) =>
        source.ToArrayByIndex(length, indexSelector, (e, _) => resultSelector(e));

    public static TResult[] ToArrayByIndex<T, TResult>(this IEnumerable<T> source, int length,
        Func<T, int> indexSelector, Func<T, int, TResult> resultSelector)
    {
        var array = new TResult[length];
        foreach (var e in source)
        {
            var i = indexSelector(e);
            if (i < array.Length)
                array[i] = resultSelector(e, i);
        }
        return array;
    }
}
```

Suggestions for a better name welcome. 😃

**Comment by fsateler** [comment]
What is the use case of this? Why isn't a `Dictionary<int, T>` sufficient? If order is important, a `SortedList<int, T>` can easily wrap the dictionary.

As to name, so far all functions end in `By` when they take a similar parameter, so maybe change to `ToArrayIndexedBy`?

**Comment by atifaziz** [comment]
> What is the use case of this? 

When you want to go from a sequence that describes a sparse array (key is the array index) into one that is dense. The resulting array, while _densely allocated_, may appear _sparsely populated_ if the type of the element is a reference. In other words, if no element maps to a particular index then that index would assume the default value of `null`.

Another way to also look at the use case is normalization of keys into a continuous integer space:

```c#
var q = @"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Integer ultricies dignissim aliquet. Etiam ac rutrum quam, 
    ac aliquam elit. Phasellus at cursus metus. Vestibulum 
    ante ipsum primis in faucibus orci luctus et ultrices 
    posuere cubilia Curae; Donec neque lacus, tincidunt ut 
    rutrum et, molestie in dolor."
        .Split()
        .Select(s => s.Trim())
        .Where(s => s.Length > 0)
        .GroupBy(s => char.ToLowerInvariant(s[0]))
        .ToArrayByIndex(26, g => g.Key - 'a');
```

Words are grouped by their starting character in the alphabet space normalized into integers going from 0 = a to 25 = z. The resulting array will always be 26 elements long. Where no group was produced, you will have a `null` in the array.

> Why isn't a `Dictionary<int, T>` sufficient?

Sure a dictionary could do but wouldn't be efficient when you what really want and can do with is an array. [`TryGetValue`](https://msdn.microsoft.com/en-us/library/bb347013.aspx) is also [impossible to use in a LINQ expression until we get _out variables_ in C# 7](https://github.com/dotnet/roslyn/issues/6183#issuecomment-156362567). With an array, you just index into it if the size (key space length) is known in advance or use [`ElementAtOrDefault`](https://msdn.microsoft.com/en-us/library/bb494386.aspx) in case the result array may be shorter.

**Comment by fsateler** [comment]
OK, I understand. I'm not sure this would be a widely used operation, but I guess this depends on the type of apps one is building.

BTW, I have some comments on the code, maybe it's best to follow the usual PR flow so people can comment on it? Quoting code in comments is a bit cumbersome.


PS: 
> TryGetValue is also impossible to use in a LINQ expression

Which is why in almost all my projects I have the following extension method:

```csharp
public static TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dict, TKey key, TValue value) {
    TValue result;
    if (dict.TryGetValue(key, out result)) {
        return result;
    }
    else {
        return value;
    }
}
```

**Comment by atifaziz** [comment]
> maybe it's best to follow the usual PR flow so people can comment on it? Quoting code in comments is a bit cumbersome.

I agree and meant to do that next. This issue was just a to-do note meanwhile to park the idea until I got round to turning it into a PR (granted it doesn't take more time but I had a train to catch 😄). I just didn't think I'd be getting feedback so soon but appreciate all your input and challenging the idea overall.

> Which is why in almost all my projects I have the following extension method: …

Understandably, and [as do I](https://bitbucket.org/raboof/mannex/src/eb3d025bb06a7a8ff42e640dd4fbf3746d77145f/src/Collections/Generic/Dictionary.cs?at=default&fileviewer=file-view-default#Dictionary.cs-41:63). I didn't mean to apply this operation is a way around `TryGetValue`.

> but I guess this depends on the type of apps one is building.

I guess so too and I think it depends more on how you decide to slice & dice a problem than perhaps on the type of application. I could certainly give more background if you're interested.

**Comment by fsateler** [comment]
>>but I guess this depends on the type of apps one is building.
>
> I guess so too and I think it depends more on how you decide to slice & dice a problem than perhaps on the type of application. I could certainly give more background if you're interested.

It could be useful. Your example, although it explains well what the code does, does not explain why prefer this over a `Dictionary<int, T>`.  You then claim that using a dictionary is not as efficient. While I buy this argument (I have complained about performance in the past), I'm fairly certain the type of application needs to be very specific to care about indexing speed 😉 .

**Comment by atifaziz** [comment]
@fsateler PR #204 is here so fire away!

**Comment by atifaziz** [comment]
>  I'm fairly certain the type of application needs to be very specific to care about indexing speed

To be honest, it's more about convenience than performance.

If you have _dense containers_ like two arrays, you can zip them to combine into one for processing. With dictionaries, you'd be _joining_ on a key, sorting and then dealing with gaps to realign (or use a full-outer join). Both will logically do the same but one run slower, and more important, read less natural.

> Your example, although it explains well what the code does, does not explain why prefer this over a Dictionary<int, T>.

Fair enough. Here's a more complex example then:

```c#
var q = 
    from gs in new[]
    {
        /*--+---+---+---+---+---+---+---+
        + A | B | C | D | E | F | G | H |
        +---+---+---+---+---+---+---+---+
        | 1 |   | 2 |   |   | 3 |   |   |
        +---+---+---+---+---+---+---+---+
        |   | 4 | 5 |   |   | 6 |   | 7 |
        +---+---+---+---+---+---+---+--*/
        from s in @"
            A1:1
            C1:2
            F1:3
            B2:4
            C2:5
            F2:6
            H2:7
            ".Split('\n')
        select s.Trim() into s
        where s.Length > 0
        select s.Split(':') into kv
        let a = Address.ParseA1(kv[0]) // using A1; see https://github.com/atifaziz/A1
        select new { a.Col, a.Row, Num = double.Parse(kv[1]) } into cell
        group cell by cell.Row
    }
    // above is mostly parsing the input plus grouping cells into rows
    // below is the real processing...
    select gs.ToArrayByIndex(2, g => g.Key, g => g.ToArrayByIndex(e => e.Col, e => e.Num)) into rows
    select rows.Select(r => r ?? new double[0]).ToArray() into rows
    from sum in rows[0].ZipLongest(rows[1], (a, b) => a + b)
    select sum;

    
Console.WriteLine(q.ToDelimitedString(Environment.NewLine));
```

So the input is like a spreadsheet _sparsely_ described as a cell per line. Each cell itself is described as an address and value. The query is designed to sum the values on the first two rows. The actual processing I am doing is a lot more complex but the above example captures the essence and demonstrates how `ToArrayByIndex` helped make things simpler.

**Comment by fsateler** [comment]
Thanks for the more complete example, it makes more sense now.

**Comment by atifaziz** [comment]
Another less obvious use case for `ToArrayByIndex` is to implement partitioning to _x_ buckets:

```c#
var sample =
    MoreEnumerable.Random(-100, 100).Take(10).ToArray();
    
var q =
    sample.Assert(e => e != 0)
          .GroupBy(e => e > 0)
          .ToArrayByIndex(2, // false + true cases
                          g => g.Key ? 1 : 0, // int -> bool
                          g => new { Sum = g.Sum(), Trades = g.Count() })
          .Fold((s, b) => new { Sells = s, Buys = b });

Console.WriteLine(q);
```

So if `sample` is { -56, 67, 16, 34, 81, 5, -48, 61, 60, -62 } then the output will be:

    { Sells = { Sum = -166, Trades = 3 }, Buys = { Sum = 324, Trades = 7 } }
