### ISSUE TITLE
Please add a "None" method

### ISSUE THREAD

**Issue by UweKeim** [morelinq/MoreLINQ#203]
I suggest to add a shortcut to `!Any()`, just like [asked on SO](http://stackoverflow.com/q/8741439/107625).

I.e. I want the opposite of the `Any()` method.

(This is [already present](https://github.com/thomaslevesque/Linq.Extras/blob/master/Linq.Extras/None.cs) in the Linq.Extras library, I would prefer to stick with MoreLINQ only)

**Comment by atifaziz** [comment]
`None` is already available as part of [Linq.Extras](https://github.com/thomaslevesque/Linq.Extras/) that is [published](https://www.nuget.org/packages/Linq.Extras) so anyone can use it if needed. I don't see the point of duplicating it here. It also has a trivial implementation that can be copied & pasted (if taking an additional dependency is a concern) without worrying about servicing for bugs.

**Comment by UweKeim** [comment]
Thanks. My concern would be to have lots of duplicate methods if using both Linq.Extras and MoreLINQ together in the same project. 

Just imagine always having to worry about whether e.g. `DistinctBy` comes from MoreLINQ or Linq.Extras sounds too complicated (or results in ReSharper asking me to choose from one or the other).

Anyway, I do understand that you want to keep MoreLINQ clean.

**Comment by atifaziz** [comment]
@UweKeim I understand the issue about introducing duplicates & unfortunately C# provides no way to resolve those conflicts today. I proposed [a solution for MoreLINQ some time ago that could make it conflict-free](https://github.com/morelinq/MoreLINQ/issues/60#issuecomment-133518416).
