### ISSUE TITLE
Add support for enumerable noise sets

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#21]
A useful method to perform algorithms that use noise would be to set up the noise data as an enumeration, much like `Enumerable.Range(int start, int count)`. The proposed method would be `Enumerable.Noise(int seed)`, yielding infinite procedural noise generation. 

Then, to take five random numbers one would call `var randomNumbers = Enumerable.Noise(seed).Take(5);`

There is alot of uses for floating point noise aswell, mainly in procedural fractal generation. 

```c#
Enumerable.Noise<float>(seed); // Generate noise between 0-1
Enumerable.NoiseSigned<float>(seed); // Generate noise between (-1)-1
```

Due to the problem of infinite enumeration, `foreach` loops on raw enumerations of noise would be problematic. Perhaps one should set up a maximum range of numbers?

---
Originally reported on Google Code with ID 21

Reported by `l.jarvensivu` on 2009-03-25 14:40:32

**Comment by fsateler** [comment]
There is already a `Random` method, so I think this is already done.

**Comment by atifaziz** [comment]
@fsateler Agree & thanks!
