### ISSUE TITLE
Conflict-free extension methods

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#214]
**Note:** This is forked from a [comment](https://github.com/morelinq/MoreLINQ/issues/60#issuecomment-133518416) in issue #60.

With extension methods, there's always a potential for conflict with some future version of .NET or another library so following is a proposal to come up with a future-proof and conflict-free solution that puts the user in control.

At the present, when you import the `MoreLinq` namespace, you get all operators whether you like it or not. What would be helpful is to be able to choose exactly the operators one would like to import and avoid those that are not needed or would otherwise conflict with either the .NET Framework or another library referenced in the user's project. This could be done by breaking up `MoreEnumerable` into distinct classes (as opposed to the single partial class it is today), hosting only a single operator along with its overloads. Each `MoreEnumerable` class would then be wrapped in a namespace named after the operator it hosts.

The following sample illustrates this approach:

```c#
#pragma warning disable 1591

using System;
using System.Collections.Generic;

namespace MoreLinq
{
    namespace NoConflict
    {
        namespace DistinctBy
        {
            public static class MoreEnumerable
            {
                public static IEnumerable<TSource> DistinctBy<TSource, TKey>(this IEnumerable<TSource> source,
                    Func<TSource, TKey> keySelector)
                {
                    return MoreLinq.MoreEnumerable.DistinctBy(source, keySelector);
                }

                public static IEnumerable<TSource> DistinctBy<TSource, TKey>(this IEnumerable<TSource> source,
                    Func<TSource, TKey> keySelector, IEqualityComparer<TKey> comparer)
                {
                    return MoreLinq.MoreEnumerable.DistinctBy(source, keySelector, comparer);
                }
            }            
        }

        namespace EquiZip
        {
            public static class MoreEnumerable
            {
                public static IEnumerable<TResult> EquiZip<TFirst, TSecond, TResult>(this IEnumerable<TFirst> first,
                        IEnumerable<TSecond> second,
                        Func<TFirst, TSecond, TResult> resultSelector)
                {
                    return MoreLinq.MoreEnumerable.EquiZip(first, second, resultSelector);
                }
            }
        }
    }
}
```

Adding it to the current `MoreLinq` project has the effect of making both options available. The user could import `MoreLinq` namespace as today and be done with it. Alternatively there's a new `NoConflict` namespace (in the spirit of jQuery) that uses the new approach with some select operators, and using which, the user would import `MoreLinq.NoConflict.DistinctBy` just to bring in and use that operator.

The `NoConflict` approach has the benefit of providing the conflict-prone or conflict-free option to the user while maintaining backward compatibility. However, it does complicate the life of MoreLINQ contributors going forward for these reasons:

- The signatures have to be duplicated and kept in sync
- The XML doc would have to be duplicated and kept in sync
- The conflict-free, forwarding, implementations of the operators won't be tested, meaning there's a small chance that they incorrectly call the base implementations

In light of the above, it would be best to break compatibility in a future major version and just do with the _namespace per method_ approach (and minus `NoConflict`).

**Comment by jskeet** [comment]
> Each `MoreEnumerable` class would then be wrapped in a namespace named after the operator it hosts.

That's unnecessary with C# 6 and `using static`. Users could just import the class they want. I'd argue that's a lot cleaner than creating a huge number of namespaces, but it has two downsides:

- The class couldn't be named the same as the extension methods it contains
- It's not as friendly to pre-C#-6 users, although I'd personally plan for the future.

**Comment by fsateler** [comment]
>>Each MoreEnumerable class would then be wrapped in a namespace named after the operator it hosts.
>
>That's unnecessary with C# 6 and `using static`. Users could just import the class they want. I'd argue that's a lot cleaner than creating a huge number of namespaces, but it has two downsides:

Oh, this is a very good idea! I didn't know `using static` a class also imported the extension methods (although makes sense in retrospect).

>
> - The class couldn't be named the same as the extension methods it contains

Slight annoyance, but easily worked around: `More${Method}` , or `${Method}Ext`

> - It's not as friendly to pre-C#-6 users, although I'd personally plan for the future.

It's not like pre-c# 6 users can't use morelinq, they just don't have a way to avoid conflicts (which they don't anyway today).

The only question is wether to make this the default or opt-in. If the default, then `MoreEnumerable` stays as it is, and `MoreLinq.NoConflict` contains the per-method classes that are just thin wrappers.

**Comment by atifaziz** [comment]
> …and `MoreLinq.NoConflict` contains the per-method classes that are just thin wrappers.

I don't think we want to have to maintain that or ask everyone submitting a PR to also write those wrappers. As you said, users on C# versions before 6 wouldn't be worse off than they are today. If they have a conflict in their project then it can be resolved locally by adding a wrapper to their project for the one or two cases where the conflict exists.

If we go with favoring `using static` then we only need to resolve the following issue:

> The class couldn't be named the same as the extension methods it contains

Taking `EquiZip` as an example, the container class could be called as shown in the `using static` usages below:

1. `using static MoreLinq.EquiZipOp;`
2. `using static MoreLinq.EquiZipModule;`
3. `using static MoreLinq.EquiZipExtension;`

My preference is 2 although 3 would be keeping tradition/convention. How's this looking?

This `using static` approach also requires avoiding conflicts across methods extending _different_ interfaces but sharing the _same_ name. For example, we have `Partition` for sequences & `Partition` for groupings as being proposed in #210. How would you go about importing one and not the other. Call the latter `PartitionGroup`? Actually, this problem would have to be addressed when breaking down methods by namespaces.

And perhaps this is obvious but methods like `Generate` would have to stay on `MoreEnumerable`.

**Comment by fsateler** [comment]
>> …and MoreLinq.NoConflict contains the per-method classes that are just thin wrappers.
>
> I don't think we want to have to maintain that or ask everyone submitting a PR to also write those wrappers. 

Indeed, that would be very annoying. An alternative solution would be to have it backwards, and make `MoreEnumerable` the thin wrapper class. This way it would be fairly easy to create the wrappers via a T4 template. The downside would be that a double-compile would be needed to generate a library: once to be able to load the assembly with the method, another for the library to contain the thin wrapper. 

The reason why I think about keeping the previous class is worthwhile is to avoid breaking binary compatibility. I'd hate to be unable to upgrade MoreLinq because another library I depend on happens to depend on MoreLinq but at a lower version.

> If we go with favoring using static then we only need to resolve the following issue:

>> The class couldn't be named the same as the extension methods it contains

I'm fine with any of the proposed names.

> For example, we have `Partition` for sequences & `Partition` for groupings as being proposed in #210. How would you go about importing one and not the other. Call the latter `PartitionGroup`?

Now that you mention it, if they do different things they should be named differently (but we should move this to a separate issue).

**Comment by atifaziz** [comment]
> I don't think we want to have to maintain that or ask everyone submitting a PR to also write those wrappers.

One workaround for this would be to write a generator for the wrappers, using Roslyn to discover the public API to be wrapped. This way, there would only be the core implementation that would need maintaining. A contributor with a PR could then be asked to run the generator to update the wrappers.

**Comment by atifaziz** [comment]
The experimentation in PR #235 has taken shape and adds “no-conflict” wrapper methods at [no run-time cost](https://github.com/morelinq/MoreLINQ/pull/235#issuecomment-271914747) for a release build. Since the conflict-free wrappers are opt-in via a sub-namespace (`NoConflict`), the library remains 100% backward compatible and so we don't have to wait for [the next major revision](https://github.com/morelinq/MoreLINQ/milestone/2). The only thing I'd like to review now is the `MoreLinq.NoConflict` namespace name. Can we do better? What about `MoreLinq.Extensions`? Is that pretending to be what it's not?

**Comment by fsateler** [comment]
I think it depends on what is planned for the future:

1. The extension methods will be removed from `MoreEnumerable` at some point.
2. The extension methods will coexist in the main and `NoConflict` namespaces for the foreseeable future.

In the second case, I think `NoConflict` is a better name, since it correctly conveys its reason to exist. In the first case, I guess `Extensions` is a better name, because in the future one would be `using MoreLinq.Extensions`, which does look nice 😄 .

**Comment by atifaziz** [comment]
> In the second case, I think `NoConflict` is a better name, since it correctly conveys its reason to exist. In the first case, I guess `Extensions` is a better name, because in the future one would be `using MoreLinq.Extensions`, which does look nice 😄 . 

That's exactly why I am torn between the two.

> The extension methods will be removed from MoreEnumerable at some point.

I see `MoreLinq` still being used for 95% of the time for sake of simplicity. Importing via `NoConflict` will be for the rare instances you run into a conflict, and even then, it'll be scoped to usually a single file (or even method!) in a project where the conflict needs to be resolved. So yeah, for the foreseeable future, I see point 2 being the way.

**Comment by leandromoh** [comment]
> Importing via NoConflict will be for the rare instances you run into a conflict, and even then, it'll be scoped to usually a single file (or even method!). So yeah, for the foreseeable future, I see point 2 being the way.

Since the conflic scenario would be rare, why not let user call the method with the static syntaxe? 
`MoreEnumerable.DistinctBy(source)` for example.

**Comment by atifaziz** [comment]
> why not let user call the method with the static syntax in this rare cases? For example `MoreEnumerable.DistinctBy(source)`.

Because it's really ugly when you're method chain runs long and you need to resolve a conflict smack in the middle of it.

**Comment by lostmsu** [comment]
I am newcomer to MoreLinq, and this solution looks bad to me. I took a good 10 minutes to figure out the best solution to the .Append conflict, and I will probably forget it by the next time I hit it. Multiply it say by 1000 developers a year, and you waste an 5 years of developer lifetime per year because of it.

I imagine removing or renaming those conflicted methods would take much less time.

**Comment by atifaziz** [comment]
@lostmsu Did you read the “[Usage](https://github.com/morelinq/MoreLINQ/blob/v3.0.0/README.md#usage)” section that's right there as the _first_ section in the [README](https://github.com/morelinq/MoreLINQ/blob/v3.0.0/README.md)?
