### ISSUE TITLE
source packages should be marked as developmentDependency

### ISSUE THREAD

**Issue by SurajGupta** [morelinq/MoreLINQ#224]
The source packages should be marked as a `developmentDependency`.  If not, then consumers of a package that dependent on the source package will have to install the source packages, despite that code already being compiled-into the dependency.

please see `developmentDependency` here:
https://docs.nuget.org/ndocs/schema/nuspec

**Comment by atifaziz** [comment]
Fair point. Can I ask you to [open this issue](https://github.com/morelinq/srcpkg/issues/new) for tracking in the [repo for the source packages](https://github.com/morelinq/srcpkg)?

**Comment by SurajGupta** [comment]
done
