### ISSUE TITLE
Replace ExpectedException with Assert.Throws in unit tests

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#227]
[`ExpectedException` has been removed starting with NUnit 3](https://github.com/nunit/nunit/issues/113). Unit tests need to be adjusted to use `Assert.Throws` instead, which is the recommended and better way.

Meanwhile #226 adds a local `[ExpectedException]` so tests using that attribute can compile and run unchanged with NUnit 3. The local `[ExpectedException]` implementation should be removed when migration to using `Assert.Throws` is complete.

Test files that need addressing are:

- [ ] `AcquireTest.cs`
- [ ] `AssertCountTest.cs`
- [ ] `AssertTest.cs`
- [ ] `AtLeastTest.cs`
- [ ] `BatchTest.cs`
- [ ] `CartesianTest.cs`
- [ ] `ConcatTest.cs`
- [ ] `ConsumeTest.cs`
- [ ] `CountByTest.cs`
- [ ] `DistinctByTest.cs`
- [ ] `EndsWithTest.cs`
- [ ] `EquiZipTest.cs`
- [ ] `ExceptByTest.cs`
- [ ] `ExcludeTest.cs`
- [ ] `FoldTest.cs`
- [ ] `ForEachTest.cs`
- [ ] `FullGroupJoinTest.cs`
- [ ] `GenerateTest.cs`
- [ ] `GroupAdjacentTest.cs`
- [ ] `IncrementalTest.cs`
- [ ] `IndexTest.cs`
- [ ] `InterleaveTest.cs`
- [ ] `LagTest.cs`
- [ ] `LeadTest.cs`
- [ ] `MaxByTest.cs`
- [ ] `MinByTest.cs`
- [ ] `NestedLoopTest.cs`
- [ ] `PadTest.cs`
- [ ] `PairwiseTest.cs`
- [ ] `PartitionTest.cs`
- [ ] `PermutationsTest.cs`
- [ ] `PipeTest.cs`
- [ ] `PreScanTest.cs`
- [ ] `PrependTest.cs`
- [ ] `RandomSubsetTest.cs`
- [ ] `RandomTest.cs`
- [ ] `RepeatTest.cs`
- [ ] `RunLengthEncodeTest.cs`
- [ ] `SegmentTest.cs`
- [ ] `SingleOrFallbackTest.cs`
- [ ] `SkipUntilTest.cs`
- [ ] `SortedMergeTest.cs`
- [ ] `StartsWithTest.cs`
- [ ] `SubsetTest.cs`
- [ ] `TagFirstLastTest.cs`
- [ ] `TakeEveryTest.cs`
- [ ] `TakeLastTest.cs`
- [ ] `TakeUntilTest.cs`
- [ ] `ToDataTableTest.cs`
- [ ] `ToDelimitedStringTest.cs`
- [ ] `TraceTest.cs`
- [ ] `TraverseTest.cs`
- [ ] `WindowedTest.cs`
- [ ] `ZipLongestTest.cs`
- [ ] `ZipShortestTest.cs`

**Comment by fsateler** [comment]
This[1] will break most pending PRs (does the fix for #226 do so too?). Rebasing on top of current master will probably be required for most PRs. To mitigate a bit this problem, usage of `ExpectedException` should be advised against during review.

**Comment by atifaziz** [comment]
The PRs won't break because of `[ExpectedException]` because that has been added privately to the test project until this issue is closed and it can be completely removed (preventing others from using it in the future). If `TestCase` is being used then they'll break. Rebasing or adjusting before merging is best. However, changing the few PRs that are open right now is peanuts compared to the 27 files in the test code base that's still using `[ExpectedException]`.

**Comment by atifaziz** [comment]
Since this entails a lot of manual work, it might be interesting to try and tackle this more smartly by automating the following steps via Roslyn:

1. Load up and parse each test file
1. Find methods decorated with `[ExpectedException]`
1. Extract the exception type as the first argument to `[ExpectedException]`. 
1. Wrap the existing body into a statement lambda that is then passed to `Assert.Throws<T>` and use the exception type discovered in the previous step for `T`.
1. Remove the `[ExpectedException]` attribute
1. Write back the new syntax tree to the file.

**Comment by GeorgeVovos** [comment]
I've updated the code.
Shall I delete the Attribute?

**Comment by atifaziz** [comment]
@GeorgeVovos Cool. Do you have a PR to submit for review?

**Comment by GeorgeVovos** [comment]
@atifaziz I do now...
https://github.com/morelinq/MoreLINQ/pull/233

Let me now if there are any issues
