### ISSUE TITLE
Add ChunkBy (Group Results by Contiguous Keys)?

### ISSUE THREAD

**Issue by pbolduc** [morelinq/MoreLINQ#237]
I recently found I need to add a [Group Results by Contiguous Keys (ChunkBy)](https://msdn.microsoft.com/en-us/library/cc138361.aspx) Linq extension method our our project.  Could be useful addition.

**Comment by atifaziz** [comment]
Doesn't [`GroupAdjacent`](https://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_GroupAdjacent.htm) already cover this already?

**Comment by pbolduc** [comment]
Yes it does. Sorry, didn't review everything in this project yet.
