### ISSUE TITLE
Transpose function

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#239]
The transpose function transposes the rows and columns of its argument. For example,

`transpose` applied to `[[1,2,3],[4,5,6]]` returns `[[1,4],[2,5],[3,6]]`

If some of the rows are shorter than the following rows, their elements are skipped:

`transpose` applied to `[[10,11],[20],[],[30,31,32]]` returns `[[10,20,30],[11,31],[32]]`

I'm planning to submit a PR for this.

What do you think?

**Comment by atifaziz** [comment]
> If some of the rows are shorter than the following rows, their elements are skipped

I wonder how could this, _as a default behaviour_, could be practically useful that the output doesn't confuse or surprise anyone?

**Comment by leandromoh** [comment]
> I wonder how could this, as a default behaviour, could be practically useful that the output doesn't confuse or surprise anyone?

For me sounds natural to ignore "empty elements". Haskell's transpose behaves this way.

But I agree that we should give the user more overloads, so I also think about one overload where user can provide an `T` value for fill the gaps and maybe another overload that throw an `InvalidOperationException` when use pass a matrix where some of the rows are shorter than others...

Summary: this is the overloads I imagine:

- ingnore empty: `[[10,11],[20],[],[30,31,32]].transpose() returns [[10,20,30],[11,31],[32]]`

`IEnumerable<IEnumerable<T>> Transpose<T>(this IEnumerable<IEnumerable<T>> source)
`
- fill empty with value provide: `[[10,11],[20],[],[30,31,32]].transpose(X) returns [[10,20,X,30],[11,X,X,31],[X,X,X,32]]`

`IEnumerable<IEnumerable<T>> Transpose<T>(this IEnumerable<IEnumerable<T>> source, T emptyRepresentation)`

- throw exception: `[[10,11],[20],[],[30,31,32]].transpose() throws Exception`
????

Need help for define the `Exception `overload.

Why do you think about the overloads?

**Comment by atifaziz** [comment]
> For me sounds natural to ignore "empty elements"

If it sounds natural to you then care to explain _why so_? :smile: What are the corner cases of skipping or not skipping? Just because Haskell does it that way doesn't mean we should copy without understanding the value proposition of that _as a default_. Also, think about the implications if one list is _infinite_.

I'm not in favour of the overloads. `Transpose` is like a `ZipMany` or `Zip` for list of lists and the way we did this for `Zip` is to have a separate method for each distinct behaviour ([`EquiZip`][EquiZip], [`ZipLongest`][ZipLongest] & [`ZipShortest`][ZipShortest]). See #24 and #6 for background and discussion. It would seem to me that it's better to do the same here instead of overloading.


[EquiZip]: http://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_EquiZip.htm
[ZipLongest]: http://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_ZipLongest__3.htm
[ZipShortest]: http://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_ZipShortest.htm

**Comment by leandromoh** [comment]
> If it sounds natural to you then care to explain why so? :smile:

I talked with with some friends about it and that is what I heard:

- "`IEnumerable `don't have the concept of "empty elements", so is natural jut ignore it"

- "Since `IEnumerable`'s, may have different length, make sense the result `IEnumerable`'s also have different length. I would expect the "empty elements" would be keep if the `transpose` signature was for two dimensional array (e.g., `double[ , ]`)"

- "Since `tranpose` (in math) is just for matrix (list of equal-length lists), there is nothing defined about nonrectangular matrix (list of different-lenght lists)... so any behavior is acceptable because there isnt a standard".

I agree manly with the first two thoughts.


>  Also, think about the implications if one list is infinite.

I already have a sketch of `transpose`'s implementation (ingnoring empty and pad overloads), both works with infinit list of infinit lists. I tested with something like:

```
var table = NaturalNumbers().Select(n => new InfiniteSequence(n)); 

foreach (var inner in table.Transpose().Take(3).Select(x => x.Take(9)))
{
    foreach (var x in inner)
    {
       Console.Write(x + " ");
    }
    Console.WriteLine();
}
```
The output was the expected:

```
0 1 2 3 4 5 6 7 8
0 1 2 3 4 5 6 7 8
0 1 2 3 4 5 6 7 8
```

> have a separate method for each distinct behaviour 

I consider distinct methods when the overloads signrature and its documentation by itself are not enough to distinct each behavior (or if becames too much complicated). 

In my opinion, the difference between the first 2 overloads can easyly be understand. Only EquiTranspose receive a different name to explicit its potentially dangerous behavior and avoid user mistakes.

- `Transpose<T>(this IEnumerable<IEnumerable<T>> source)`
- `Transpose<T>(this IEnumerable<IEnumerable<T>> source, T pad)`
- `EquiTranspose<T>(this IEnumerable<IEnumerable<T>> source)`

**Comment by leandromoh** [comment]
@atifaziz what do you think about target `TransposeShortest `and `TransposeLongest` to release 2.4 ?

**Comment by atifaziz** [comment]
@leandromoh I don't think this one has been completely thought out yet.

**Comment by leandromoh** [comment]
I had understood the problem was define which overload would be the `default`.
However, since we will use differents methods instead of overloads, I thought the problem was solved.

What do you think is missing to define?

**Comment by leandromoh** [comment]
@atifaziz I would like to submit a PR only for the transpose method that ignore empty entries, for now. What do you think? The method name can bem defined ar PR time.

[[10,11],[20],[],[30,31,32]].transpose() returns [[10,20,30],[11,31],[32]]
