### ISSUE TITLE
Repeat overload without count (repeat forever)

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#248]
sometimes is usefull to create an infinit list from a seed value where all elements are equals to seed.
usefull for padding some list, for example:

```
var source = Enumerable.Range(1,5);
var pad = 0;
var notLeastThan10 = source.Concat(pad.Cycle()).Take(10); // [1,2,3,4,5,0,0,0,0,0]
```

or to cycle a finite list into a circular one
`var sourceCircular = source.Cycle(); // [1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,...]` 

so, my propouse is to create the follow methods:

1. `IEnumerable<TSource> Cycle<TSource>(this TSource source)`
2. `IEnumerable<TSource> Cycle<TSource>(this IEnumerable<TSource> source)`

we can also use the first overload with lists:

```
var list = Enumerable.Range(1,3);
var list3Times = Cycle<IEnumerable<int>>(list); // [[1,2,3],[1,2,3],[1,2,3],...]
```

**Comment by fsateler** [comment]
The second method looks a lot like [Repeat](https://morelinq.github.io/2.1/ref/api/html/M_MoreLinq_MoreEnumerable_Repeat__1.htm), except there is no `count` argument. Adding this as an overload sounds sensible to me.

OTOH, I'm not a fan of adding an extension method on `T`, as that effectively means adding a method to `object`.

**Comment by leandromoh** [comment]
> The second method looks a lot like Repeat, except there is no count argument. Adding this as an overload sounds sensible to me.

Really. It's a good idea.

> OTOH, I'm not a fan of adding an extension method on T, as that effectively means adding a method to object.

I dont think it's a problem. Sometimes it is just usefull. [Concat method use it](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Concat.cs#L35), for example.

**Comment by atifaziz** [comment]
@fsateler is right. This is just making `count` optional in [`Repeat`][repeat] so we wouldn't be introducing a new method called `Cycle` here (even if I like the name better).

Also, the second case of repeating a single value forever should be called `RepeatForever` to mean just that and is better off as a separate method. That said, I wouldn't be too in favour of adding it since it would be as trivial as writing `new[] { 0 }.Repeat()`.


[repeat]: https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Repeat__1.htm

**Comment by leandromoh** [comment]
> This is just making count optional in Repeat so we wouldn't be introducing a new method called Cycle here

Okay, i will add extra overload on PR.

> I wouldn't be too in favour of adding it since it would be as trivial as writing new[] { 0 }.Repeat().

But was not this strategy used for [Prepend](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Prepend.cs#L45
)?

**Comment by atifaziz** [comment]
> Was not this strategy used for [Prepend](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Prepend.cs#L45
)? Is not trivial to write `new[] { 0 }.Concat(numbers)` ?

Yes it is if you are starting out your query but if you're deep into the query chain and want to insert an element at the beginning then `Prepend` becomes quite handy, e.g.:

```c#
var csv =
    Enumerable.Range(1, 10)
              .Select(x => new[] { x, x * x }.ToDelimitedString(","))
              .Prepend("X,SQR")
              .ToDelimitedString(Environment.NewLine);
```

Output:

```
X,SQR
1,1
2,4
3,9
4,16
5,25
6,36
7,49
8,64
9,81
10,100
```

Also, `Prepend` is an extension of `IEnumerable<T>` and not `T`.

**Comment by leandromoh** [comment]
@atifaziz  I understood, thanks for the explanation. The PR will have only the extra overload so.
