### ISSUE TITLE
RFE: Extension method that acquires an IDisposable when iterating a sequence, and releases it afterwards

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#253]
An operation I've found myself doing is acquiring an `IDisposable` , iterating over a sequence, and then releasing the disposable. For example, this can be done to insert performance tracing into a long linq chain. The usual pattern would be:

```csharp
public static IEnumerable<T> DoSomething<T>(this IEnumerable<T> src) {
    using(MyDisposable()) {
      foreach(var item in src) {
         yield return item;
      }
   }
}
```

While the pattern is not difficult to implement, it usually enlarges the codebase as each disposable that wraps an enumerable gets its own function. I decided to generalize that, and maybe it would be useful for others.

The proposed signature would be:

```csharp
public static IEnumerable<T> Using<T>(this IEnumerable<T> src, Func<IDisposable> disposableGenerator);
```

I would make the function take a method that generates the disposable, because I think it is desirable that each iteration should get its own disposable.

I can prepare a PR if this function is desirable.

**Comment by atifaziz** [comment]
Have you looked at [`Using` from `System.Interactive`](https://github.com/Reactive-Extensions/Rx.NET/blob/ffe6e1e0bfa7783bf23e8c699ad993a884bf50c7/Ix.NET/Source/System.Interactive/Using.cs)? Looks awfully close to what you're suggesting.

**Comment by fsateler** [comment]
I just benchmarked the obvious foreach listed above versus a custom `IEnumerable`. In LINQPad running with optimization enabled the custom enumerable is about 20% faster for fast sequences (`Enumerable.Range`). The difference becomes smaller for slower sequences: `MoreEnumerable.Random` is about 6% faster.

**Comment by fsateler** [comment]
> Have you looked at Using from System.Interactive? Looks awfully close to what you're suggesting.

Oh, indeed I had not. Thanks for pointing that out.

That one does have the problem of not being an extension method of `IEnumerable<T>`, because it assumes the resource is needed to create the actual enumerable. That seems a reasonable use case, but different from the one I faced.

**Comment by atifaziz** [comment]
> That one does have the problem of not being an extension method of `IEnumerable<T>`, because it assumes the resource is needed to create the actual enumerable.

Except I don't think that's _the problem_. What you are suggesting seems like a side-effecting operation because the disposable generated is orthogonal to the query. It's more of a `Do` than a `Using` except the _do-action_ is over the lifetime of the query (as opposed to a usual `Do` that is per sequence element) and in fact delineated by _two_ actions invoked: _start_ (`disposableGenerator`) and _end_ (`Dispose`) of query. Am I completely off?

**Comment by fsateler** [comment]
> Except I don't think that's *the problem*.

Well, its a problem for me 😄 . The method itself is not problematic *per se*, it just doesn't solve my use case.

> What you are suggesting seems like a side-effecting operation because the disposable generated is orthogonal to the query. It's more of a Do than a Using except the do-action is over the lifetime of the query (as opposed to a usual Do that is per sequence element) and in fact delineated by two actions invoked: start (disposableGenerator) and end (Dispose) of query. Am I completely off?

Exactly. And it should involve the same sort of guarantees `using` does, namely that the action at the end will be invoked even if the sequence is short-circuited, even by an exception.

**Comment by atifaziz** [comment]
Right, in the case, [`Do` from `System.Interactive`](https://github.com/Reactive-Extensions/Rx.NET/blob/v3.1.1/Ix.NET/Source/System.Interactive/Do.cs#L81) comes closer:

```c#
// Lazily invokes an action for each value in the sequence, and executes an action upon successful or exceptional termination.
public static IEnumerable<TSource> Do<TSource>(
	this IEnumerable<TSource> source,
	Action<TSource> onNext,
	Action<Exception> onError,
	Action onCompleted
)
```

It's also an extension method for on the sequence, unlike `Using`. The only part that's missing now is an action for the start of iteration, like an `onStart` or `onBegin`. My next question is then, wouldn't it make sense to talk to the Ix folks first on enhancing what almost seems like an incremental enhancement of something that already exists? Failing that, we could imagine adding something like `DoUsing`. 😆 

BTW, I think if an `onStart` would ever get added, you would want it to thread a state (as a generalization) through the other actions. Here's what I'm thinking:

```c#
public static IEnumerable<T> Do<T, TState>(this IEnumerable<T> source,
    Func<TState> onStart,
    Action<TState, T> onNext,
    Action<TState> onCompleted,
    Action<TState, Exception> onError)
{
    var state = onStart();
    using (var e = source.GetEnumerator())
    while (true)
    {
        try
        {	        
            if (!e.MoveNext())
                break;
            onNext(state, e.Current);
        }
        catch (Exception ex)
        {
            onError(state, ex);
            break;
        }
        yield return e.Current;
    }
    onCompleted(state);
}
```

This way, you don't need to worry about the state being an `IDisposable` or not. You could then implement `DoUsing` as a specialization of the above:

```c#
public static IEnumerable<T> DoUsing<T>(this IEnumerable<T> source, Func<IDisposable> onStart) =>
    source.Do(onStart, delegate {}, s => s.Dispose(), (s, _) => s.Dispose());
```

But let's assume there's an overload for `Do` for times where you only care about side-effects during the start and end of iteration (folding `onCompleted` and `onError` into `onEnd`, as in a `finally`):

```c#
public static IEnumerable<T> Do<T, TState>(this IEnumerable<T> source,
    Func<TState> onStart,
    Action<TState, Exception> onEnd) =>
    source.Do(onStart, delegate {}, s => onEnd(s, null), onEnd);
```

With this, you'll see how the state can be used for timing without any reliance on the disposable pattern:

```c#
var q = Enumerable.Range(1, 10).Pipe(_ => Thread.Sleep(150));

foreach (var e in q.Do(() => Stopwatch.StartNew(), (sw, _) => Console.Error.WriteLine(sw)))
    Console.WriteLine(e);
```

**Comment by fsateler** [comment]
> Right, in the case, Do from System.Interactive comes closer

Indeed it does.

>My next question is then, wouldn't it make sense to talk to the Ix folks first on enhancing what almost seems like an incremental enhancement of something that already exists?

Yes, it makes sense. Posted as https://github.com/Reactive-Extensions/Rx.NET/issues/330

**Comment by fsateler** [comment]
I'm closing this now. If things don't go well over at the Ix side lets discuss again.
