### ISSUE TITLE
Feature request: Sequence and SequenceWith

### ISSUE THREAD

**Issue by WildCard65** [morelinq/MoreLINQ#259]
This feature request is for 2 extension methods:

```cs
public static IEnumerable Sequence(this IEnumerable<IEnumerable> enumerables)
{
    foreach (var enumerable in enumerables)
    {
        foreach (var item in enumerable)
            yield return item;
    }
}

public static IEnumerable<T> Sequence<T>(this IEnumerable<IEnumerable<T>> enumerables)
{
    foreach (var enumerable in enumerables)
    {
        foreach (var item in enumerable)
            yield return item;
    }
}
```
```cs
public static IEnumerable SequenceWith(this IEnumerable enumerable, params IEnumerable[] enumerables) // Concatenate enumerable and enumerables with enumerable first then call Sequence
public static IEnumerable<T> SequenceWith<T>(this IEnumerable<T> enumerable, params IEnumerable<T>[] enumerables) // Concatenate enumerable and enumerables with enumerable first then call Sequence
```

The use case for this is to allow iteration of multiple IEnumerable(<T>) instances as 1 singular one.

**Comment by atifaziz** [comment]
[`SelectMany`](https://msdn.microsoft.com/en-us/library/bb534336(v=vs.110).aspx) already does this and if you're using the query syntax then a nested `from` will have the same effect.

**Comment by fsateler** [comment]
In my projects I usually have this single liner:

```csharp
public static IEnumerable<T> Flatten<T>(this IEnumerable<IEnumerable<T>> src) => src.SelectMany(i => i);
```

I'm not sure if it's worth including in MoreLinq, as it is trivial to do.

**Comment by atifaziz** [comment]
> I'm not sure if it's worth including in MoreLinq, as it is trivial to do.

Yeah, I think having the ceremony of a whole project/library like MoreLINQ with unit testing and documentation is an overkill for mere one-line wrappers.

Closing this for now as it's principally covered by `SelectMany`.
