### ISSUE TITLE
Migrate projects to .NET Core Tools 1.0

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#261]
The `.xproj` and `project.json` files (based on preview versions) need to be migrated to `.csproj` now that [.NET Core Tools 1.0 is released](https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/).

Contributors not using Visual Studio 2017 will have to rely on IDEs like [Visual Studio Code](https://code.visualstudio.com/) or other editors supported by [OmniSharp](http://www.omnisharp.net/). This may already be the case anyhow for those not on Windows.

**Comment by atifaziz** [comment]
Initial attempt didn't go so well; see dotnet/cli#5973.

**Comment by atifaziz** [comment]
So according to dotnet/sdk#335 and @DustinCampbell's [words](https://github.com/dotnet/sdk/issues/335#issuecomment-273835465) there: 

> The high-order bit here is that cross-gen is broken for .NET Framework projects on all platforms but Windows.

This is a step backward. Unfortunately for us, building is breaking on Windows.

**Comment by DustinCampbell** [comment]
Note later in that issue that I noted that I was able to get OmniSharp's build (which targets net46 and netstandard1.6) working on OSX/Linux with a bit of trickery.

**Comment by atifaziz** [comment]
Thanks @DustinCampbell, [I noticed](https://github.com/dotnet/sdk/issues/335#issuecomment-291487227) and will give it a crack as soon as I have the Windows side of things working.

**Comment by atifaziz** [comment]
According to nunit/dotnet-test-nunit#108, [dotnet-test-nunit](https://www.nuget.org/packages/dotnet-test-nunit/) won't work with .NET Core Tools 1.0 anymore. Meanwhile, [NUnitLite](https://www.nuget.org/packages/NUnitLite/) could serve as a [workaround](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/).

**Comment by atifaziz** [comment]
Closed by e11a96ea3ebe8454421fb508da3b20da3c9b3c83
