### ISSUE TITLE
AllEquals function

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#266]
Sometimes I found myself checking if all elements of an enumerable (or some projection) are equals. 
Searching, found that it is a common issue (see [1](http://stackoverflow.com/questions/4390406/using-linq-or-otherwise-how-do-check-if-all-list-items-have-the-same-value-and), [2](http://stackoverflow.com/questions/5307172/check-if-all-items-are-the-same-in-a-list), [3](http://stackoverflow.com/questions/5478681/using-linq-can-i-verify-a-property-has-the-same-value-for-all-objects), [4](http://stackoverflow.com/questions/6681351/c-sharp-check-if-all-strings-in-list-are-the-same), [5](http://stackoverflow.com/questions/13336343/check-if-all-values-are-equal-in-a-list), [6](http://stackoverflow.com/questions/23339584/how-to-check-if-all-values-in-an-array-are-equal), [7](http://stackoverflow.com/questions/4354902/check-that-all-items-of-ienumerablet-has-the-same-value-using-linq))

of course we can do 
`source.CountBy(x => x.foo).Count() == 1` 
or 
`source.GroupBy(x => x.foo).Count() == 1` 
or even 
```
var first = source.First().foo;  // throws an exception on an empty sequence
source.All(o => o.foo == first);
```

but of cource none of these solutions are optimal.

My propose is to add the following methods:

- static bool AllEquals<TSource>(this IEnumerable<TSource> source)
- static bool AllEquals<TSource>(this IEnumerable<TSource> source, IEqualityComparer<TSource> comparer)
- static bool AllEqualsBy<TSource, Tkey>(this IEnumerable<TSource> source, Func<TSource, Tkey> keySelector)
- static bool AllEqualsBy<TSource, Tkey>(this IEnumerable<TSource> source, Func<TSource, Tkey> keySelector, IEqualityComparer<Tkey> comparer)

some examples of usage:

```
Assert.IsTrue(new[] { 3 }.Repeat(100).AllEquals())

text.AllEqualsBy(x => char.ToLower(x))

students.AllEqualsBy(x => x.Age)

lists.AllEqualsBy(x => x.Count)
```

Here is my draft:

```
public static bool AllEquals<TSource>(this IEnumerable<TSource> source)
{
	return source.AllEquals(null);
}

public static bool AllEquals<TSource>(this IEnumerable<TSource> source, IEqualityComparer<TSource> comparer)
{
	return AllEqualsImpl(source, x => x, comparer);
}

public static bool AllEqualsBy<TSource, Tkey>(this IEnumerable<TSource> source, Func<TSource, Tkey> keySelector)
{
	return source.AllEqualsBy(keySelector, null);
}

public static bool AllEqualsBy<TSource, Tkey>(this IEnumerable<TSource> source, Func<TSource, Tkey> keySelector, IEqualityComparer<Tkey> comparer)
{
	if (keySelector == null) throw new ArgumentNullException(nameof(keySelector));
	
	return AllEqualsImpl(source, keySelector, comparer);
}

private static bool AllEqualsImpl<TSource, Tkey>(IEnumerable<TSource> source, Func<TSource, Tkey> keySelector, IEqualityComparer<Tkey> comparer)
{
	if (source == null) throw new ArgumentNullException(nameof(source));

	comparer = comparer ?? EqualityComparer<Tkey>.Default;

	using (var e = source.GetEnumerator())
	{
		if (!e.MoveNext())
		{
			return true;
		}
		else
		{
			var first = keySelector(e.Current);
			var firstHash = comparer.GetHashCode(first);

			while (e.MoveNext())
			{
				var current = keySelector(e.Current);

				if (comparer.GetHashCode(current) != firstHash || !comparer.Equals(current, first))
				{
					return false;
				}
			}

			return true;
		}
	}
}

```

**Comment by leandromoh** [comment]
immediately after I open the issue, I realized that my current draft is equivalent to the following code. 
So consider this issue closed, please.

`source.DistinctBy(x => x.foo).AtMost(1);`

**Comment by fsateler** [comment]
Agreed. This is easily done by composing existing functions, so there is no need to add new methods. I'm thus closing.
