### ISSUE TITLE
AggregateWhile & AggregateUntil functions

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#267]
Like Aggregate, AggregateWhile returns a single item by iterating through the list, successively calling the iterator function. AggregateWhile also takes a predicate that is evaluated before each step. If the predicate returns false, it "short-circuits" the iteration and returns the current value of the accumulator. 
For symmetry, I also propose `AggregateUntil`.

Signatures:

- `static TAccumulate AggregateWhile<TSource>(this IEnumerable<TSource> source, Func<TSource, TSource, bool> predicate, Func<TSource, TSource, TSource> func)`
- `static TAccumulate AggregateWhile<TSource, TAccumulate>(this IEnumerable<TSource> source, TAccumulate seed, Func<TAccumulate, TSource, bool> predicate, Func<TAccumulate, TSource, TAccumulate> func)`

These signature pattern also apply for `AggregateUntil `.

Examples of usage:

```

int sumWhileLesser = numbers.AggregateWhile(0, (acc, x) => acc % x == 0, (acc, x) => acc + x)

int sumOfAges = students.AggregateUntil(0, (acc, s) => s.Name == "Bob" && s.Age < acc, (acc, s) => acc + s.Age);

string summary = texts.AggregateWhile((acc, _) => acc.Length <= 1000, (acc, x) => acc + x);

bool sumGreaterThan1000 = numbers.AggregateUntil(0, (acc, _) => acc > 1000, (acc, x) => acc + x) > 1000;

```

I would like to submit a PR for this.

What do you think?

**Comment by atifaziz** [comment]
You can combine [`Scan`][Scan] with [`TakeWhile`][TakeWhile] or [`TakeUntil`][TakeUntil] and then [`Last`][Last] to get the same effect, e.g.:

```c#
"the quick brown fox jumps over the lazy dog"
    .Split()
    .Scan((Length: 0, Word: default(string)), (s, w) => (s.Length + w.Length, w))
    .Skip(1)
    .TakeUntil(e => e.Word == "over")
    .Last().Length
```

and where the condition doesn't depend on an element:

```c#
Enumerable.Range(1, 1000)
          .Scan((s, x) => s + x)
          .TakeUntil(s => s > 1000)
          .Last()
```


[Scan]: https://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_Scan.htm
[TakeWhile]: https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.takewhile--1
[TakeUntil]: https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_TakeUntil__1.htm
[Last]: https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.last--1

**Comment by leandromoh** [comment]
Your approach doesnt work always...

As you said:

- If the criteria to stop is in source list, then we can combine`TakeWhile`/`TakeUntil `with `Aggregate`.
- If the criteria to stop is the result of the `Aggregate`, then we can combine `Scan` with `Aggregate`.

But if the criteria to stop use the result of the `Aggregate` as well the source list, there is no alternative.

Example:

```
var students = new[]
{
    new { Name = "alice", Age = 10 },
    new { Name = "bob", Age = 40 },
    new { Name = "carlos", Age = 30 },
    new { Name = "bob", Age = 20 },
    new { Name = "dario", Age = 50 },
};

var result = students.AggregateUntil(0, (acc, s) => s.Name == "bob" && acc > 60,
                                        (acc, s) => acc + s.Age);

Console.WriteLine(result); // 100
```

**Comment by atifaziz** [comment]
Your example can be written in terms of `Scan` & `TakeUntil`:

```c#
var result =
    students.Scan(new { Name = default(string), Age = 0 },
                  (acc, s) => new { s.Name, Age = acc.Age + s.Age })
            .TakeUntil(s => s.Name == "bob" && s.Age > 60)
            .Last().Age;
```

With C# 7 tuples, you can even avoid the cost of the intermediate anonymous objects:

```c#
var result =
    students.Scan((Name: default(string), Age: 0),
                  (acc, s) => (s.Name, acc.Age + s.Age))
            .TakeUntil(s => s.Name == "bob" && s.Age > 60)
            .Last().Age;
```

**Comment by leandromoh** [comment]
@atifaziz you are right! For some reason I forgot about to use anonymous object as intermediary to produce the expected result. 

Of course `Scan + TakeWhile + Last` combination is not the best code (otherwise, why would exists `Aggregate` if we can replace it by `Scan + Last` ?), but is solves the problem.
