### ISSUE TITLE
Help to Build MoreLinq and run it's tests from terminal/VS Code

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#279]
the picture shows my current situation. Can anyone help me?

![sem titulo](https://cloud.githubusercontent.com/assets/11452028/25537920/ee61217c-2c16-11e7-86b9-b2b7088b8a73.png)

**Comment by fsateler** [comment]
Dotnet test is [currently not working](https://github.com/morelinq/MoreLINQ/commit/e11a96ea3ebe8454421fb508da3b20da3c9b3c83), so you need to invoke the tests manually, like [test.cmd](https://github.com/morelinq/MoreLINQ/blob/master/test.cmd#L19-L22)

**Comment by atifaziz** [comment]
You need to run [`build.cmd`](https://github.com/morelinq/MoreLINQ/tree/v2.4.0-beta-2) to build or [`test.cmd`](https://github.com/morelinq/MoreLINQ/blob/v2.4.0-beta-2/test.cmd) to build _and_ test. The scripts are setup to target multiple frameworks, which are not all supported by the final .NET Core SDK tooling. To do so, you need the [MSBuild that comes with VS 2017](https://github.com/morelinq/MoreLINQ/blob/v2.4.0-beta-2/msbuild.cmd#L29-L34) (and which can be installed separately without VS) or [Mono 4.8](https://github.com/morelinq/MoreLINQ/blob/v2.4.0-beta-2/msbuild.sh#L4-L8).

If you want to build with just the `dotnet` CLI then I believe you can do so by just targeting the supported framework specifically, which would be `netstandard1.0` for `MoreLinq.dll` and `netcoreapp1.0` for `MoreLinq.Test.dll`.

Try the following in a Windows Command Prompt or Bash shell:

```
dotnet restore && dotnet build MoreLinq.Test/MoreLinq.Test.csproj -f netcoreapp1.0 && dotnet exec MoreLinq.Test/bin/Debug/netcoreapp1.0/MoreLinq.Test.dll
```

Building the test project will also build the MoreLINQ library. The above will only run tests in the debug configuration. You should also run then in release configuration before committing.

**Comment by atifaziz** [comment]
@leandromoh Can we close this?

**Comment by leandromoh** [comment]
@atifaziz I think yes. Thanks.
