### ISSUE TITLE
Version 2.4 and .NET 4.7

### ISSUE THREAD

**Issue by Hanno11** [morelinq/MoreLINQ#280]
The version 2.4 don't work with my project, based on .NET 4.7 + C# 7.0,  version 2.3 does.
The problems are releated to the now integrated tuples in .NET 4.7
Greetings
Hanno

**Comment by atifaziz** [comment]
When you say it doesn't work, can you share more details, like the compilation errors you're getting?

**Comment by Hanno11** [comment]
Hi, here a little more information
It happens in a function with multiple return values. Till .NET 4.7 you needed to include the tuple lib. In my .NET 4.7 I don't need it anymore.
Here the code
      private async Task<(bool ret, bool excludeOutDated)>
         ReadRealStatus(Request request, Status status, List<EPGEvent> epgEventsUI)
      {
         var result = await UdpSocketDriver.QueryAwait(Commands.GetCurrent);
         var currentServiceInformation = XmlConverter.ExtractData<CurrentServiceInformation>(result);
         if (currentServiceInformation == null)
         {
            await SendBack(request);
            return (false, true);
         }
         ReadMuteVolume(currentServiceInformation, status);
         var excludeOutDated = !string.IsNullOrEmpty(currentServiceInformation.ActualChannel.ProviderName);
         epgEventsUI.Clear();
         if (currentServiceInformation.MediaEvents != null)
            epgEventsUI.AddRange(UtilitiesDb.ConvertEpgEventDbs2EpgEvents(currentServiceInformation.MediaEvents.AllEvents,
               excludeOutDated));
         return (true, excludeOutDated);
      }

And the call of the function, line 81:
            var ret = await ReadRealStatus(request, status, epgEventsUI);

Here with the colored errors:
![image](https://cloud.githubusercontent.com/assets/5377745/25582134/dc27ef96-2e8b-11e7-8a83-f91d939b601f.png)


Error messages from visual
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8137	Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	111	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	111	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	81	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	81	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	81	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	81	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	81	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	119	Active
Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported	DreamboxDriver	C:\work\JRiver\SmartHome\DreamboxDriver\CommandQueues\DeviceStatus.cs	127	Active

Any more question? Feel free to ask
Greetings
Hannno

**Comment by atifaziz** [comment]
Thanks, @Hanno11. I'm afraid since there's no independent download available for .NET 4.7 currently besides having a Windows 10 machine with Creator Update, it's very hard to reproduce this issue. Your help in digging to the bottom of the issue would be much appreciated. The code you have shared has nothing to do with MoreLINQ, but if I understand correctly, upgrading MoreLINQ to 2.4.0 causes those seemingly unrelated errors in your project. I have a feeling this has less to do with MoreLINQ and more with one of the following:

> - EE issue (dotnet/corefx#16195, VSO)
> - Scripting issue (dotnet/roslyn#17157)
> - Compiler workaround (dotnet/roslyn#17192)
>
> &mdash; <cite>[[Umbrella] ValueTuple library work](https://github.com/dotnet/roslyn/issues/13177)</cite>

**Comment by Hanno11** [comment]
Hi,
correct, in this code moreLINQ is not used. The trouble comes surely not directly from moreLINQ, but from the collision of the tuple libs. Perhaps all will be solved, when the creator update is available everywhere

**Comment by aienabled** [comment]
.NET 4.7 is available now for Windows 7 SP1 and newer Windows versions.
https://blogs.msdn.microsoft.com/dotnet/2017/05/02/announcing-the-net-framework-4-7-general-availability/

**Comment by willson556** [comment]
The solution to this will be to remove `System.ValueTuple` as a dependency when targeting 4.7. Until then, MoreLINQ is incompatible with 4.7. This should be reopened and the package reference somehow removed in the 4.7 version.

**Comment by atifaziz** [comment]
@willson556 This should really be solved by the [System.ValueTuple](https://www.nuget.org/packages/System.ValueTuple/) package instead of every dependent having to do it. The issue I see with adding the 4.7 target to MoreLINQ is that anyone wanting to build and contribute to the project will also need to have 4.7 installed, which is setting the bar pretty high for what seems to be an artificial requirement.

**Comment by ljani** [comment]
The solution seems to be installing [`System.ValueTuple` version **4.4.0**](https://www.nuget.org/packages/System.ValueTuple/4.4.0) instead of the declared [4.3.0 version](https://www.nuget.org/packages/System.ValueTuple/4.3.0) of the dependency. I don't know if [4.3.1](https://www.nuget.org/packages/System.ValueTuple/4.3.1) fixes this.

4.4.0 was released along with .NET Core 2.0 13 days ago.

Also NuGet default to installing the lowest available version of dependencies unless explicitly specified in `.csproj`, so you'll end up with 4.3.0 as morelinq declares it as the minimum requirement.

**Comment by atifaziz** [comment]
> The solution seems to be explicitly installing [`System.ValueTuple` version **4.4.0**](https://www.nuget.org/packages/System.ValueTuple/4.4.0)

Looks like they've addressed the issue in System.ValueTuple 4.4.0 as I see the assembly for 4.7 having types forwarded to `mscorlib` (that should do the unification):

```
.class extern forwarder System.Runtime.CompilerServices.TupleElementNamesAttribute
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.TupleExtensions
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`1
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`2
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`3
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`4
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`5
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`6
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`7
{
    .assembly extern 'mscorlib'
}

.class extern forwarder System.ValueTuple`8
{
    .assembly extern 'mscorlib'
}
```

@ljani Thanks for bringing this to my attention; I'm re-opening this issue.

> I don't know if [4.3.1](https://www.nuget.org/packages/System.ValueTuple/4.3.1) fixes this.

I'm afraid it doesn't.

**Comment by atifaziz** [comment]
The [`morelinq.2.7.0-ci-20170823T1226.nupkg`](https://ci.appveyor.com/api/buildjobs/jsa24bv30sojx06v/artifacts/dist%2Fmorelinq.2.7.0-ci-20170823T1226.nupkg) package should reference [`System.ValueTuple` 4.4.0](https://www.nuget.org/packages/System.ValueTuple/4.4.0). As I don't have .NET 4.7, I would appreciate that those who do could, take the package for a spin and give feedback if it resolves this issue or not. Thanks!

**Comment by atifaziz** [comment]
[`morelinq.2.7.0-ci-20170823T1226.nupkg`](https://ci.appveyor.com/api/buildjobs/jsa24bv30sojx06v/artifacts/dist%2Fmorelinq.2.7.0-ci-20170823T1226.nupkg) is now also published as [MoreLinq 2.7 beta 1 on nuget.org](https://www.nuget.org/packages/morelinq/2.7.0-beta-1). Again, testing and feedback against .NET 4.7 and write respect to this issue would be appreciated.

**Comment by ljani** [comment]
> [MoreLinq 2.7 beta 1 on nuget.org](https://www.nuget.org/packages/morelinq/2.7.0-beta-1).

Working fine here.

For some reason it'll fail the very first rebuild after changing `2.6.0` to `2.7.0-beta-1` (or vice versa, but it succeeds in that case), but the second rebuild will pass without any problems, but it's MSBuild's problem and I've seen similar behavior with other packages as well.

**Comment by atifaziz** [comment]
@ljani Thanks for testing and confirming that it works. 👍 

> For some reason it'll fail the very first rebuild after changing `2.6.0` to `2.7.0-beta-1`

Perhaps missing a  `dotnet restore` just after upgrading?

**Comment by ljani** [comment]
> Perhaps missing a [dotnet restore] just after upgrading?

Yeah, might be, though 2.0 stated that [dotnet restore is now an implicit command](https://github.com/dotnet/announcements/issues/23).
