### ISSUE TITLE
Scan exception doc wrong for when source is empty

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#285]
[This](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Scan.cs#L55) Scan overload must throw an `InvalidOperationException` if `source` is empty (and its documentation say it does). However it just return an [empty sequence](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Scan.cs#L67)

**Comment by atifaziz** [comment]
The behaviour is correct and was fixed in #97. The [documentation needs fixing](https://github.com/morelinq/MoreLINQ/blob/v2.4.1/MoreLinq/Scan.cs#L53).
