### ISSUE TITLE
Document that Subsets() = “power set” & Subsets(k) = “combinations”

### ISSUE THREAD

**Issue by PawJershauge** [morelinq/MoreLINQ#288]
Wouldn't the correct naming for the method **[Subsets](http://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Subsets__1_1.htm)** be **Combinations**, as it implements the [Combination](https://en.wikipedia.org/wiki/Combination) algorithm nCr  and not the mathematical term [Subset](https://en.wikipedia.org/wiki/Subset) ???

**Comment by atifaziz** [comment]
So you're just talking about renaming the [second `Subsets` overload that accepts a size argument](http://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Subsets__1_1.htm) (since combinations are subsets of a particular size)?

**Comment by PawJershauge** [comment]
I would call em both Combinations as they lead to ever known combination at a specific size of combination or variable size of combinations. right ?

**Comment by PawJershauge** [comment]
My good friend and co-developer Mikael Birk Slej came up with the following code:

`        /// foreach (var list in Enumerable.Range(1, 4).ToList().Combinations())
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 
        /// 1
        /// 1, 2
        /// 1, 2, 3
        /// 1, 2, 3, 4
        /// 1, 2, 4
        /// 1, 3
        /// 1, 3, 4
        /// 1, 4
        /// 2
        /// 2, 3
        /// 2, 3, 4
        /// 2, 4
        /// 3
        /// 3, 4
        /// 4
        /// ------------------------
        /// */
        /// 
        /// foreach (var list in Enumerable.Range(1, 4).ToList().Combinations(2))
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 1, 2
        /// 1, 3
        /// 1, 4
        /// 2, 3
        /// 2, 4
        /// 3, 4
        /// ------------------------
        /// */
        /// 
        /// <summary>
        /// Returns all posible combination of items from the collection either with fixed or variable combination length.
        /// </summary>
        /// <typeparam name="T">type of element in the collection</typeparam>
        /// <param name="collection">collection to choose from</param>
        /// <param name="count">if -1 all posible combinations will be returned; else its the fixed length of items in the outcome.</param>
        /// <returns>a list of combinations</returns>
        /// <example>
        /// foreach (var list in Enumerable.Range(1, 4).ToList().Combinations())
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 
        /// 1
        /// 1, 2
        /// 1, 2, 3
        /// 1, 2, 3, 4
        /// 1, 2, 4
        /// 1, 3
        /// 1, 3, 4
        /// 1, 4
        /// 2
        /// 2, 3
        /// 2, 3, 4
        /// 2, 4
        /// 3
        /// 3, 4
        /// 4
        /// ------------------------
        /// */
        /// 
        /// foreach (var list in Enumerable.Range(1, 4).ToList().Combinations(2))
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 1, 2
        /// 1, 3
        /// 1, 4
        /// 2, 3
        /// 2, 4
        /// 3, 4
        /// ------------------------
        /// */
        /// </example>
        public static List<List<T>> Combinations<T>(this List<T> collection, int combinationLength = -1)
        {
            List<List<T>> combinations = new List<List<T>>();
            CombinationsImpl(combinations, collection, new List<T>(), combinationLength);
            return combinations;
        }
        private static void CombinationsImpl<T>(List<List<T>> combinations, List<T> collection, List<T> currentcombination, int combinationLength)
        {
            if (combinationLength == -1 || currentcombination.Count == combinationLength)
                combinations.Add(currentcombination);

            foreach (var item in collection)
            {
                List<T> nextCombination = new List<T>(currentcombination);
                nextCombination.Add(item);
                collection = collection.GetRange(collection.IndexOf(item) + 1, collection.Count - 1);
                CombinationsImpl(combinations, collection, nextCombination, combinationLength);
            }
        }


        /// <summary>
        /// Returns all posible permutations of items from the collection either with fixed or variable permutation length.
        /// </summary>
        /// <typeparam name="T">type of element in the collection</typeparam>
        /// <param name="collection">collection to choose from</param>
        /// <param name="count">if -1 all posible permutation will be returned; else its the fixed length of items in the outcome.</param>
        /// <returns>a list of combinations</returns>
        /// <example>
        /// foreach (var list in Enumerable.Range(1, 4).ToList().Permutation())
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 
        /// 1
        /// 1, 2
        /// 1, 2, 3
        /// 1, 2, 3, 4
        /// 1, 2, 4
        /// 1, 2, 4, 3
        /// 1, 3
        /// 1, 3, 2
        /// 1, 3, 2, 4
        /// 1, 3, 4
        /// 1, 3, 4, 2
        /// 1, 4
        /// 1, 4, 2
        /// 1, 4, 2, 3
        /// 1, 4, 3
        /// 1, 4, 3, 2
        /// 2
        /// 2, 1
        /// 2, 1, 3
        /// 2, 1, 3, 4
        /// 2, 1, 4
        /// 2, 1, 4, 3
        /// 2, 3
        /// 2, 3, 1
        /// 2, 3, 1, 4
        /// 2, 3, 4
        /// 2, 3, 4, 1
        /// 2, 4
        /// 2, 4, 1
        /// 2, 4, 1, 3
        /// 2, 4, 3
        /// 2, 4, 3, 1
        /// 3
        /// 3, 1
        /// 3, 1, 2
        /// 3, 1, 2, 4
        /// 3, 1, 4
        /// 3, 1, 4, 2
        /// 3, 2
        /// 3, 2, 1
        /// 3, 2, 1, 4
        /// 3, 2, 4
        /// 3, 2, 4, 1
        /// 3, 4
        /// 3, 4, 1
        /// 3, 4, 1, 2
        /// 3, 4, 2
        /// 3, 4, 2, 1
        /// 4
        /// 4, 1
        /// 4, 1, 2
        /// 4, 1, 2, 3
        /// 4, 1, 3
        /// 4, 1, 3, 2
        /// 4, 2
        /// 4, 2, 1
        /// 4, 2, 1, 3
        /// 4, 2, 3
        /// 4, 2, 3, 1
        /// 4, 3
        /// 4, 3, 1
        /// 4, 3, 1, 2
        /// 4, 3, 2
        /// 4, 3, 2, 1
        /// ------------------------
        /// */
        /// 
        /// foreach (var list in Enumerable.Range(1, 4).ToList().Permutation(2))
        /// 	Debug.WriteLine(string.Join(", ", list));
        /// /*
        /// Result:
        /// ------------------------
        /// 1, 2
        /// 1, 3
        /// 1, 4
        /// 2, 1
        /// 2, 3
        /// 2, 4
        /// 3, 1
        /// 3, 2
        /// 3, 4
        /// 4, 1
        /// 4, 2
        /// 4, 3
        /// ------------------------
        /// */
        /// </example>
        public static List<List<T>> Permutation<T>(this List<T> collection, int permutationLength = -1)
        {
            List<List<T>> permutations = new List<List<T>>();
            PermutationImpl(permutations, collection, new List<T>(), permutationLength);
            return permutations;
        }
        private static void PermutationImpl<T>(List<List<T>> permutations, List<T> collection, List<T> currentpermutation, int permutationLength)
        {
            if (permutationLength == -1 || currentpermutation.Count == permutationLength)
                permutations.Add(currentpermutation);

            foreach (var item in collection)
            {
                List<T> nextPermutation = new List<T>(currentpermutation);
                nextPermutation.Add(item);
                List<T> remPermutation = new List<T>(collection);
                remPermutation.Remove(item);
                PermutationImpl(permutations, remPermutation, nextPermutation, permutationLength);
            }
        }
`
Use it if you want ;)

**Comment by atifaziz** [comment]
> I would call em both Combinations as they lead to ever known combination at a specific size of combination or variable size of combinations. right ?

If we get into strict mathematical definitions here then perhaps [the first `Subsets` overload](https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Subsets__1.htm) should be called [`Powerset`](https://en.wikipedia.org/wiki/Power_set). Also, since combinations are also referred to as k-subsets, I don't think the `Subsets` overload taking _k_ (`subsetSize`) is particularly wrong or misleading. Perhaps what can help is to make the link to those mathematical terms in the _doc summaries_ so that if someone with a mathematical background is searching through the documentation for those particular keywords has a good chance of finding and relating to the `Subsets` overloads. Seems to me what needs improving is that [searching for “combinations”](https://www.google.co.uk/search?q=subsets+site%3Amorelinq.github.io) shouldn't yield nothing.

> My good friend and co-developer [Mikael Birk Slej](https://dk.linkedin.com/in/mikael-birk-slej-6a78762b) came up with the following code:
> Use it if you want ;)

Thanks for sharing but MoreLINQ already has the implementation for both. I'd be happy to reconsider them if your colleague is keen to prove that his implementation is superior in performance and correctness.

**Comment by PawJershauge** [comment]
You could put it into the doc, that would probably help a lot, yes.

> Thanks for sharing but MoreLINQ already has the implementation for both. I'd be happy to reconsider them if your colleague is keen to prove that his implementation is superior in performance and correctness.

I did not add the code to say that the implementation was wrong, but the code footprint is smaller, its marley there as an suggestion.
Performance-wize i havn't testet.
