### ISSUE TITLE
Create an enumerable given an enumerator factory

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#291]
`Create` will return an `IEnumerable<>` given a function that creates an `IEnumerator<>`. Since this is essentially the same signature as for [`IEnumerable<>`'s only method `GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1.getenumerator), it enables getting a boilerplate streaming `IEnumerable<>` implementation whenever you have function returning an `IEnumerator<>`, but really needed an `IEnumerable<>`. For example, suppose you have an extension method like this:

```c#
static class Extensions
{
    public static IEnumerator<string> ReadLines(this TextReader reader)
    {
        using (reader)
        for (var line = reader.ReadLine(); line != null; line = reader.ReadLine())
            yield return line;
    }
}
```

`Create` would enable using the above function in a query:

```c#
var q =
    from fp in Directory.EnumerateFiles(Environment.GetEnvironmentVariable("windir"), "*.ini")
    select new
    {
        Path  = fp,
        Content =
            from line in MoreEnumerable.Create(() => File.OpenText(fp).ReadLines())
            select line.TrimStart() into line
            where line.Length > 0 && line[0] != ';' // skip blanks + comments
            select line
    };
```

It would also enable writing in-line, ad-hoc and anonymous iterators using [local functions (introduced with C# 7)](https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/csharp-7#local-functions), as shown here to conduct multiple aggregations in a single pass without materialization:

```c#
var summary =
    from x in Enumerable.Range(1, 20)
    group x by x % 5 == 0 into g
    select new
    {
        MultiplesOf5 = g.Key,
        Run =
            from x in MoreEnumerable.Create(() =>
            {
                return _(); IEnumerator<(int Num, int Min, int Max, int Count, int Sum)> _()
                {
                    var min = int.MaxValue;
                    var max = int.MinValue;
                    var sum = 0;
                    var count = 0;
                    using (var e = g.GetEnumerator())
                    while (e.MoveNext())
                    {
                        var x = e.Current;
                        if (x < min) min = e.Current;
                        if (x > max) max = e.Current;
                        sum += e.Current;
                        yield return (x, min, max, ++count, sum);
                    }
                }
            })
            select new
            {
                x.Num, x.Min, x.Max, x.Count, x.Sum,
                Average = (double) x.Sum / x.Count
            }
    };
```

The result will be two groups where the first group will have a key of `false` (numbers not divisible by 5) and the following sequence as its run:

| Num | Min | Max | Count | Sum |   Average   | 
|----:|----:|----:|------:|----:|------------:| 
|   1 |   1 |   1 |     1 |   1 |           1 | 
|   2 |   1 |   2 |     2 |   3 |         1.5 | 
|   3 |   1 |   3 |     3 |   6 |           2 | 
|   4 |   1 |   4 |     4 |  10 |         2.5 | 
|   6 |   1 |   6 |     5 |  16 |         3.2 | 
|   7 |   1 |   7 |     6 |  23 | 3.833333333 | 
|   8 |   1 |   8 |     7 |  31 | 4.428571429 | 
|   9 |   1 |   9 |     8 |  40 |           5 | 
|  11 |   1 |  11 |     9 |  51 | 5.666666667 | 
|  12 |   1 |  12 |    10 |  63 |         6.3 | 
|  13 |   1 |  13 |    11 |  76 | 6.909090909 | 
|  14 |   1 |  14 |    12 |  90 |         7.5 | 
|  16 |   1 |  16 |    13 | 106 | 8.153846154 | 
|  17 |   1 |  17 |    14 | 123 | 8.785714286 | 
|  18 |   1 |  18 |    15 | 141 |         9.4 | 
|  19 |   1 |  19 |    16 | 160 |          10 | 

The second group will have a key of `true` (numbers divisible by 5) and the following sequence as its run:

| Num | Min | Max | Count | Sum | Average | 
|----:|----:|----:|------:|----:|--------:| 
|   5 |   5 |  5  |     1 |   5 |       5 | 
|  10 |   5 | 10  |     2 |  15 |     7.5 | 
|  15 |   5 | 15  |     3 |  30 |      10 | 
|  20 |   5 | 20  |     4 |  50 |    12.5 |

**Comment by fsateler** [comment]
> `Create` will return an `IEnumerable<>` given a function that creates an `IEnumerator<>`

How common are such functions? Your example looks a bit artificial, since you could have just as well returned an `IEnumerable<>`. I'm not seeing the use case, could you please elaborate on this?

**Comment by fsateler** [comment]
Upon further thought, I can see that an interesting feature is not necessarily the `IEnumerator<>` parameter type, but rather that it takes a function that generates it. Maybe it's better instead to have a `Lazy` operator or so, that takes a `Func<IEnumerable<T>>` and returns an `IEnumerable<T>` ? Or do you see this as something different?

**Comment by atifaziz** [comment]
>  Your example looks a bit artificial, since you could have just as well returned an `IEnumerable<>`

Which example? I'm guessing you're referring to the `ReadLines` example? If so, returning `IEnumerable<>` would be logically wrong or misleading because the sequence would not be repeatable or for one-time consumption. If that's the case then `IEnumerator<>` is the more correct return type. It tells the caller they're getting a cursor to scroll over data and that cursor is already open. That's the case with `ReadLines`. It doesn't care whether the `TextReader` is sitting on top of a stream representing a file or a socket. It simply consumes the stream in terms of character data and returns lines.

> How common are such functions?

Well, everyone's mileage will vary but I have had my plenty share.

**Comment by fsateler** [comment]
> Which example? I'm guessing you're referring to the ReadLines example?

Yes, sorry for not mentioning that.

> If so, returning IEnumerable<> would be logically wrong or misleading because the sequence would not be repeatable or for one-time consumption.

Hmm. I've never assumed that `IEnumerable<>` is inherently repeatable. All it means is that you can iterate over a strongly typed collection. As with all objects, an `IEnumerable<>` may be in an invalid state, and then it is not possible to enumerate it anymore.

>> How common are such functions?
>
>Well, everyone's mileage will vary but I have had my plenty share.

Well, I assumed you have seen a few, otherwise you wouldn't be proposing this feature 😄 .
But I don't see many functions returning an `IEnumerator<T>` in any of the APIs I use frequently, so that is why I asked how common these functions are. If you have any publicly available examples I'd appreciate pointers.

**Comment by atifaziz** [comment]
>  I've never assumed that `IEnumerable<>` is inherently repeatable.

Let's put repeat-ability aside for a moment. If you are modeling a database cursor as a class, would you make the class implement `IEnumerable<>` or `IEnumerator<>`? I hope you agree that the latter is the right call. If you were modelling a SQL database query as a class, you'd make it implement `IEnumerable<>`. Its `GetEnumerator` will issue the query to the database and return an `IEnumerator<>` as cursor over the results. The query can then be executed again and again and each time you'll receive a distinct cursor over the results. Likewise, choosing to return `IEnumerable<>` or `IEnumerator<>` from a function shouldn't be an arbitrary decision because the type should convey the right abstraction. If a function takes a file path then it can return `IEnumerable<>`. When iterated, it will open the file and return a cursor over the content and you can do that again and again. On the other hand, if a function takes a stream it _should_ return `IEnumerator<>`.

**Comment by fsateler** [comment]
> If you are modeling a database cursor as a class, would you make the class implement `IEnumerable<>` or `IEnumerator<>`?

It appears mileage does indeed vary 😉 . I have never had to model a database cursor. But now I see that there are use cases where `IEnumerator<>` might be the right abstraction. Given that, a method that wraps the `IEnumerator<>` for easy usage would indeed be useful. I'll share comments on the PR.

**Comment by atifaziz** [comment]
@fsateler Actually, a bigger motivation was the second example, enabling one to write in-line, ad-hoc and anonymous iterators. Well, that's what they look like if you squint hard enough. :wink:

**Comment by atifaziz** [comment]
> But I don't see many functions returning an `IEnumerator<T>` in any of the APIs I use frequently, so that is why I asked how common these functions are.

You don't really confront them unless you are writing extension methods and since the .NET Framework doesn't offer many extension methods outside of LINQ, they're not common at all. So why mostly extension methods? Say you have an extension method that takes a `TextReader`, parses the text and returns `IEnumerator<T>` where `T` is some record. If that method didn't extend `TextReader` then you could change its signature to take a `TextReader` factory, a `Func<TextReader>`, and then return `IEnumerable<T>` instead. You're not forced to return `IEnumerator<T>`. With an extension method, you don't have that choice. Sure you can extend `Func<TextReader>` but that feels odd and not very discoverable from an API design perspective.

> If you have any publicly available examples I'd appreciate pointers.

If open source projects qualify as public examples, then here some from my projects: :wink:

- [See all methods extending `IDataReader` in Eggado](https://github.com/atifaziz/Eggado/blob/f3ee77a9f40b4d404a588b80b8d6dca9cf356037/src/DataReaderExtensions.cs)
- [See `ParseXsv` for `TextReader` in Mannex](https://bitbucket.org/raboof/mannex/src/eb3d025bb06a7a8ff42e640dd4fbf3746d77145f/src/IO/TextReader.cs?at=default&fileviewer=file-view-default#TextReader.cs-226:263)

**Comment by fsateler** [comment]
Is this still necessary if you have published [Delegating](https://github.com/atifaziz/Delegating)?

**Comment by atifaziz** [comment]
@fsateler Aye, no more.
