### ISSUE TITLE
Simple linear regression for two-dimensional sample data points

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#298]
Given a sample of two-dimensional (x, y) data points, the operator will calculate and return the following components of the a [simple linear regression](https://en.wikipedia.org/wiki/Simple_linear_regression):

- Slope (&beta; in **&alpha; + &beta;x** or _m_ in **y = mx + b**)
- Y-Intercept (&alpha; in **&alpha; + &beta;x** or _b_ in **y = mx + b**)
- Correlation coefficient

**Comment by atifaziz** [comment]
⚠️ The addition of this operator does risk expanding MoreLINQ's scope to the domain of statistics instead of just transformation of sequences, although one could argue that this is just an aggregation like `Average` (which I think was there in LINQ more in support of SQL database systems than anything else).

**Comment by fsateler** [comment]
> The addition of this operator does risk expanding MoreLINQ's scope to the domain of statistics instead of just transformation of sequences,

Indeed. I'm a bit worried about the scope expansion here. After this, it would be perfectly reasonable for MoreLINQ to have standard deviation, variance, N-level momentums and whatnot functions. I'm not sure we want all that.

> although one could argue that this is just an aggregation like Average (which I think was there in LINQ more in support of SQL database systems than anything else).

Well, any function that takes as input a data series or data set would fit this description 😉

**Comment by atifaziz** [comment]
> Well, any function that takes as input a data series or data set would fit this description 😉 

True but I was calling out `Average` specially as you could take the angle that it's a statistical function.

> After this, it would be perfectly reasonable for MoreLINQ to have standard deviation, variance, N-level momentums and whatnot functions.

Is this something that would ever make sense as an experiment, as discussed in #209? In other words, we'd not only be experimenting with the idea and implementation of the operator but also the scope.

>  I'm not sure we want all that.

I agree and I am going to close this out of the same concern. I might propose this to @dkackman for [LinqStatistics](https://www.nuget.org/packages/LinqStatistics/).

**Comment by dkackman** [comment]
Hi @atifaziz - LinqStatistics does include an implementation of Least Squares linear regression and Pearson correlation coeffcient.

**Comment by atifaziz** [comment]
@dkackman Ah, I was CTRL+F-ing over the [README](https://github.com/dkackman/LinqStatistics/blob/v2.1.0/README.md) for the word “regression” and jumped to the conclusion that you probably haven't just gotten round to it. Thanks for dropping by and breaking me out of my tunnel vision.

**Comment by dkackman** [comment]
@atifaziz  fixed :)
