### ISSUE TITLE
MoreLinq nuget package asks to install System.ValueTuple 4.3.0 on .Net Framework 4.7

### ISSUE THREAD

**Issue by Jivko1212** [morelinq/MoreLINQ#310]
System.ValueTuple is built into .Net 4.7 and it is strange that morelinq asks to install it. I would have no problem installing it but there is a weird bug with the Visual Studio debugger when using System.ValueTuple 4.3.0: adding tuples to watch doesn't work while debugging.

**Comment by Jivko1212** [comment]
I just made a test, adding the System.ValueTuple package to .Net 4.7 project makes tuples impossible to use .. there is a compile error. Hence I cannot use morelinq, because it requres ValueTuple which breaks tuples.

**Comment by atifaziz** [comment]
This is a duplicate of #280.
