### ISSUE TITLE
Move: move range of elements to a new offset

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#311]
It pick up a range of a sequence and put it at some other index. 
It's a combination of `Exclude + Slice + InsertAt`, but the input sequence is enumerated once.

Signature:
`static IEnumerable<T> SwapRange<T>(this IEnumerable<T> source, int index, int count, int putAt)`

A naive implementation (of this initial propose) would be

```
static IEnumerable<T> SwapRange<T>(this IEnumerable<T> source, int index, int count, int putAt)
{
    var slc = source.Slice(index, count);
    var exc = source.Exclude(index, count);

    return exc.InsertAt(slc, putAt);
}
```

Example:
`Enumerable.Range(0, 10).SwapRange(5, 2, 7) // [0, 1, 2, 3, 4, 7, 8, 5, 6, 9]`

Since the [InsertAt](https://github.com/morelinq/MoreLINQ/issues/306) function it is not complete defined yet, this propose is also not , so suggestions for the behaviour of the method is very welcome!

**Comment by leandromoh** [comment]
I was thinking, Since the objective of `SwapRange` is just to move a range within to another place, that is, **dont add new elements or remove (preserving source's length)**, only swap, i think make sense that 

`Enumerable.Range(0, 10).SwapRange(5, 2, 999)` returns `[0, 1, 2, 3, 4, 7, 8, 9 , 5, 6]`

I would like to submit a PR for this.
What do you think?

**Comment by atifaziz** [comment]
> I suggest submit a PR that throws, and latter if we think valid, turn it less strict (accpet negative index) with another PR.

Yes, let's start with the strict version and we can relax the rules in a later version.

**Comment by leandromoh** [comment]
Ok, I Will submit the PR
