### ISSUE TITLE
PadLeft function

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#312]
Only to provide symmetry with Pad function

**Comment by atifaziz** [comment]
Sure, go ahead. In addition to `PadLeft`, I would also consider the following names:

- `PadHead`
- `PrePad`

**Comment by atifaziz** [comment]
Please note that this method was renamed to [`PadStart`](https://morelinq.github.io/2.6/ref/api/html/Overload_MoreLinq_MoreEnumerable_PadStart.htm) at time of [2.6 release in which it shipped](https://github.com/morelinq/MoreLINQ/releases/tag/v2.6.0).
