### ISSUE TITLE
Limit iterations of a sequence

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#317]
I propose adding an operator that can be used to limit the maximum number of times a sequence can be iterated. Once the limit has been reached, all subsequent attempts to iterate will throw an `InvalidOperationException` or a custom exception. A limit of 0 or below will render the sequence unavailable for any iteration.

This primary use of this would be for ad-hoc testing & interactive development.

## Prototype

```c#
public static IEnumerable<T> LimitIterations<T>(this IEnumerable<T> source, int count) =>
    source.LimitIterations(count, (Func<int, Exception>) null);

public static IEnumerable<T> LimitIterations<T>(this IEnumerable<T> source, int count, Func<Exception> errorFactory) =>
    source.LimitIterations(count, _ => errorFactory());
    
public static IEnumerable<T> LimitIterations<T>(this IEnumerable<T> source, int count, Func<int, Exception> errorFactory)
{
    var remainder = count;
    return _(); IEnumerable<T> _()
    {
        if (remainder <= 0)
        {
            throw errorFactory?.Invoke(count)
               ?? new InvalidOperationException($"Sequence was iterated more than the allowed count of {count}.");
        }
        remainder--;
        foreach (var item in source)
            yield return item;
    };
}
```

Below is an alternate implementation of the last overload using [Delegating](https://www.nuget.org/packages/Delegating) (as we abandoned #291):

```c#
public static IEnumerable<T> LimitIterations<T>(this IEnumerable<T> source, int count, Func<int, Exception> errorFactory)
{
    var remainder = count;
    return Delegating.Delegate.Enumerable(() =>
    {
        if (remainder <= 0)
        {
            throw errorFactory?.Invoke(count)
               ?? new InvalidOperationException($"Sequence was iterated more than the allowed count of {count}.");
        }
        remainder--;
        return source.GetEnumerator();
    });
}
```

**Comment by fsateler** [comment]
> primary use of this would be for ad-hoc testing & interactive development

I'm a bit unsure about features whose main use case is testing. I'm not saying they aren't useful, but on actual application code they mostly pollute the namespace. Maybe we could split these to a separate namespace? What do you think?

**Comment by atifaziz** [comment]
@fsateler I'd generally agree with you but as C# is becoming more scriptable (well, it has been for a while if you take [LINQPad scripting](https://www.linqpad.net/lprun.aspx) into account), it is useful to have such an operator handy. Also, when I say, “primary use of this would be for ad-hoc testing & interactive development”, that's been my mileage. Either its utility is truly limited (pun, pun) to that or my imagination for other scenarios.

If you have an expensive source that you don't want to be iterated more than once, either by mistake because you forgot to materialize results or someone accidentally removed the materialization (removed a call to `ToArray` or `ToList`), then `LimitIterations(1)` can serve as a _run-time_ guard (e.g. in debug builds). When scripting (including for production), you might want throw in a call to `LimitIterations(1)` to make sure there's no multiple iteration of any expensive source, run & test and then comment out the call.

> Maybe we could split these to a separate namespace? 

What would you call such a namespace? `MoreLinq.Testing`? Perhaps `MoreLinq.Experimental` as discussed in #209? None of those really sound good. Also, if we ever get round to closing #214 then this operator won't be there unless explicitly imported, which would take care of the pollution problem.

My current thinking is that it's a straightforward operator with a straightforward purpose and a clean name so why not add it?

**Comment by fsateler** [comment]
> I'd generally agree with you but as C# is becoming more scriptable (well, it has been for a while if you take LINQPad scripting into account), it is useful to have such an operator handy.
<snip>
> My current thinking is that it's a straightforward operator with a straightforward purpose and a clean name so why not add it?

I agree it can be useful, which is why I'm not saying it shouldn't go in. I'm just wondering about namespace pollution.

> What would you call such a namespace? MoreLinq.Testing? Perhaps MoreLinq.Experimental as discussed in #209? None of those really sound good.

Indeed. I can't think of any good names either. `MoreLinq.Asserts` could be, given that the purpose of these functions is to assert that some condition holds.

> Also, if we ever get round to closing #214 then this operator won't be there unless explicitly imported, which would take care of the pollution problem.

Well, importing `MoreLinq` is always going to import all operators. So even if conflicts can be avoided by use of `using static` as proposed in #235, I would expect people to import everything most of the time ([as you did too](https://github.com/morelinq/MoreLINQ/issues/214#issuecomment-293796287)).

**Comment by atifaziz** [comment]
> I'm just wondering about namespace pollution.

It's hard to define pollution and it would be odd to start categorising now.

> `MoreLinq.Asserts` could be, given that the purpose of these functions is to assert that some condition holds.

We already have [`AssertCount`](https://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_AssertCount.htm) in the main namespace so it would seem odd now to make an exception for `LimitIterations`.

**Comment by atifaziz** [comment]
Closing this as a specific application of #516.
