### ISSUE TITLE
Max/MinBy should return all matching elements

### ISSUE THREAD

**Issue by orthoxerox** [morelinq/MoreLINQ#328]
The docs say that "If more than one element has the maximal projected value, the first one encountered will be returned." Is there a method that returns all of them?

If not, could it be added? If yes, I think there should be a reference to it in the docs.

**Comment by atifaziz** [comment]
I personally think that `MinBy` and `MaxBy` should themselves be changed to return a list. Since that would be a breaking change, it would have to be scheduled for [the next major release](https://github.com/morelinq/MoreLINQ/milestone/2).

**Comment by orthoxerox** [comment]
Why not add `SingleMaxBy` and `EveryMaxBy` in the next minor release and obsolete `MaxBy` in the next major?

**Comment by atifaziz** [comment]
@orthoxerox That would be a quick and simple fix but which would have be reverted anyhow when we could afford a breaking change. Perhaps it's getting time for a [major release that's been pending](https://github.com/morelinq/MoreLINQ/milestone/2).

**Comment by TormodS** [comment]
Why......? Why would you do this? 
If you have a collection of integers, let's say [1,2,3,3] and you invoke "Max" on it. Would you return 3 or a collection [3,3]?
I assume you would return only 3. Why on earth would you return a collection from MaxBy then?
As vanilla LINQ in .NET 7 now includes MaxBy, then you see that it is properly implemented there.

We had a legacy library that was using old MoreLinq nuget. When ported to .NET standard, the dev didn't pay attention when bumping to new MoreLinq version and just added a ToString() when using MaxBy in an edge case of course resulting in a bug that took a while to discover.

What interpretation of MaxBy() would warrant breaking the symmetry with Max(), which is the case for all the "-by" operators such as DisctinctBy, OrderBy, IntersectBy, UnionBy etc?

**Comment by viceroypenguin** [comment]
@TormodS If you update to v4.0.0, you'll find that the method has been renamed to `Minima`/`Maxima`, avoiding this discrepancy entirely.

**Comment by TormodS** [comment]
@viceroypenguin 
Right, I see that the MaxBy and MinBy have been deprecated (not reverted to their proper implementation) in version 4.0. 
I suppose that this means that I can use Minima().First() construct as a future proof workaround that wont break if (when?) the proper implementation of MaxBy and MinBy returns.

I agree that this change avoids the convention discrepancy, and I hope that mainstream functions such as MaxBy and MinBy will return in the next major version. 

I assume that Minima will always return at least one record if the input set is non-empty and the lambda isn't throwing, so I don't an mid-check for empty set.

Thank you.

**Comment by viceroypenguin** [comment]
`MinBy` and `MaxBy` are not likely to return, as they have already been implemented in the BCL. Yes, use `Minima().First()` as a future-proof workaround.

**Comment by atifaziz** [comment]
> Why......? Why would you do this?
> If you have a collection of integers, let's say [1,2,3,3] and you invoke "Max" on it. Would you return 3 or a collection [3,3]?
> I assume you would return only 3. Why on earth would you return a collection from MaxBy then?

Say you have students with their test scores:

```c#
var students = new[]
{
    new { Name = "Maybell Bechtelar" , Score = 7 },
    new { Name = "Gerhard Paucek"    , Score = 6 },
    new { Name = "Russell Walter"    , Score = 4 },
    new { Name = "Angel Waelchi"     , Score = 7 },
    new { Name = "Anais Rempel"      , Score = 5 },
    new { Name = "Moriah Donnelly"   , Score = 5 },
    new { Name = "Jonas Trantow"     , Score = 7 },
    new { Name = "Louie Runte"       , Score = 6 },
    new { Name = "Bettye Kohler"     , Score = 3 },
    new { Name = "Tyson Roberts"     , Score = 4 },
    new { Name = "Raphael Mitchell"  , Score = 7 },
    new { Name = "Jocelyn Abernathy" , Score = 3 },
    new { Name = "Katlynn Leffler"   , Score = 3 },
    new { Name = "Idell Haag"        , Score = 3 },
    new { Name = "Collin Turcotte"   , Score = 4 },
    new { Name = "Russell Willms"    , Score = 4 },
    new { Name = "Gabriella Lubowitz", Score = 7 },
    new { Name = "Austen Dibbert"    , Score = 7 },
    new { Name = "Hoyt Fay"          , Score = 6 },
    new { Name = "Oda Stamm"         , Score = 3 },
};
```

And you want to list the students who performed the worst, then you can use `Minima` without knowing the minimum score in advance:

```c#
foreach (var s in students.Minima(s => s.Score))
    Console.WriteLine(s.ToString());
```

This will print:

    { Name = Bettye Kohler, Score = 3 }
    { Name = Jocelyn Abernathy, Score = 3 }
    { Name = Katlynn Leffler, Score = 3 }
    { Name = Idell Haag, Score = 3 }
    { Name = Oda Stamm, Score = 3 }

In contrast, with `MinBy` in .NET, you just get the first student that scored the worst in the list:

```c#
Console.WriteLine(students.MinBy(s => s.Score).ToString());
```

which prints:

    { Name = Bettye Kohler, Score = 3 }

**Comment by TormodS** [comment]
I understand the use case. Just like Max() conceivably be complemented with a function to return a count of max instances in the passed collection. I, however,  don't understand how this replaced MaxBy, which both by LINQ convention (through the symmetry with Max) and category theory has a dictated purpose. I suspect this is the reason for the down votes on the rationale when it was initially voiced in this thread. 
I would understand the decision better if MaxBy didn't already exist. MaxBy and MinBy was part of the earliest obvious "holes" that Jon Skeet originally addressed with MoreLinq.

Since the .NET 7 BCL isn't available to my .NET Standard lib and it apparently isn't coming back to MoreLinq, I will just make a local implementation. As long as MoreLinq is a .NET Standard library, only a subset of the consumers risk an ambiguity between MoreLInq and BCL. But at least here I understand how both options have downsides.
