### ISSUE TITLE
DistinctBy + Take

### ISSUE THREAD

**Issue by ranouf** [morelinq/MoreLINQ#334]
Hi,

`query.Take(x).ToList()`

When I used DistinctBy in my query, i have a list with 1 value and 1 null.

When I remove the distinctby, i have a list with 2 values.

I would like to continue to user my distinctBy and get the list with 2 values.

Maybe already have this situation?
Cedric

**Comment by atifaziz** [comment]
@ranouf I'm afraid I'm having difficulty understanding what you're asking for here. Can you illustrate through an actual example with sample data?

**Comment by ranouf** [comment]
Hi,

I had to use ToAsyncEnumerable and it resolved the problem.

Thank you to have answered.
Cedric
