### ISSUE TITLE
MoreThan extension method

### ISSUE THREAD

**Issue by SeanFarrow** [morelinq/MoreLINQ#339]
Hi,

I would love to see a MoreThan extension method for the CountMethods class.

For example in a project I'm working on currently, I do a lot of count > 1 so would like to be able to use morelinq to do this. AtLeast won't work here as it includes the value passed in. Is there a current alternative, or should I look at forking/doing this for v3?

**Comment by atifaziz** [comment]
@SeanFarrow And `AtLeast(2)` doesn't cut it for you?

**Comment by SeanFarrow** [comment]
Hi,

Unfortuantely, no, I want ot exclude the number present, so I’d idealoly like to say MoreThan(1), simantec I guess.

**Comment by atifaziz** [comment]
@SeanFarrow In that case, I suggest you add a local helper that goes like this:

```c#
public static bool CountMoreThan<T>(this IEnumerable<T> source, int count) =>
    source.AtLeast(count + 1);
```

**Comment by SeanFarrow** [comment]
Ok, makes sense.
