### ISSUE TITLE
Conflicts with new Enumerable members in .NET Core .20

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#351]
It looks like that .NET Core 2.0 has introduced a number of new methods on [`Enumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=netcore-2.0) that could potentially conflict with those in MoreLINQ. The problem is that the unit tests may be testing the LINQ extension methods instead of those from MoreLINQ and could either be giving false positives (passing when they should be failing) or false negatives (failing when they should be passing). This happened with, for example, 5eb30a2d70fbfaa294f2c23cb07085f9cd670441 in #304 where a fix still had [a `TaskLast` test failing mysteriously](https://github.com/morelinq/MoreLINQ/pull/304#pullrequestreview-61429113).

The following methods are suspects and need to be investigated:

- ~[`Concat`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.concat?view=netcore-2.0)~
- ~[`OrderBy`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netcore-2.0)~
- [x] [`Prepend`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.prepend?view=netcore-2.0)
- ~[`Repeat`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.repeat?view=netcore-2.0)~
- [x] [`SkipLast`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skiplast?view=netcore-2.0)
- [x] [`TakeLast`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.takelast?view=netcore-2.0)
- ~[`ThenBy`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.thenby?view=netcore-2.0)~
- ~[`ToDictionary`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.todictionary?view=netcore-2.0)~
- [x] [`ToHashSet`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset?view=netcore-2.0)
- ~[`ToLookup`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolookup?view=netcore-2.0)~

**Comment by atifaziz** [comment]
📌  [`Append` and `Prepend`](https://github.com/dotnet/standard/blob/v2.0.0/netstandard/src/ApiCompatBaseline.net461.txt#L13-L14) are also landing in .NET Framework 4.7.1.

**Comment by Arithmomaniac** [comment]
[`ToHashSet`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset) landed in 4.7.2.

**Comment by atifaziz** [comment]
#214 needs closing as a priority.

**Comment by gojanpaolo** [comment]
Hello. Is there plans to remove/rename the conflicting methods in morelinq since it is now natively supported in .NET? I just got this issue when I tried to use `ToHashSet`. I worked around it by using `Enumerable.ToHashSet`.

**Comment by atifaziz** [comment]
@gojanpaolo Please see the usage section in the [README](https://github.com/morelinq/MoreLINQ/blob/v3.1.0/README.md#usage) for a workaround:

> ## Usage
>
> MoreLINQ can be used in one of two ways. The simplest is to just import the `MoreLinq` namespace and all extension methods become instantly available for you to use on the types they extend (typically some instantiation of `IEnumerable<T>`). In some very rare instances, however, doing so can cause conflicts with other libraries you may be using that incidentally also extend the same type with an identically named method and signature. This happened with MoreLINQ, for example, when Microsoft .NET Framework 4.0 introduced [`Zip`][netzip] and [MoreLINQ already had one][zip]. Starting with version 3.0 of MoreLINQ, you can reduce the potential for present (or even future) conflicts by individually importing just the extension methods you need using the [static imports feature introduced in C# 6][using-static]:
>
> ```c#
> using static MoreLinq.Extensions.LagExtension;
> using static MoreLinq.Extensions.LeadExtension;
> ```
> 
> In the example above, only the [`Lag`][lag] and [`Lead`][lead] extension methods will be available in scope.
> 
> Apart from extension methods, MoreLINQ also offers regular static method that *generate* (instead of operating on) sequences, like `Unfold`, `Random`, `Sequence` and others. If you want to use these while statically importing other individual extension methods, you can do so via aliasing:
> 
> ```c#
> using static MoreLinq.Extensions.LagExtension;
> using static MoreLinq.Extensions.LeadExtension;
> using MoreEnumerable = MoreLinq.MoreEnumerable;
> ```
> 
> In the example above, [`Lag`][lag] and [`Lead`][lead] will be available as extension methods as well as all the regular static methods on `MoreEnumerable` but _without_ any of the extension methods offered by `MoreEnumerable`.


[lag]: https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Lag.htm
[lead]: https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Lead.htm
[using-static]: https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/csharp-6#using-static
[netzip]: https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.zip--3
[zip]: https://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_Zip__3.htm
[unfold]: https://morelinq.github.io/2.3/ref/api/html/M_MoreLinq_MoreEnumerable_Unfold__3.htm
[random]: https://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Random.htm
[sequence]: https://morelinq.github.io/2.2/ref/api/html/Overload_MoreLinq_MoreEnumerable_Sequence.htm

**Comment by gojanpaolo** [comment]
Noted. Thank you!

**Comment by MatthewSteeples** [comment]
Not sure whether this is better opened in another issue, but as it's related to this I wanted to flag it here first. The workaround only works if you're using methods from a separate class. We want to use `.Batch` but it's causing conflicts with `.ToHashSet` because they're both on the same class

Wouldn't it make more sense to exclude these methods from assemblies targetting .NET 4.7.2 / NETSTANDARD 2? If that's acceptable I'm happy to put together a PR for it

**Comment by atifaziz** [comment]
> We want to use `.Batch` but it's causing conflicts with `.ToHashSet` because they're both on the same class

Don't import `MoreLinq` namespace. Instead, import just `Batch` like so:

```c#
using static MoreLinq.Extensions.BatchExtension;
```

Then you won't have any conflict. See the [Usage section in README](https://github.com/morelinq/MoreLINQ/tree/v3.1.1#usage) for more.

> Wouldn't it make more sense to exclude these methods from assemblies targetting .NET 4.7.2 / NETSTANDARD 2? If that's acceptable I'm happy to put together a PR for it

Wouldn't it make more sense to use the conflict-free approach already offered?

You may be interested in subscribing to #565 and following up there.

**Comment by MatthewSteeples** [comment]
Hi @atifaziz, Thanks for taking the time to respond. I _thought_ I'd followed the instructions in the README but I hadn't quite done it properly. I'd not noticed that there was a generated class file, and I was trying to statically import the method directly from https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Batch.cs which is part of a big partial class so did not work.

Entirely my own fault, and I feel quite dense for having had to raise it and not working it out myself! Thanks again
