### ISSUE TITLE
Choose (elements that can be projected)

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#358]
`Choose` will apply a function to _optionally_ project a result from each element of a sequence and returns a sequence of results that could be projected successfully.

## Prototype

```c#
public static IEnumerable<TResult> Choose<T, TResult>(this IEnumerable<T> source, Func<T, (bool IsSome, TResult Value)> chooser) =>
    from item in source
    select chooser(item) into option
    where option.IsSome
    select option.Value;
```

## Example

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => (int.TryParse(s, out var n), n));

Console.WriteLine(string.Join(", ", xs)); // 2, 3, 4, 6, 7, 9
```

## Motivation

You can't use the query syntax due to CS8201:

> Out variable and pattern variable declarations are not allowed within a query clause.

This doesn't work today:

```c#
var q =
    from s in "O,l,2,3,4,S,6,7,B,9".Split(',')
    // CS8201: Out variable and pattern variable declarations are
    //         not allowed within a query clause.
    select int.TryParse(s, out var n)
         ? (IsSome: true, Value: n)
         : (IsSome: false, Value: 0) into n
    where n.IsSome
    select n.Value;
```

The alternative using method chaining, while works, remains nonetheless verbose:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Select(s => int.TryParse(s, out var n)
                   ? (IsSome: true, Value: n)
                   : (IsSome: false, Value: 0))
        .Where(n => n.IsSome)
        .Select(n => n.Value);
```

The `Select` &rarr; `Where` &rarr; `Select` composition does not capture the intention as clearly as `Choose`.

Although not a huge benefit, `Choose` allows immediate projection (in limited cases) to an anonymous type:

```c#
var points =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => (int.TryParse(s, out var x), new { X = x, Y = x * 2 }));
```

`Choose` does not require labeling the returned tuple elements as it's clear from the context.

**Comment by fsateler** [comment]
It appears you are using `ValueTuple<bool, T>` as a substitute for a missing option type. It appears there are [other use cases for such a type](https://github.com/morelinq/MoreLINQ/pull/357/files#r144713341). Might it make sense to add an explicit type? On the one hand, I don't like introducing arbitrary types on sch a generic library, on the other, I like well-defined types for well-defined purposes.

**Comment by atifaziz** [comment]
> It appears you are using `ValueTuple<bool, T>` as a substitute for a missing option type.

Yes, I am. Is there something wrong with that? 😇

> Might it make sense to add an explicit type?

I'm trying to avoid that because there are a number of libraries out there providing an optional type and MoreLINQ would just add to the misery with the user being burdened with doing conversions. It's best to take the BYOT (bring your own type) approach as with all other operators but it ends up being somewhat cumbersome for `Choose`. For example, here is the bring-your-own-option-type version:

```c#
public static IEnumerable<TResult> Choose<T, TOption, TResult>(
    this IEnumerable<T> source,
    Func<T, TOption> chooser,
    Func<TOption, bool> predicate,
    Func<TOption, TResult> resultSelector)
    => from item in source
        select chooser(item) into option
        where predicate(option)
        select resultSelector(option);
```

Now here's the usage with nullables:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => int.TryParse(s, out var n) ? n : (int?) null,
                n => n != null, n => (int) n);
```

The user can also decide if he or she wants to use tuples or not:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => int.TryParse(s, out var n)
                    ? (IsSome: true, Value: n)
                    : (IsSome: false, Value: 0),
                n => n.IsSome, n => n.Value);
```

And if someone is already using an optional type, like one from [Optional](https://www.nuget.org/packages/Optional/), it would work like this:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => int.TryParse(s, out var n) ? n.Some() : 0.None(),
                n => n.HasValue, n => n.ValueOrFailure());
```

[Optional.Utilities](https://www.nuget.org/packages/Optional.Utilities/) also gives you [parsing functions](https://github.com/nlkl/Optional/blob/3.2.0/Optional.Utilities/Parse.cs) returning its optional type, so the above can be shortened to:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(Parse.ToInt, n => n.HasValue, n => n.ValueOrFailure());
```

But you'll agree that it gets cumbersome to teach `Choose` how to work with the type each place you use it. That's why taking advantage of tuples in C# seemed like a good compromise. Furthermore, you can still make it work with another optional type, show here again for `Option<>` from [Optional](https://www.nuget.org/packages/Optional/):

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => Parse.ToInt(s).Match(x => (true, x), () => (false, 0)));
```

And if you add an extension method to help with conversions:

```c#
public static (bool IsSome, T Value) ToTuple<T>(this Option<T> option) =>
    option.Match(some: v => (true, v),
                 none: () => (false, default(T)));
```

then it becomes even simpler to use:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => Parse.ToInt(s).ToTuple());
```

BTW, the ideal version of `Choose` would be one where you don't even see the tuple as you could supply the option constructors to the `chooser` function. This is what I would have liked to propose:

```c#
public static IEnumerable<TResult> Choose<T, TResult>(
    this IEnumerable<T> source,
    Func<T, Func<TResult, (bool, TResult)>, (bool, TResult), (bool IsSome, TResult Value)> chooser)
    => from item in source
        select chooser(item, result => (true, result), (false, default(TResult))) into option
        where option.IsSome
        select option.Value;
```

The usage would be:

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose((s, some, none) => int.TryParse(s, out var n) ? some(n) : none);
```

It would be particularly interesting because it would work really well with anonymous types. Unfortunately, the above code doesn't compile because the compiler's type inference engine fails. It requires explicit specification of type arguments and that's uncool:

```c
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose<string, int>((s, some, none) => int.TryParse(s, out var n) ? some(n) : none);
```

…unless I'm overlooking something?

**Comment by fsateler** [comment]
@atifaziz thanks for the detailed response. 

> I'm trying to avoid that because there are a number of libraries out there providing an optional type and MoreLINQ would just add to the misery with the user being burdened with doing conversions.

Right, that's what I thought. 

>  It's best to take the BYOT (bring your own type) approach as with all other operators but it ends up being somewhat cumbersome for Choose.

I have not been able to come up with an alternative that's better than what you have proposed.

Do you have a proposed alternative for platforms where `ValueTuple` is not supported? Or would this method just be missing?

**Comment by atifaziz** [comment]
> Do you have a proposed alternative for platforms where ValueTuple is not supported? Or would this method just be missing?

@fsateler No, it would be missing. The alternative is the overload I presented at the start of [my earlier comment](https://github.com/morelinq/MoreLINQ/issues/358#issuecomment-337267495) but I don't think anyone will find it palatable enough to ask for it. If I'm wrong, we can add it later. Yet another option would to be to provide overloads for reference & nullable types but I'd have to check if they'd cause a conflict or not (I'm guessing not). Thoughts?

**Comment by fsateler** [comment]
> No, it would be missing. The alternative is the overload I presented at the start of my earlier comment but I don't think anyone will find it palatable enough to ask for it. If I'm wrong, we can add it later.

I agree, it's not really nice. Let's just wait if anyone asks for it.

> Yet another option would to be to provide overloads for reference & nullable types but I'd have to check if they'd cause a conflict or not (I'm guessing not). Thoughts?

I'm undecided. AFAICT, the value this method provides is easing the use of methods with `out` parameters. I'm not sure I see much benefit in changing from 

```csharp
src.Choose(str => (int.TryParse(str, out var i), i))
```

Versus

```csharp
src.Choose(str => int.TryParse(str, out var i) ? i : (int?)null)
```

**Comment by atifaziz** [comment]
> the value this method provides is easing the use of methods with out parameters

I'd like to believe there's more to it but I'll be honest and say it's one big motivation when you don't have any other method handy. 😇 Suppose, though, that you are using a library like [TryParsers](https://github.com/atifaziz/TryParsers) that returns nullables instead of using using out-parameters, then a `Choose` overload can be used more directly:

```c#
src.Choose(TryParse.Int32)
```

Point would be, you don't need to teach `Choose` if you _already_ have a nullable. Needless to say, this can be added later too but it was to answer your question if something would be provided for frameworks without support for types backing value tuples.

**Comment by atifaziz** [comment]
In the [**Motivation** section of the opening comment](https://github.com/morelinq/MoreLINQ/issues/358#issue-265736479), I said:

> You can't use the query syntax due to CS8201:
>
>> Out variable and pattern variable declarations are not allowed within a query clause.

Seems that C# 7.3 is going address this somewhat by [limited use expression variables in query clauses](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-01-03.md#scoping-of-expression-variables-in-query-clauses), as illustrated below by @gafter's [example](https://github.com/dotnet/csharplang/issues/159#issuecomment-374704576) posted in dotnet/csharplang#159:

```c#
from s in e
let (b, i) = (int.TryParse(s, out int parsed), parsed)
where b
select i
```

Alas, the following still holds true:

> The `Select` &rarr; `Where` &rarr; `Select` composition does not capture the intention as clearly as `Choose`.

**Comment by leandromoh** [comment]
Why not ?

public static IEnumerable<TResult> Choose<T, TResult>(this IEnumerable<T> source, Func<T, bool> predicate, TResult Value)

**Comment by atifaziz** [comment]
@leandromoh Huh? 😕

**Comment by leandromoh** [comment]
About the API design: why not split chooser parameter in 2: predicate and value. So we dont need tuple. 

public static IEnumerable<TResult> Choose<T, TResult>(this IEnumerable<T> source, Func<T, bool> predicate, TResult value)

**Comment by atifaziz** [comment]
How do you go from `T` to `TResult` for all `T` where `predicate` returns `true`? What's the purpose of `value`? Do you propose to return a _constant_ `TResult` for all `T` where `predicate` returns `true`? If so, that's not what I'm proposing here. If I'm missing something still then perhaps a worked out example would help.

**Comment by leandromoh** [comment]
Sorry,  what i meant was something similar to what se did in unfold operator.
Maybe this may go as another overload aside the tuple's one.

```c#
public static IEnumerable<TResult> Choose<T, TState, TResult>(this 
IEnumerable<T> source, 
Func<T, TState> generate,
Func<TState, bool> predicate, 
Func<TState, TResult> selector)
```

**Comment by atifaziz** [comment]
Okay now I understand and we can consider it as an overload after adding the basic one. However, you overload has the disadvantage that if you want to use C# tuples for `TState` then you'll have to name the tuple elements for clarity whereas the version I'm proposing doesn't; see the example in [my opening comment](https://github.com/morelinq/MoreLINQ/issues/358#issue-265736479):

```c#
var xs =
    "O,l,2,3,4,S,6,7,B,9"
        .Split(',')
        .Choose(s => (int.TryParse(s, out var n), n));
```

**Comment by atifaziz** [comment]
True but that's a refactoring after adding the more generic overload. However, my guess is that the generic overload will hardly be used because of this:

> But you'll agree that it gets cumbersome to teach `Choose` how to work with the type each place you use it. 

See the rationale and plenty examples laid out in [my argument](https://github.com/morelinq/MoreLINQ/issues/358#issuecomment-337267495).
