### ISSUE TITLE
AssertCount is inconsistently lazy

### ISSUE THREAD

**Issue by Arithmomaniac** [morelinq/MoreLINQ#364]
This test says that `AssertCount` is expected to be lazy:

https://github.com/morelinq/MoreLINQ/blob/64cb2632dd4e9813ae2dc2c0c6ab0aa7302bd70c/MoreLinq.Test/AssertCountTest.cs#L99-L103

However, this is not true for collections:

https://github.com/morelinq/MoreLINQ/blob/64cb2632dd4e9813ae2dc2c0c6ab0aa7302bd70c/MoreLinq/AssertCount.cs#L86-L92

This would lead to different results for, e.g. `myEnumerable.AssertCount(3).ForEach(someFunction);`, if `myEnumerable` had more than three options.

One way to fix this would be to do like the follows:
- If passes condition, return the list
- If list too long, do something like `myList.Take(count).Concat(new ExceptionThrowingEnumerable())`
- If list is too short, do something like `myList.Concat(new ExceptionThrowingEnumerable())`

**Comment by atifaziz** [comment]
This is a good catch and definitely a bug that needs addressing!

**Comment by atifaziz** [comment]
> - If passes condition, return the list

:+1:

> - If list too long, do something like myList.Take(count).Concat(new ExceptionThrowingEnumerable())
> - If list is too short, do something like myList.Concat(new ExceptionThrowingEnumerable())

Why not throw as soon as it's enumerated?

**Comment by Arithmomaniac** [comment]
Because for a non-collection enumerable, it wouldn't throw until you took `count` items (or reached the end, if it had fewer than `count` items).

**Comment by Arithmomaniac** [comment]
The commit seems to not worry about the fact that the error case will not work identically to the `IEnumerable` error case; I take it that was a design choice?

**Comment by atifaziz** [comment]
> I take it that was a design choice?

Yes. Should it matter unless you're rely on side-effects?

**Comment by Arithmomaniac** [comment]
Don't think so.
