### ISSUE TITLE
Is SDK pinning in global.json necessary?

### ISSUE THREAD

**Issue by fsateler** [morelinq/MoreLINQ#378]
Currently we have `global.json` pinning the sdk version to `"version": "2.0.0"`. Is this strictly necessary? I have just installed a new machine and I got the following error:

> The specified SDK version [2.0.0] from global.json [C:\path\to\global.json] not found; install specified SDK version

But I installed the latest sdk version (2.1.4). This pinning means I have to go and find the appropriate sdk version to install. Not really difficult, but I think it is unnecessary. Unfortunately, `global.json` [does not support ranges or wildcards](https://github.com/dotnet/core-setup/issues/679), so we have two have a specific pin or no pin at all.

The downside of pinning is requiring everyone to install the given SDK version.
I don't know what the downsides are of unpinning, thus my question: is pinning necessary?

**Comment by atifaziz** [comment]
> I don't know what the downsides are of unpinning, thus my question: is pinning necessary?

Incompatibilities with simple things like command-line arguments changing in tools/sub-commands. I don't have any concrete examples handy at the moment but the idea is to build against the tested SDK and avoid headaches and surprises. The bonus is that the error message of, “The specified SDK version [2.0.0] from global.json not found; install specified SDK version,” is very clear.

`global.json` is also a historical note in the repo about which SDK version a particular commit was built against. There's nothing more annoying than checking out an old version of your code and finding you can't build it anymore.

> The downside of pinning is requiring everyone to install the given SDK version.

This could be mitigated by doing an automatic and _local_ install (like in `./dotnet`) of the SDK as part of the build step. This is apparently as simple as [downloading via `curl` and extracting using `tar`](https://github.com/dotnet/core/blob/46a2281edd923dda16eca41df1bd77f274644b91/release-notes/download-archives/2.0.0-download.md#installation-from-a-binary-archive).

**Comment by fsateler** [comment]
> The bonus is that the error message of, “The specified SDK version [2.0.0] from global.json not found; install specified SDK version,” is very clear.

Indeed, it is. Unfortunately upstream dotnet is not very clear on installing non-latest versions (one needs to go fishing via google), but that is not something that could or should be fixed here.

> This could be mitigated by doing an automatic and local install (like in ./dotnet) of the SDK as part of the build step.

I don't think morelinq should work around awkwardness in the dotnet tooling. Dotnet itself should have a method to fetch a given sdk version.

> Incompatibilities with simple things like command-line arguments changing in tools/sub-commands. I don't have any concrete examples handy at the moment but the idea is to build against the tested SDK and avoid headaches and surprises.

This is  a good reason (although unfortunately the format does not allow version ranges, which would help a lot here). I consider the question answered, and I don't think MoreLINQ has to do anything.

**Comment by atifaziz** [comment]
> Dotnet itself should have a method to fetch a given sdk version.

There is [dotnet-install](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).
