### ISSUE TITLE
Support returning some count of Max/MinBy

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#380]
Since #328 changes [`MaxBy`][maxby] and [`MinBy`][minby] to return a list, I propose to add `PartialMaxBy` and `PartialMinBy` that take an extra parameter indicating the maximum count of extrema elements to return. It avoids wastage building a list of all extrema elements ~and scanning the entire source sequence~ when one may be satisfied with, for example, any of the first ones.

[maxby]: http://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_MaxBy.htm
[minby]: http://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_MinBy.htm

**Comment by leandromoh** [comment]
It does not make sense, because we always have to Scan The entire source, since the extreme element may be the last one.

**Comment by atifaziz** [comment]
@leandromoh Of course 🤦‍♂️ and thanks for setting me straight. However, it is still useful to not have to waste building a list of all extrema if one is happy with less.

**Comment by leandromoh** [comment]
@atifaziz How common is this cenario (source with **great** number of extrema elements)? 
Does it justify a new operator?

**Comment by atifaziz** [comment]
@leandromoh I can't speak for the world so it's hard for me to say whether it's common or not. The one time I did need `MinBy` and `MaxBy`, I know I needed a list as a result. Asking for a single item (as they've been implemented up to now) means you'll get any one of the extrema and that's rarely useful.

The real reason for proposing partial versions is to provide an option for those people who have been relying on `MinBy` and `MaxBy` returning a single item as we've made a breaking change and both methods have been part of MoreLINQ's history for an exceptionally long time; in fact, since as early as [the second commit](https://github.com/morelinq/MoreLINQ/commit/76ae6927b347e3ee66c07dff7c6e1bec2e99f889)! They have even been [mentioned](https://books.google.ch/books?id=3HqnBQAAQBAJ&lpg=PA122&ots=79WaRJwsJc&dq=morelinq%20minby%20maxby&pg=PA122#v=onepage&q=morelinq%20minby%20maxby&f=false) in the book [Thinking in LINQ](https://www.apress.com/us/book/9781430268451)!

`PartialMinBy` and `PartialMaxBy` with an upper limit are interesting if you're want some sample of an extremum, like 10 files of the largest files size in a directory. For small samples, I agree you can compose `MinBy` or `MaxBy` with `Take`.
