### ISSUE TITLE
T4 template generation for all IDEs & non-Windows platforms

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#381]
T4 is used for code generation, like in [`Fold.g.tt`][Fold.g.tt] and [`ToDelimitedString.g.tt`][ToDelimitedString.g.tt]. T4 is great when you have VS as your primary IDE and building on Windows but there should be a way to refresh the generated code for someone using another IDE and on another platform than Windows. It doesn't have to be as integrated an experience as T4 enjoys in VS so just a command-line alternative would do.

[Fold.g.tt]: https://github.com/morelinq/MoreLINQ/blob/812045328654177044e67eb93212efa3a7de20a8/MoreLinq/Fold.g.tt
[ToDelimitedString.g.tt]: https://github.com/morelinq/MoreLINQ/blob/812045328654177044e67eb93212efa3a7de20a8/MoreLinq/ToDelimitedString.g.tt

**Comment by fsateler** [comment]
I found out today about Scripty: https://github.com/daveaglick/Scripty

**Comment by atifaziz** [comment]
I am aware of Scripty but I have something else in mind for sake of compatibility: [T5](https://github.com/atifaziz/t5). It is my fork of [Mono.TextTemplating](https://www.nuget.org/packages/Mono.TextTemplating) that's been made to work on .NET Core.

If you are interested in some background, see [my comment](https://github.com/mono/t4/issues/8#issuecomment-363590843) in mono/t4#8.

**Comment by atifaziz** [comment]
Closed via c418b1cb6aa3a6318179442374680e7269256f37.
