### ISSUE TITLE
HasSingleElement

### ISSUE THREAD

**Issue by Brondahl** [morelinq/MoreLINQ#382]
I often find myself wanting to either check that I've only got 1 element, or condition my code on whether or not a collection has exactly 1 element.

If I want to efficiently check whether my IEnumerable (`foo`) is Empty, I can use `!foo.Any()`.
If I want to efficiently check whether it has exactly 1 element, it's much less pleasant. `foo.Skip(1).Any()` is correct and efficient, but isn't really clear what you're trying to say. `foo.Count() = 1` is inefficient if the answer is "No, there are more elements.", anything resembling `catch() {foo.Single()}` is just appauling for multiple reasons.

I propose adding `HasSingleElement`  (or `IsSingle`, or `ContainsOnlyOneElement`, or any other variation of the name that people prefer.) which implements this efficiently at the manual enumeration level.
The implementation would follow the logic of `foo.Skip(1).Any()`

Questions:
A) How do you (people who have design understanding of MoreLINQ) feel about this proposal?
B) What do I need know about contributing to MoreLINQ in order to produce a PR for this myself? Is there an "ideal PR" for a new function that I should use as a template?

**Comment by atifaziz** [comment]
Why not use [`Exactly`](https://morelinq.github.io/2.1/ref/api/html/M_MoreLinq_MoreEnumerable_Exactly__1.htm), as in `Exactly(1)`?

**Comment by Brondahl** [comment]
Ah ... because I didn't know that existed, and it doesn't show up if you search the docs for anything that mentions "Single" or "One" :)

Now that I've seen that, I also searched for "Count", which I note doesn't hit `Exactly` but does hit `CountBetween` which would work just as well.

I shall use that in future.

I would argue that adding that method may still be useful, in terms of adding discoverability (or perhaps renaming / adding an alternate name of `CountIsExactly`), but I agree that it's much less important if the functionality does already exist.

**Comment by atifaziz** [comment]
I agree that the document search isn't the best so I would recommend [searching the docs using Google instead](https://www.google.ch/search?q=site%3Amorelinq.github.io+count).

> in terms of…discoverability

I think this is a separate issue that could apply to a number of other operators.

> I agree that it's much less important if the functionality does already exist.

I'll close this issue on that basis.

**Comment by Brondahl** [comment]
FBM. Thanks for the responses.
