### ISSUE TITLE
Clean up special test collections/lists

### ISSUE THREAD

**Issue by Arithmomaniac** [morelinq/MoreLINQ#385]
Refactoring suggestions for MoreLinq.Test:

1) This pattern:
```c#
readOnly
    ? new UnenumerableReadOnlyList<int>(new[] { 1 })
    : (IEnumerable<int>)new UnenumerableList<int> { 1 };
```
Has come up often enough at this point that I think a future commit (or even this one) should consolidate it into a helper method of signature `IEnumerable<T> GetUnenumerableList<T>(bool readOnly, params T[] items)`.

2) `Unenumerable(ReadOnly)List` should inherit from `BreakingSequence`.

3) `Breaking(ReadOnly)Collection` should be replaced with `Unenumerable(ReadOnly)List`.

**Comment by atifaziz** [comment]
Makes sense. The exact shape and form of the consolidation may become clearer and need debating when you submit a PR.

**Comment by Arithmomaniac** [comment]
I'm currently leaning towards an extension method for 1): `IEnumerable<T> ToUnenumerable<T>(this T[] enumerable, bool readOnly)`.
