### ISSUE TITLE
GetCheapCount internal method

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#386]
Almost always when we try to cast a sequence for collection is about its `Count` property. 

Now that we are also checking for `IReadOnlyCollection`, It is becomming a bit repetitive and with a lot of ternarious opetator. To avoid this I suggest To create the `GetCheapCount` internal method. This one tries all the possible casts and return the `count` If avaible.

Initial signature suggestion:

`Internal static int? GetCheapCount<T>(this IEnumerable<T> souce)`

**Comment by atifaziz** [comment]
Sometimes you need the count _and_ the collection type you cast to.

> It is becomming a bit repetitive and with a lot of ternarious opetator.

Do you have a list of places where this would be make savings? If you want to demonstrate that through a PR then that's fine too (sometimes code can speak volumes) as long as you're not disheartened if we decide to abandon it at the end; that is, if the savings don't seem worthwhile.

**Comment by Arithmomaniac** [comment]
Since an `IReadOnlyCollection` is just an `IEnumerable` with a count, you should be able to use it in any of the optimizations listed in #128 for `IReadOnlyCollection`.

**Comment by Arithmomaniac** [comment]
You could similarly catch all of the `IReadOnlyList` cases, too. If I was to implement this, I would have the two following method signatures:

`bool IsCollectionType<T>(this IEnumerable<T> enumerable, out int count)`

`bool IsListType<T>(this IEnumerable<T> enumerable, out int count, out Indexer<T> indexer)`, using `delegate T Indexer<T>(IEnumerable<T> enumerable, int index)`

Using `out` works very nicely with the C#7 out conditions, as you can check for the Collection/List case with a ternary expression.

**Comment by Arithmomaniac** [comment]
@leandromoh do you plan on working on this? If not, I'll do it this coming week.

**Comment by atifaziz** [comment]
`IsCollectionType` should instead be called `TryGetCollectionCount` because it says more clearly what it's doing:

```c#
bool TryGetCollectionCount<T>(this IEnumerable<T> source, out int count) // can live with
int? TryGetCollectionCount<T>(this IEnumerable<T> source) // preferred and as effective
```

The second signature allows you to use pattern matching, as in `source.TryGetCollectionCount() is int count` and reads better.

For the list, I would open a separate issue/PR.

**Comment by leandromoh** [comment]
@Arithmomaniac No, I am not planning to work on this. Go ahead =)

Another bônus of this method is that If in a future version of the framework appears another interface with Count , we can simply add this on TryGetCount, instead of replace everywhere.

**Comment by Arithmomaniac** [comment]
@atifaziz I would prefer the first of those two options, since:
 - it is more idiomatic to C# (e.g. `TryParse`)
 - its equivalent for #390 (if we choose to do that) looks more reasonable to me.

**Comment by atifaziz** [comment]
> - it is more idiomatic to C# (e.g. `TryParse`)

This is an internal API and nullables are equally idiomatic to C#. We should strive to write functions with input arguments and return values before resorting to by-ref semantics.

I am also unsure #390 will be solved in the same way; too early to say.
