### ISSUE TITLE
SelectWithPrevious 

### ISSUE THREAD

**Issue by MkazemAkhgary** [morelinq/MoreLINQ#389]
Alternative to that is

    source.Skip(1).Zip(source, (curr, prev) => ...);

but I found `SelectWithPrevious` better option. I think it worth being added here. one reason is its readability.

but more important reason is that you will enumerate main source only once which is crucial sometimes and has more performance for sure.

https://stackoverflow.com/a/3683217/4767498

**Comment by MkazemAkhgary** [comment]
Just realized that `Incremental` does the same thing.

**Comment by atifaziz** [comment]
`Incremental` has been removed from the [upcoming 3.0 release](https://github.com/morelinq/MoreLINQ/issues?q=is%3Aclosed+milestone%3A3.0.0) (see #242). You should use [`Pairwise`](https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Pairwise__2.htm) instead.

**Comment by MkazemAkhgary** [comment]
@atifaziz thanks informing that ^^
