### ISSUE TITLE
Add internal IsListType method to simplify IReadOnlyList optimizations

### ISSUE THREAD

**Issue by Arithmomaniac** [morelinq/MoreLINQ#390]
Parallel to #386, but for lists; would simplify the code in `AggregateRight`, `SingleOrFallback`, and `Slice`.

Proposed method signature (though the final one would depend on what is chosen for #386):

`bool IsListType<T>(this IEnumerable<T> enumerable, out int listCount, out Func<int, T> listIndexer)`

**Comment by atifaziz** [comment]
Would be good if we can avoid the closure allocation that'll come with `listIndexer`, given the proposed signature of `Func<int, T>`.

**Comment by Arithmomaniac** [comment]
As long as there is some `Func<int, T> CreateIndexer(INumerable<T> enumerable)` method external to `IsListType`, that shouldn't be a problem, right? Or would a closure still be created because you are using the `enumerable` parameter?

**Comment by atifaziz** [comment]
> Or would a closure still be created because you are using the `enumerable` parameter?

Exactly.

**Comment by Arithmomaniac** [comment]
We have finished #128 and decided not to go this way.
