### ISSUE TITLE
Scan iterates too eagerly

### ISSUE THREAD

**Issue by quassnoi** [morelinq/MoreLINQ#392]
When doing Scan (regular or seeded), the source gets iterated once too many times.

Scan should yield the first element right after it has been read from the source, but it waits for the next element to be read instead.

I've put together a PR to fix this.

**Comment by atifaziz** [comment]
Great catch and appreciate the PR _with_ tests. 👍 

Since [3.0](https://github.com/morelinq/MoreLINQ/milestone/2) might not be out any time soon, I'm inclined to push this out earlier in a maintenance 2.x release. 🤔

**Comment by atifaziz** [comment]
I'm filing this as a bug because while `Scan` isn't doing anything wrong, speaking logically/strictly, an undesirable effect shouldn't be _observable_ as [asserted by the tests](https://github.com/quassnoi/MoreLINQ/blob/1c9378639e94b1df482817041c5f40d332dee906/MoreLinq.Test/ScanTest.cs#L50-L51).
