### ISSUE TITLE
Recurrent TakeWhile

### ISSUE THREAD

**Issue by MkazemAkhgary** [morelinq/MoreLINQ#394]
Im not sure what would be the good name but i have such scenario where enumerations can be suspended (due to some conditions) but no terminated. It can be continued later. So i did this

    enunerator = readonly_query.TakeWhile(x => !suspended).GetEnumerator();

Notice that im using enumerator not enumerable. Using a temporary struct i can use it with foreach. 

    foreach(var x in enumerator.GetEnumerable()) 
    {
    }

When "suspended" becomes true foreach ends. But enumerator (or another foreach) should be able to continue the enumeration once "suspended" is false.

Problem with TakeWhile is that once a condition is false, enumeration will end regardless of what is left in sequence. 

Therefor Im asking for a method say `TryTakeWhile` or `RecurrentTakeWhile` that does not reach its true end while a condition is false. 

It seems yield break will end enuneration. I have to write custom class for that :(

**Comment by MkazemAkhgary** [comment]
TryTake would be a cool name too

**Comment by atifaziz** [comment]
I think what you want, speaking at a very high-level, is to break a sequence into a sequence of sequences with a predicate function determining where the breaks should occur in the source sequence. You would then be able to for-each on the sub-sequences. The content of each sub-sequence would be buffered but the sub-sequences themselves could be yielded in a streaming fashion. If that captures the essence, I'm curious about how you go about _threading_ your suspensions now without concurrency? In my mind, the predicate would be a function of some element of the sequence. Unlike [`Split`](http://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_Split.htm), the _breaking element_ would be a terminator of one sequence but included in the next (in `Split`, the splitting element is removed from the resulting sequence).

> It seems yield break will end enuneration. I have to write custom class for that :(

You can write a [local function](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#local-functions) to avoid that if you have the luxury to use [C# 7](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7).

**Comment by MkazemAkhgary** [comment]
I need this functionality at real time. suspended property is like a pause and resume to the end user (although part of condition relates to sequence). 

The key solution was to "break a sequence into a sequence of sequences". exactly what I needed, once inner enumerable reaches the end I can continue the enumeration because outer enumerable is not finished yet.

I didn't like the implementation of `Segment` and `Split` because subsequences were buffered in a list. so I made something my self. (thanks for pointing out the key solution other wise I would be stumped for all day!)

I think my implementation adds less garbage in the run. (maybe `Segment` and `Split` could be improved in this way.)

    public static IEnumerable<IEnumerable<TSource>> RecurrentTakeWhile<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
    {
        if (source == null) throw new ArgumentNullException(nameof(source));

        return GetEnumerable();

        IEnumerable<IEnumerable<TSource>> GetEnumerable()
        {
            using (IEnumerator<TSource> enumerator = source.GetEnumerator())
            {
                bool end = false; TSource current;

                if (!enumerator.MoveNext()) yield break; // initial move

                while (!end) yield return TakeWhile(); // yield sub-sequences

                IEnumerable<TSource> TakeWhile()
                {
                    do
                    {
                        current = enumerator.Current; // store current item into singular buffer.

                        if (predicate(current))
                        {
                            yield return current;
                        }
                        else
                        {
                            yield break;
                        }
                    } while (enumerator.MoveNext());

                    end = true; // true end is reached!
                }
            }
        }
    }

---

Out of curiosity, what's the difference between `Segment` and `Split`?

**Comment by atifaziz** [comment]
So what you really want is `Segment`.

> I didn't like the implementation of `Segment`…because subsequences were buffered in a list.

If you're returning a sequence of sequences (i.e. `IEnumerable<IEnumerable<TSource>>`) then each sub-sequence has to be independent of the other sub-sequences. The kind of behaviour you seem to be after is perhaps more correctly modeled as `IEnumerator<IEnumerator<TSource>>`; that is, a _cursor_ over _cursors_, over fundamentally the same (source) sequence. You won't be able to use for-each but you'll be able to run a while-loop, which is looping either way. The devil is in the semantics.

> I need this functionality at real time. suspended property is like a pause and resume to the end user 

Perhaps Rx is a better answer.

> I think my implementation adds less garbage in the run.

Garbage? Like what?

> Out of curiosity, what's the difference between `Segment` and `Split`?

`Segment` splits _between_ elements whereas `Split` splits _on_ an element. The former returns the element in the result whereas the latter removes it. `Split` is modeled after [`String.Split`](https://docs.microsoft.com/en-us/dotnet/api/system.string.split) where the delimiter is assumed to be embedded in the source sequence. For example, the following segmentation:

```c#
Enumerable.Range(1, 10)
          .Segment(x => x % 3 == 0)
          .Select(s => "[" + s.ToDelimitedString(", ") + "]")
          .ToDelimitedString("; ")
```

will return `[1, 2]; [3, 4, 5]; [6, 7, 8]; [9, 10]`. If you replace `Segment` with `Split`, you'll get `[1, 2]; [4, 5]; [7, 8]; [10]`.

**Comment by MkazemAkhgary** [comment]
>Perhaps Rx is a better answer.

ill look into it. I got this suggestion long time ago for another project. looks like its very powerful that programmers suggest to use it. thanks, ill try it.

>Garbage? Like what?

well, my implementation does not create temporary lists, in my case, sequence is not short and can run for a long time, there are timing controls on that too. but looks like GC is very effective at collecting those temporary objects.

>Segment splits between elements whereas Split splits on an element...

great explanation, thank you.
