### ISSUE TITLE
Need a wiki page for each operator

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#4]
We should really create a wiki page with a simple example of each operator as we implement it.

---

Originally reported on Google Code with ID 4

Reported by @jskeet on 2009-02-15 21:28:49

**Comment by JamesFaix** [comment]
I've started making some pages for operators on my clone of the project, but there isn't a clear way to do wiki pull requests.

**Comment by fsateler** [comment]
It appears it is not possible, but you can still clone the repo, and then the PR is manual but can be done via the ususal git tools

**Comment by atifaziz** [comment]
@JamesFaix @fsateler This is an old issue from 2009 and perhaps relevant at a time when wiki was the way to go on Google Code. It also gave you a URL per operator. However, since then, I've put docs online for [1.x][docs1.x] and [2.0][docs2.0] that are generated from XML doc comments in code so there's one source. Maintaining a wiki would be duplicate effort. If anything, it would be better to spend that energy instead on [improving docs](https://github.com/morelinq/MoreLINQ/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) (possible including [docs site](https://github.com/morelinq/morelinq.github.io)) and investigating if [DocFx](http://dotnet.github.io/docfx/) helps deliver more value over [Sandcastle](https://github.com/EWSoftware/SHFB).

[docs2.0]: https://morelinq.github.io/2.0/ref/api/html/N_MoreLinq.htm
[docs1.x]: https://morelinq.github.io/1.x/ref/api/html/N_MoreLinq.htm

**Comment by fsateler** [comment]
@atifaziz I agree. I think this issue should be closed, and any improvements should go to the xmldocs.
