### ISSUE TITLE
Optimize Batch to return lazy enumerables

### ISSUE THREAD

**Issue by Arithmomaniac** [morelinq/MoreLINQ#400]
This takes the point of #98 and runs it in an opposite direction: What if `Batch` really only returned lazy `IEnumerable<T>`s for each batch, without getting all of the items in the batch first?

This [StackOverflow answer](https://stackoverflow.com/questions/419019/split-list-into-sublists-with-linq/10425490#10425490) contains such an implementation.

**Comment by atifaziz** [comment]
Best if @SamSaffron, whose implementation you cite, drops by himself and contributes the implementation along with tests. 😄 Short of that, I don't see it happening any time soon as it's a fairly involved implementation to undertake. On a quick run, I noticed it does multiple passes over the source (possibly by design). I didn't dig in to understand why because I don't have the bandwidth for it right now (involved in far too many projects for my own good, I'm afraid). I'm happy if you are volunteering to investigate. I reckon it's not an easy problem.

**Comment by Arithmomaniac** [comment]
Not volunteering; I myself barely have enough time to keep up with #128 🙁

**Comment by leandromoh** [comment]
If I understood right, my sketch bellow does that. As well the [stackoverflow asnwer](https://stackoverflow.com/questions/419019/split-list-into-sublists-with-linq/10425490#10425490), it is not thread safe.

```
public static IEnumerable<IEnumerable<T>> Batch<T>(this IEnumerable<T> source, int size)
{
    if (source == null) throw new Exception();

    return BatchImpl(source, size).TakeWhile(x => x.Any());
}

static IEnumerable<IEnumerable<T>> BatchImpl<T>(this IEnumerable<T> source, int size)
{
    var e = source.GetEnumerator();
    var list = new List<T>();
    var i = 1;

    while (true)
    {
        yield return Oi(e, list, i, size);
        i++;
    }
}

static IEnumerable<T> Oi<T>(IEnumerator<T> e, List<T> list, int group, int size)
{
    var min = (group - 1) * size + 1;
    var max = group * size;
    var hasValue = false;

    while (list.Count < min && e.MoveNext())
    {
        list.Add(e.Current);
    }

    for (var i = min; i <= max; i++)
    {
        if (i <= list.Count)
        {
            hasValue = true;
        }
        else if (hasValue = e.MoveNext())
        {
            list.Add(e.Current);
        }

        else
        {
            e.Dispose();
        }

        if (hasValue)
            yield return list[i - 1];
        else
            yield break;
    }
}
```

**Comment by atifaziz** [comment]
@leandromoh The only trouble is that the source is entirely committed to memory if all batches of elements are visited, which is usually the case. If `source` has a million elements, memory will grow as you work through the batches. With the current `Batch` implementation that buffers the list, the worst you are committing to memory is the batch size. When you move on to the next batch, the previous becomes fodder for GC. Laziness is an important property for when dealing with sequences but that's not the case with batches where they are known to be finite in size. That said, `Batch` can still work with the source sequence being infinite.

**Comment by leandromoh** [comment]
@atifaziz I see. I submit a [PR ](https://github.com/morelinq/MoreLINQ/pull/402) with the necessaries improviments.

**Comment by SamSaffron** [comment]
@atifaziz a point of reference here, Sam has not launched visual studio in 5 years and has looked at very tiny amount of c# code since. 

> drops by himself and contributes the implementation along with tests.

accordingly, chances are not too high this will be happening 🏖

**Comment by atifaziz** [comment]
Closing as abandoned as no one has volunteered to champion this.
