### ISSUE TITLE
EnumerateRows/EnumerateCols suggestion

### ISSUE THREAD

**Issue by martinfreedman** [morelinq/MoreLINQ#403]
When it comes to regular 2D arrays e.g. `T[,]` there is no default Enumerable behaviour.

An option is to convert to a jagged array e.g. `T[][]` and then you can enumerate rows but if you want columns you have to transpose - adding the cost of a conversion of data and, possibly, a transposition too.

Another option is to  use existing library such as math.Net that supports regular arrays with methods `EnumerateRows()` and `EnumerateColumns()`, however you have to convert to its internal Matrix type, but now no transposition is required to enumerate columns. Since math.Net does not support int[,] you have to use (implicit) casting to do the conversion. Why should this be limited to floating point data, rather than any numerical type? Why limit it just to numerical types? It could be used for string, DateTime etc.

So why not do this directly on the regular array?

I propose 4 methods:-

`IEnumerable<IEnumerable<T>> EnumerateRows<T>(this T[,] matrix)` 
`IEnumerable<IEnumerable<T>> EnumerateCols<T>(this T[,] matrix)` 

`IEnumerable<IEnumerable<(T,int)>> EnumerateRowsWithIndex<T>(this T[,] matrix)`  `IEnumerable<IEnumerable<(T,int)>> EnumerateColsWithIndex<T>(this T[,] matrix)`. 

Then there are no conversion, casting, memory space nor transposition costs. The methods would use built-in IL efficient code for loops with no bounds checking required. (Not suggesting unsafe pointers and pointer arithmetic optimisations for now... but, theoretically, should be be available whereas not so with jagged arrays.)

I could generalise this to 3D arrays and above, if requested but then some clarity over the Rank Conjunction higher-order function from array functional languages such as J or APL might be required. Can probably make this trivial for those not familiar with such but **I think just a 2D implementation is probably all that is needed for now?** 

I have long done this and added in various personal libraries. For trivial examples see my gist https://gist.github.com/martinfreedman/120cade6e9a925e85d8ea993ba942161

If discussion is positive here I can quickly produce a PR.

P.S. The WithIndex methods, as indicated by signatures, might need some discussion.

**Comment by atifaziz** [comment]
@martinfreedman Thanks for your detailed proposal. `EnumerateRows` and `EnumerateCols` are useful methods and I've had their need in the past too. The only problem I see is that these methods are extensions for multi-dimensional arrays rather than sequences and so they belong in library of array extension methods rather than here in MoreLINQ, even if the output is sequence. If we add these methods then they would become an excuse for anyone to start proposing extensions to other types that yield sequences.
