### ISSUE TITLE
new Acquire overload

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#405]
in a similar scenario that #404, sometimes some elements of a sequence can not be access, but we must do something with all avaible elements.

scenario :

```c#
foreach (var element in source) // if some element can not be reach, we must skip it
{ 
       // do something with element 
}
```
example of error :

```c#
Enumerable.Range(1, 10).Select(x =>
{
    if (x % 5 == 0)
        throw new InvalidOperationException();
    else
        return x;
}).ForEach(p => Console.WriteLine(p));
```

here we can not access elements 5 and 10, but the others can be printed.

So I propose a new operator that do this handling and return a sequence with all avaible elements.

Propose signature:

```c#
public static IEnumerable<T> Available<T>(this IEnumerable<T> source)
```

example of usage:

```c#
Enumerable.Range(1, 10).Select(x =>
{
    if (x % 5 == 0)
        throw new InvalidOperationException();
    else
        return x;
})
.Available()
.ForEach(Console.WriteLine);
```
now all elements except 5 and 10 are printed.

Draft: 

```c#
public static IEnumerable<T> Available<T>(this IEnumerable<T> source)
{
    if (source == null) throw new ArgumentNullException(nameof(source));

    var e = source.GetEnumerator();
    bool hasValue;
    bool dispose = false;

    while (true)
    {
        hasValue = true;
        try
        {
            if (!e.MoveNext())
            {
                e.Dispose();
                dispose = true;
            }
        }
        catch
        {
            hasValue = false;
        }

        if (dispose)
            yield break;

        if (hasValue)
            yield return e.Current;
    }
}
```

I would like to submit a PR for this. What do you think?

PS: the operator name is not defined yet;

**Comment by atifaziz** [comment]
Generally speaking, I don't think exceptions should be dealt with exceptionally. They should be part of the query:

```c#
var xs =
    from x in Enumerable.Range(1, 10)
    select (Item: x, Error: x % 5 == 0 ? new InvalidOperationException() : null) into r
    where r.Error == null
    select r.Item;

q.ForEach(x => Console.WriteLine(x));
```

However, I can imagine that if the exception is thrown by some third-party code that's not under your control then such an operator can be useful.

I would call it `IgnoreErrors` but it should allow you to specify the specific errors to ignore, e.g.:

```c#
public static IEnumerable<T> IgnoreErrors<T, TException>(
    this IEnumerable<T> source,
    Func<T, TException, bool> errorPredicate) { /* ... */ }

public static IEnumerable<T> IgnoreErrors<T, TException1, TException2>(
    this IEnumerable<T> source,
    Func<T, TException1, bool> error1Predicate,
    Func<T, TException2, bool> error2Predicate) { /* ... */ }

public static IEnumerable<T> IgnoreErrors<T, TException1, TException2, TException3>(
    this IEnumerable<T> source,
    Func<T, TException1, bool> error1Predicate,
    Func<T, TException2, bool> error2Predicate,
    Func<T, TException3, bool> error2Predicate) { /* ... */ }
```

Up to 3 exception types should be sufficient.

**Comment by leandromoh** [comment]
> However, I can imagine that if the exception is thrown by some third-party code that's not under your control then such an operator can be useful.

Exactly.

> I would call it IgnoreErrors but it should allow you to specify the specific errors to ignore, e.g.:

We can not pass a `T` for `predicate` because the element are inaccessible or could not be projected (and therefore dont exist).

That said, I think a better signature would be the following: 

```
public static IEnumerable<T> IgnoreErrors<T>(
    this IEnumerable<T> source,
    Action<Exception> exceptionHandler)
```

```
public static IEnumerable<TResult> IgnoreErrors<TSource, TResult>(
    this IEnumerable<TSource> source,
    Func<TSource, Exception, TResult> selector)
```

**Comment by atifaziz** [comment]
> We can not pass a T for predicate because the element are inaccessible or could not be projected (and therefore dont exist).

Sorry, that was a mistake. You are correct and what I meant what this:

```c#
public static IEnumerable<T> IgnoreErrors<T, TException>(
    this IEnumerable<T> source,
    Func<TException, bool> errorPredicate) { /* ... */ }

public static IEnumerable<T> IgnoreErrors<T, TException1, TException2>(
    this IEnumerable<T> source,
    Func<TException1, bool> error1Predicate,
    Func<TException2, bool> error2Predicate) { /* ... */ }

public static IEnumerable<T> IgnoreErrors<T, TException1, TException2, TException3>(
    this IEnumerable<T> source,
    Func<TException1, bool> error1Predicate,
    Func<TException2, bool> error2Predicate,
    Func<TException3, bool> error2Predicate) { /* ... */ }
```

Why an action for `exceptionHandler`? It implies a side-effect, which should be avoided if it can be helped. What if the exception type is not good enough? The predicate-based signatures are open to more scenarios. For example, you have a [`WebException`](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webexception) and you want to filter further on its [`Status`](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webexception.status#System_Net_WebException_Status).

Both overloads you propose are hard to reason about when you look at the name of the method or what it's intended to do, which is _ignore errors_. The predicates-based overloads allow the user to say which errors should be ignored.

**Comment by leandromoh** [comment]
> Both overloads you propose are hard to reason about when you look at the name of the method or what it's intended to do, which is ignore errors. 

At this first moment I am not worried about the method name, but about its behavior. What I really want/need is a method that give to user the control of the situation. that is, give me all the available elements, and for those which could not be processed, tell me what happens. The second operator i suggest give me this.

> Why an action for exceptionHandler?

for the first overload I thought something like `Pipe`:

```c#
var availableElements= elements.Available(ex => 
{
   if (ex is WebException) // do something
   else if (ex is ArgumentException) // do something else
   //others types of excception ignore
}); 
```
However I think my second overload is the most powerfull, as the following example:

```c#
sequence
    .Available((item, exception) => new { item, exception })
    .ForEach((x, index) =>
    {
        if (x.exception == null)
            Console.WriteLine($"index {index} give me {x.item}");
        else
            Console.WriteLine($"index {index} throws an {x.exception.GetType().Name}");
    });
```

outputs:

```
index 0 give me 1
index 1 give me 2
index 2 give me 3
index 3 give me 4
index 4 throws an InvalidOperationException
index 5 give me 6
index 6 give me 7
index 7 give me 8
index 8 give me 9
index 9 throws an InvalidOperationException
```
if one is not worried about exceptions, they can be skipped simply.

``` c#
sequence
   .Available(ValueTuple.Create)
   .Where(x => x.Item2 == null)
   .Select(x => x.Item1);
```

**Comment by atifaziz** [comment]
> At this first moment I am not worried about the method name, but about its behavior. 

In API design, the method name can bring a lot clarity but about behavior. For example, whenever I've had a hard time coming up with a good name, I realize that the method is perhaps doing too much and needs to be broken down into smaller parts, each of which is then easier to name more meaningfully.

> However I think my second overload is the most "powerfull" and versatile, as the following example:

Your second overload? I think [you only proposed one for `Available`](https://github.com/morelinq/MoreLINQ/issues/405#issue-302102752). I'm confused now.

I'm convinced that what you're asking here too is accomplished simply by a simple filter (`Where`)
 over [`SelectWithError`](https://github.com/morelinq/MoreLINQ/issues/404#issuecomment-370362838) as I suggested in #404.

**Comment by leandromoh** [comment]
> In API design, the method name can bring a lot clarity but about behavior. For example, whenever I've had a hard time coming up with a good name, I realize that the method is perhaps doing too much and needs to be broken down into smaller parts, each of which is then easier to name more meaningfully.

I agree.

> Your second overload? I think you only proposed one for Available. I'm confused now.

[Here](https://github.com/morelinq/MoreLINQ/issues/405#issuecomment-370254705) is the second overload.

> I'm convinced that what you're asking here too is accomplished simply by a simple filter (Where)
> over SelectWithError as I suggested in #404.

 `SelectWithError` is great, but remember it uses `source.Select`, that is, there is not a `try catch` on the source's enumerator `MoveNext` call. So in my [example of usage](https://github.com/morelinq/MoreLINQ/issues/405#issue-302102752), it would break the enumeration. Also, beside the `Func<T, Exception, TResult>` selector, should have on without the `T` argument, since it could not be projected. Adding this two changes, I think we can deal with all error scenarios.

I would like submit a PR for this. What do you think?

**Comment by atifaziz** [comment]
> but remember it uses `source.Select`, that is, there is not a `try catch` on the source's enumerator `MoveNext` call

True but it was just a quick prototype. I was more concerned with API design and signature than implementation correctness at this stage.

> second overload:
>
>     public static IEnumerable<TResult> IgnoreErrors<TSource, TResult>(
>         this IEnumerable<TSource> source,
>         Func<TSource, Exception, TResult> selector)
>
> in the second signature, either a `TSource  `or `Exception `will be passed to `selector`. Never both at the same time.
>
> I would like submit a PR for this. What do you think?

I don't think we're ready with this yet and needs more discussion on the following items:

- The name does not match what it does; it's not just ignoring errors anymore
- It handles all exceptions; there's no way to say which ones should be ignored
- There should be separate selectors for the success and error case

**Comment by leandromoh** [comment]
What about this signature?

```c#
        public static IEnumerable<TResult> Available<TSource, TResult>(
            this IEnumerable<TSource> source,
            Func<TSource, TResult> elementSelector,
            Func<Exception, TResult> exceptionSelector,
            Func<Exception, bool> errorPredicate)
```

**Comment by leandromoh** [comment]
closed unintentionally.

**Comment by leandromoh** [comment]
@atifaziz What about this signature? I think it is okay with the [items you pointed.](https://github.com/morelinq/MoreLINQ/issues/405#issuecomment-370417474)

```c#
public static IEnumerable<TResult> Acquire<TSource, TResult>(this 
    IEnumerable<TSource> source,
    Func<TSource, TResult> elementSelector,
    Func<Exception, TResult> exceptionSelector,
    Func<Exception, bool> errorPredicate)
```
We can add the method that ignore errors as a new operator implemented based on the above.

```c#
public static IEnumerable<T> IgnoreErrors<T>(this IEnumerable<T> source)
{
    return source.Acquire(x => (Item: x, Error: (Exception) null),
                                        e => (Item: default(T), Error: e),
                                        e => false)
                 .Where(t => t.Error == null)
                 .Select(t => t.Item);
}

```

**Comment by leandromoh** [comment]
@atifaziz How about the above comment?

**Comment by atifaziz** [comment]
This is still unaddressed:

> - It handles all exceptions; there's no way to say which ones should be ignored

**Comment by leandromoh** [comment]
There's a [`predicate`](https://github.com/morelinq/MoreLINQ/issues/405#issuecomment-370748170) where user say which ones should throw.

**Comment by atifaziz** [comment]
Right, but I meant in terms of _exception types_, like [shown earlier](https://github.com/morelinq/MoreLINQ/issues/405#issuecomment-370264244):

```c#
public static IEnumerable<T> IgnoreErrors<T, TException1, TException2>(
    this IEnumerable<T> source,
    Func<TException1, bool> error1Predicate,
    Func<TException2, bool> error2Predicate)
    where TException1 : Exception
    where TException2 : Exception
    { /* ... */ }
```

So yes, while the predicate is there, your signature requires catching _any_ type of exception, which is something I believe should be avoided. If the predicate is just handed the base `Exception` type then down-casting will be required if the predicate depends on some value on a specific exception type (like [`WebException.Status`](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webexception.status?view=netcore-1.0#System_Net_WebException_Status) to illustrate one example). In the above case, each predicate will naturally deal with the exception type it is designed for.

**Comment by leandromoh** [comment]
I think maybe we can reach a consensus more easily if we separete the proposals. Let's discuss `IgnoreErrors` in another thread/issue and new `Acquire `overload in this one. The proposal `Acquire` overload are okay for you? or your previous comment applies to it too?

**Comment by atifaziz** [comment]
I thought they were one and the same, all stemming from discussion of the [original proposal](https://github.com/morelinq/MoreLINQ/issues/405#issue-302102752)? May be they are forks of different ideas? I'm confused where we are headed with this now. 😕

**Comment by leandromoh** [comment]
I am interested in the new `Acquire` overload proposed [here](https://github.com/morelinq/MoreLINQ/issues/405#issuecomment-380311636). `Acquire` permissive and `IgnoreErrors` and differents ideas. Let's discuss `Acquire` overload first,

**Comment by atifaziz** [comment]
Okay, the name needs some thought. Apart from that, I still find exceptions should be handled like proposed for `IgnoreErrors`.

**Comment by leandromoh** [comment]
> your signature requires catching any type of exception, which is something I believe should be avoided

why?

I think the order that exceptions will be catch is not obvious when we have a predicate for each exception type.

**Comment by atifaziz** [comment]
> why?

Forcing the practice of catch-all exceptions when it can be avoided.

> I also think the order that exceptions will be catch is not obvious when we have a predicate for each exception type.

It should be obvious that they are caught in order: `TException1`, `TException2`, etc. This would be no different than writing out the catch blocks yourself.

**Comment by leandromoh** [comment]
> It should be obvious that they are caught in order: TException1, TException2, etc. This would be no different than writing out the catch blocks yourself.

I see. We can add a remark for this.

> Forcing the practice of catch-all exceptions when it can be avoided.

Make sense. We can follow this way for me at all.

Any other point before I open the PR?

**Comment by atifaziz** [comment]
> Any other point before I open the PR @atifaziz ?

Name and signature, and I still can't say off the top of my head what this does. :grimacing:

**Comment by leandromoh** [comment]
I was thinking about operators design and thought this: 

1) the objective of the first proposed method (one we are calling as Acquire)  is *acquire unconditionally* all avaible elements of a sequence, even If some MoveNext throws. So API should be

```c#
static IEnumerable<TResult> Acquire<TSource, TResult>(this 
    IEnumerable<TSource> source,
    Func<TSource, TResult> elementSelector,
    Func<Exception, TResult> exceptionSelector)
```

2) the objective of the Second proposed method (one we are calling as IgnoreErrors)  is *ignore (some cases of) errors*. So API should be:

```c#
static IEnumerable<T> IgnoreErrors<T, TException1, TException2>(
    this IEnumerable<T> source,
    Func<TException1, bool> error1Predicate,
    Func<TException2, bool> error2Predicate)
    where TException1 : Exception
    where TException2 : Exception
    { /* ... */ }
```

Makes sense to you @atifaziz?

**Comment by leandromoh** [comment]
@atifaziz?

**Comment by leandromoh** [comment]
I see that Rambda library have a function bit similar to item 1, called TryCatch (which is a good name at all): https://bitsrc.io/bit/ramda/utils/try-catch?version=1.0.0

**Comment by atifaziz** [comment]
Closing on the assumption that #515 supersedes this.
