### ISSUE TITLE
FirstOrDefault for Value Types

### ISSUE THREAD

**Issue by myblindy** [morelinq/MoreLINQ#407]
With value tuples becoming more and more predominant, I've run into a couple of issues using them with Linq, in particular with the `*OrDefault` functions. 

I understand why the following works as it does, but it's useless for my needs (I dare say even useless in general):

```
var arr = new []{ (i: 1, j: 3), (i: 2, j: 4), (i: 0, j: 2) };
var res = arr.FirstOrDefault(w => w.i > 10);
Console.WriteLine(res.i);  // why is 0 being displayed when I'm asking for i > 10???
```

What I propose is the following:

```
        public static TValue? FirstOrDefaultValue<TValue>(this IEnumerable<TValue> source, Func<TValue, bool> predicate) where TValue : struct
        {
            using (var enumerator = source.GetEnumerator())
            {
                while (enumerator.MoveNext())
                    if (predicate == null || predicate(enumerator.Current))
                        return enumerator.Current;
                return null;
            }
        }

        public static TValue? FirstOrDefaultValue<TValue>(this IEnumerable<TValue> source) where TValue : struct => FirstOrDefaultValue(source, null);
```

This way you get a nullable value returned if nothing matched the predicate (or if the sequence is empty), letting you test without making silly assumptions. It also works really well with the `?.` operator: 

```
var res = arr.FirstOrDefaultValue(w => w.i > 10)?.i;  // res is of type int?
```

Thoughts?

**Comment by leandromoh** [comment]
Why Dont use Cast before FirstOrDefault?

var res = arr.Cast<(int, int)?>().FirstOrDefault(w => w.i > 10)?.i;  // res is of type int?

**Comment by atifaziz** [comment]
@myblindy Like @leandromoh already pointed out, you could use `Cast` though the code would be more like:

```c#
var res = arr.Where(w => w.i > 10).Cast<(int i, int)?>().FirstOrDefault()?.i
```

Another way to go about it is to put the default via [`DefaultIfEmpty`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.defaultifempty):

```c#
var res = arr.Where(w => w.i > 10).DefaultIfEmpty((-1, -1)).First();
```

They also work with `Last`, `Single` and other such methods.

**Comment by myblindy** [comment]
> Why Dont use Cast before FirstOrDefault?

True, it would also work, but it wouldn't be semantically clear what you're doing. I mean that's the purpose of Linq, right? To see at a glance what your code is trying to do -- otherwise you can implement all of it with a bunch of `foreach` and `if` statements.

> `DefaultIfEmpty((-1, -1))`

That however still requires hard coded assumptions about your collection, which will bite you in the ass years down the line when you decide -1 is also a valid value.

**Comment by atifaziz** [comment]
>> `DefaultIfEmpty((-1, -1))`
>
> That however still requires hard coded assumptions about your collection, which will bite you in the ass years down the line when you decide -1 is also a valid value.

That was just for illustration (of how to go using an alternative value as a default) and not advocating a practice. With using the null value as the default, it would look as follows:

```c#
var res = arr.Where(w => w.i > 10).Cast<(int i, int)?>().FirstOrDefault()?.i;
```

**Comment by fsateler** [comment]
I think that adding an overload named FirstOrDefault is simply not feasible. It would conflict with the standard LINQ operator. However, I do agree it is sometimes annoying that an explicit cast is necessary, which can make the code unnecessarily verbose (especially if the tuple is of high arity). Moreover, sometimes it is impossible without involving a third method (if anonymous types are part of the tuple).

I think a more feasible option would be to provide a `CastNullable` operator:

```csharp
public static IEnumerable<T?> CastNullable<T>(this IEnumerable<T> src) where T : struct
     => src.Cast<T?>();
```
I'm not quite happy with the name but at least it describes what the method does. OTOH, the triviality of this method makes me question if it is really necessary to provide in MoreLINQ.

**Comment by atifaziz** [comment]
> I'm not quite happy with the name

`AsNullable()`?

> OTOH, the triviality of this method makes me question if it is really necessary to provide in MoreLINQ.

I agree.

**Comment by atifaziz** [comment]
@myblindy I would recommend looking at [Optuple] for a solution for this where in version [2.1.0], I introduced `FirstOrNone`, `LastOrNone` and `SingleOrNone` in the `Optuple.Collections` namespace.

You would then write your code as follows:

```c#
// assume:
// using Optuple;
// using Optuple.Collections;
var arr = new []{ (i: 1, j: 3), (i: 2, j: 4), (i: 0, j: 2) };
var res = arr.Where(w => w.i > 10).FirstOrNone();
Console.WriteLine(res.ToNullable());  // displays null when there's no result
```

Using Optuple will give you other benefits of dealing with the idea of a missing value more elegantly (and supports convert to and from nullable value types). For example, you could rewrite the above with `Do`:

```c#
var arr = new []{ (i: 1, j: 3), (i: 2, j: 4), (i: 0, j: 2) };
arr.Where(w => w.i > 10)
   .FirstOrNone()
   .Do(res => Console.WriteLine(res.i));
```

If you don't like `Do`, you can just use a regular `if` with pattern-matching to the same effect:

```c#
var arr = new []{ (i: 1, j: 3), (i: 2, j: 4), (i: 0, j: 2) };
if (arr.Where(w => w.i > 10).FirstOrNone() is (true, var res))
    Console.WriteLine(res.i);
```

I'm going to close this for MoreLINQ to avoid overlap.

[Optuple]: https://github.com/atifaziz/Optuple
[2.1.0]: https://github.com/atifaziz/Optuple/releases/tag/v2.1.0
