### ISSUE TITLE
AddRange for collection types

### ISSUE THREAD

**Issue by myblindy** [morelinq/MoreLINQ#408]
There are many collection types that don't have an `AddRange` function, which has always struck me as silly since most of the time all it does it simply iterate over an enumerable and call `Add` for each item. `HashSet<T>` is one of these collections classes.

There are also collections that only provide an `AddRange` over an array, instead of an enumerable, forcing me to materialize my otherwise lightweight queries (even lists for that matter). `StringCollection` is one such collection class.

What I propose is this:
```
        public static void AddRange<T>(this ICollection<T> source, IEnumerable<T> items)
        {
            foreach (var item in items)
                source.Add(item);
        }
```

Very simple, clear and, at least in my experience, useful. The compiler will use the collection's own `AddRange` method if it exists (and takes the proper type, ie an enumerable if an enumerable is given), otherwise this extension method kicks in and does what you'd expect.

**Comment by atifaziz** [comment]
> There are many collection types that don't have an `AddRange` function

MoreLINQ is primarily a library of extensions/operators for sequences (`IEnumerable<T>`) or methods that help in generating them. An extension for collection types would therefore be out of scope. That said, you can already add to any collection using our [`ForEach`][ForEach], e.g.:

```c#
var list = new List<(int, int)>();

Enumerable
    .Range(1, 10)
    .Select(x => (x, x * 2))
    .ForEach(list.Add);

var set = new HashSet<int>();
ICollection<int> collection = set;

MoreEnumerable
    .Random(10)
    .Take(20)  
    .ForEach(collection.Add);
```

> The compiler will use the collection's own `AddRange` method if it exists (and takes the proper type, ie an enumerable if an enumerable is given), otherwise this extension method kicks in and does what you'd expect.

Admittedly, this won't happen with `ForEach`.

I believe that collection types providing an `AddRange` do so for optimising bulk insertion, e.g. to avoid lots memory moves in case the backing storage is an array.

[ForEach]: http://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_ForEach.htm

**Comment by myblindy** [comment]
> I believe that collection types providing an AddRange do so for optimising bulk insertion, e.g. to avoid lots memory moves in case the backing storage is an array.

Sure, but it also doubles as a nice semantic one liner to add items in bulk even if it can't really be optimized for bulk inserts (again, `HashSet<T>`). `ForEach()` doesn't make it semantically clear you're just trying to add items in bulk, and it involves an additional delegate to boot.

**Comment by atifaziz** [comment]
The real trouble is that extending collection types is not in the scope of this library. There's nothing LINQ-y about `AddRange`; it cannot be composed with a query except via a materialization of a query's result into a collection. One could consider the following by swapping the arguments and extending `IEnumerable<T>` instead:

```c#
public static void AddTo<T>(this IEnumerable<T> source, ICollection<T> target) =>
    source.ForEach(target.Add);
```

but it doesn't stand to benefit from an optimised `AddRange` on the target collection.

**Comment by atifaziz** [comment]
Closing this on the basis that it's out of scope; that is, unrelated to LINQ.
