### ISSUE TITLE
Shuffle is missing

### ISSUE THREAD

**Issue by MkazemAkhgary** [morelinq/MoreLINQ#409]
I think this method is missing and wait before suggesting the following alternative. let me explain by showing downsides and upsides of each.

     private static readonly Random _rng = new Random();
     // ...
     sequence = sequence.OrderBy(_ => _rng.Next());

versus

     sequence = sequence.Shuffle();

downsides of using orderby.

 - It requires additional field for the random generator.
 - Its more verbose and less descriptive.
 - Its probably not the best way. https://stackoverflow.com/a/1287572/4767498

upsides of having a shuffle method.

 - Its simple, less verbose and descriptive.
 - It encourages to use the right method for the right job.
 - Its faster.

just to make this point clear. Yes, I can absolutely go and use the existing implementations, like the one jon skeet provided. I just thought It would be a good addition to MoreLinq. because randomizing a sequence is something every one does at some point. for testing or in a part of an actual problem. 

on the other hand it doesn't need hard documentation, and is fairly simple. an state of the art implementation could be used, and developers wouldn't get involved in it too much and would just enjoy it.

**Comment by atifaziz** [comment]
[`RandomSubset`](http://morelinq.github.io/2.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_RandomSubset.htm)?

**Comment by MkazemAkhgary** [comment]
right, terrible name by the way 😄
