### ISSUE TITLE
Why is a local function required when it is only called once? (e.g. DistinctBy)

### ISSUE THREAD

**Issue by straubie** [morelinq/MoreLINQ#412]
I saw this commit adding a local function:

https://github.com/morelinq/MoreLINQ/commit/8fbb540fd140b6d0008120c37abd00e129203cc6#diff-732fe70a48ba9ee614573938ea001d6f

My question is why is the local function needed at all? Or better why was the "DistinctByImpl" before that needed? Why not just leave those out and execute the code just in the "DistinctBy" method? Asking this out of curiosity...

**Comment by leandromoh** [comment]
To separate de scope between  lazy and eager evaluation. The session "Use Case 1: eager preconditions in iterator blocks" of this [link ](https://blogs.msdn.microsoft.com/seteplia/2017/10/03/dissecting-the-local-functions-in-c-7/) explains better.

**Comment by atifaziz** [comment]
See also the explanation in the [“Local functions and exceptions”](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions#local-functions-and-exceptions) section of the C# documentation on [local functions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions):

> One of the useful features of local functions is that they can allow exceptions to surface immediately. For method iterators, exceptions are surfaced only when the returned sequence is enumerated, and not when the iterator is retrieved.
