### ISSUE TITLE
Flatten (overload) via property of an object

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#413]
How about to add the following overload to Flatten?

```c#
public static IEnumerable<object> Flatten(
     this IEnumerable source, 
     Func<object, IEnumerable> selector)
```

As suggested [here](https://github.com/morelinq/MoreLINQ/pull/357#discussion_r144713341).

**Comment by atifaziz** [comment]
In a comment on PR #357, [you said](https://github.com/morelinq/MoreLINQ/pull/357#issuecomment-353908342):

> I dont like too much about the idea of return `null `to indicate `predicate `(as you said, it is not an obvious signature). 
>
> How about maintain `predicate` and `selector `separated but put `selector `as `Func<object, IEnumerable>`?

Have you changed your mind about this?

**Comment by leandromoh** [comment]
Sorry, I expressed myself poorly. My interest is flattening via property. 

About to use predicate and selector combined or separated is something that I would like to discuss about, the benefits and disadvantages of each approach.

**Comment by leandromoh** [comment]
@atifaziz I was thinking and 2 overloads, in fact, are very similar. 

1. `Func<object, IEnumerable> selector`
2. `Func<object, IEnumerable> selector + Func<IEnumerable, bool> predicate`

In my branch of experiments of flatten, I noticed we can create overload 2 in terms of overload 1, as I did [here](https://github.com/leandromoh/MoreLINQ/blob/c8b418a295621845372a8548c140d62e11431e67/MoreLinq/Flatten.cs#L88). I made tests for both overloasd for the same problem, to see the differences of usage.

test 1: FlattenSelector
[overload 1](https://github.com/leandromoh/MoreLINQ/blob/c8b418a295621845372a8548c140d62e11431e67/MoreLinq.Test/FlattenTest.cs#L268) / [overload 2](https://github.com/leandromoh/MoreLINQ/blob/c8b418a295621845372a8548c140d62e11431e67/MoreLinq.Test/FlattenTest.cs#L360)

test 2: FlattenSelectorFilteringOnlyIntegers
[overload 1](https://github.com/leandromoh/MoreLINQ/blob/c8b418a295621845372a8548c140d62e11431e67/MoreLinq.Test/FlattenTest.cs#L312) / [overload 2](https://github.com/leandromoh/MoreLINQ/blob/c8b418a295621845372a8548c140d62e11431e67/MoreLinq.Test/FlattenTest.cs#L400).

I ask me if we should add the 2 overloads. What do you think @atifaziz  @fsateler ?
