### ISSUE TITLE
FullGroupJoin isn't drop-in compatible with LINQ's GroupJoin

### ISSUE THREAD

**Issue by fowl2** [morelinq/MoreLINQ#419]
It's pretty easy to implement:

```c#
public static IEnumerable<TResult> FullGroupJoin<TFirst, TSecond, TKey, TResult>(this IEnumerable<TFirst> first,
    IEnumerable<TSecond> second,
    Func<TFirst, TKey> firstKeySelector,
    Func<TSecond, TKey> secondKeySelector,
    Func<TFirst, IEnumerable<TSecond>, TResult> resultSelector,
    IEqualityComparer<TKey> comparer)
{
    return first.FullGroupJoin(second, firstKeySelector, secondKeySelector,
        (_, firstItems, secondItems) => from fi in firstItems.DefaultIfEmpty()
                                      select resultSelector(fi, secondItems)
        , comparer)
        .SelectMany(e => e);
    
}
```

But unless we find a new name it causes overload ambiguity. :/

**Comment by atifaziz** [comment]
This will give you unexpected, even incorrect, results because the `resultSelector` will receive a `default(TFirst)` for every key in `second` that's not present in `first`. The signature of `resultSelector` also claims that `TFirst` will always exist, which is misleading at best.

/cc @fsateler

**Comment by fowl2** [comment]
@atifaziz I think that would be the intention of a switching to full join - to get access to items form the second collection that don't match the first. 

You're right, an unexpected `default(TFirst)` isn't great though I'm not sure what other option there is and that might (probably) not outweigh any benefit.

**Comment by fowl2** [comment]
I mean to say

> to _**additionally**_ get access to items from the second collection that don't match the first.

**Comment by atifaziz** [comment]
> I mean to say to _**additionally**_ get access to items from the second collection that don't match the first.

In that case you have `FullGroupJoin` as well as [`FullJoin`](http://morelinq.github.io/2.8/ref/api/html/Overload_MoreLinq_MoreEnumerable_FullJoin.htm). The goal of `FullGroupJoin` is not to be a drop-in replacement for `GroupJoin` but to have a signature that makes most sense in the context of its operation, especially in terms of correctness of results.

> You're right, an unexpected `default(TFirst)` isn't great though I'm not sure what other option there is and that might (probably) not outweigh any benefit.

I'm going to close this issue for now but happy to re-open if you find a way out.
