### ISSUE TITLE
Refactor tests using ArrangeCollectionTestCases to expanded cases

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#445]
@leandromoh Can you refactor tests using `ArrangeCollectionTestCases` to use [the technique](https://github.com/morelinq/MoreLINQ/pull/424#issuecomment-380704132) demonstrated in PR #424? The idea would be to expand the test cases to be more explicit instead of looping internally.

**Comment by Arithmomaniac** [comment]
I'm working on this one right now.

**Comment by leandromoh** [comment]
@atifaziz Sorry, I forgot about It. Too busy.

**Comment by atifaziz** [comment]
@Arithmomaniac Thanks!

@leandromoh No worries.
