### ISSUE TITLE
SkipLastWhere suggested function

### ISSUE THREAD

**Issue by myblindy** [morelinq/MoreLINQ#454]
Perhaps not the best name, but I recently found myself in need to skip trailing elements that match a certain condition, while keeping all non-trailing elements that match the same condition. Something like this:

```c#
	var arr = new[] { 1, 2, 3, 1, 5, 1, 1, 2, 3, 1, 1 };
	arr.SkipLastWhere(w => w == 1).Dump();
        // returns 1, 2, 3, 1, 5, 1, 1, 2, 3
        // but no 1, 1 at the end
```

This is my implementation:

```c#
public static class Extensions
{
	public static IEnumerable<T> SkipLastWhere<T>(this IEnumerable<T> source, Func<T, bool> test)
	{
	    List<T> potentials = null;
	
	    foreach (var item in source)
	        if (test(item))
	        {
	            if (potentials == null) potentials = new List<T>();
	            potentials.Add(item);
	        }
	        else
	        {
	            // yield the list of potentials if any, and then clear it
	            if ((potentials?.Count ?? 0) > 0)
	            {
	                foreach (var potentialitem in potentials)
	                    yield return potentialitem;
	                potentials.Clear();
	            }
	
	            // and yield the current item
	            yield return item;
	        }
	}
}
```

In the trivial case where the condition is always false, the list isn't even created. The source is only iterated once, and, if created, the potentials list is also iterated only once, except at the end when the elements inside are quietly dropped.

Let me know what you think!

**Comment by atifaziz** [comment]
You can achieve this today, albeit in a cumbersome way, with the combination of [`Concat`][Concat], [`GroupAdjacent`][GroupAdjacent] and [`SkipLast`][SkipLast]:

```c#
var arr = new[] { 1, 2, 3, 1, 5, 1, 1, 2, 3, 1, 1 };
const int sentinel = 1;
Console.WriteLine(
    arr.Concat(sentinel)
       .GroupAdjacent(w => w == sentinel)
       .SkipLast(1)
       .SelectMany(g => g)
       .ToDelimitedString(", "));
```


[SkipLast]: https://morelinq.github.io/2.2/ref/api/html/M_MoreLinq_MoreEnumerable_SkipLast__1.htm
[GroupAdjacent]: https://morelinq.github.io/1.x/ref/api/html/Overload_MoreLinq_MoreEnumerable_GroupAdjacent.htm
[Concat]: https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Concat__1.htm

**Comment by atifaziz** [comment]
> albeit in a cumbersome way

@myblindy I should add that cumbersome is somewhat relative. :wink: LINQ operators were designed to be combined to achieve a desired effect. Sometimes the sum of combinations can cause intent to be lost in noise but it's somewhat an inherent part of the game and so there's a balance to be struck. I'd like to think it's a science but seems more of an art. If skipping the last group of a sentinel is rare then [the combination I showed above](https://github.com/morelinq/MoreLINQ/issues/454#issuecomment-382115277) should be acceptable to introducing a whole new extension that needs implementing, testing, documenting and maintaining. It is also _marginally_ less efficient (by a practical measure) than your implementation (your `potentials` is the grouping of adjacent elements). That's all to say that while it might seem cumbersome, it's “good enough.”

**Comment by myblindy** [comment]
I'll admit I hadn't considered that combination to achieve the same. You're right, it's probably good enough for most cases.

As a side note, glancing over `GroupAdjacent` shows that you're always creating a new list every time the test condition is true instead of clearing the list if it already exists (like in my implementation). The rest of the code is surprisingly similar, and doing this little change would potentially put less stress on the garbage collector.

**Comment by atifaziz** [comment]
> it's probably good enough for most cases.

Thanks! I'll close this issue on that basis.

As for you note about creating lists and GC pressure, you can afford to clear and re-use `potentials` because it is an internal state of your implementation. `GroupAdjacent` on the other hand yields the group (the list) itself and so cannot clear and re-use its memory (unless it was flattening internally as you do). The list is an element of the result sequence returned by `GroupAdjacent`. Depending on how long you hold on to that list, it will become GC fodder within, hopefully, generation 0.
