### ISSUE TITLE
Backsert: insert a sequence from the back of another

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#456]
Similar to [Insert operator](https://github.com/morelinq/MoreLINQ/issues/306) (same signature) but the position where `second` will be inserted at `first` is count from end to start. That is, 

- 0 means last position, 
- 1 means second-last position, 
- 2 means third-last position
- etc

## Signature:
```c#
IEnumerable<T> InsertEnd<T>(this IEnumerable<T> first, IEnumerable<T> second, int index)
```

## Example:

```c#
[1,2].InsertEnd([3,4], -1); // ArgumentOutOfRangeException when index < 0
[1,2].InsertEnd([3,4], 0); // [1,2,3,4]
[1,2].InsertEnd([3,4], 1); // [1,3,4,2]
[1,2].InsertEnd([3,4], 2); // [3,4,1,2]
[1,2].InsertEnd([3,4], 3); // ArgumentOutOfRangeException when index > first.Count()
```

## workaround

```c#
first.SkipLast(index).Concat(second).Concat(first.TakeLast(index))
```

produces the same as 

```c#
first.InsertEnd(second, index)
```

except for exception cases with `index` parameter

## Motivation

1. `InsertEnd` iterates `first` once, 
2. performance, since workaround iterates `first` 2 times and uses 2 buffers (`SkipLast` + `TakeLast`)
3. `Insert` operator symmetry
4. more readable, workaround does not capture the intention as clearly as `InsertEnd`

**Comment by atifaziz** [comment]
Interesting. 💭 Let me propose something a little more general first because I am seeing a pattern that's common among this and several other operators that we already have.

**Comment by atifaziz** [comment]
> Let me propose something a little more general first

@leandromoh See #458. Here's an implementation of `InsertEnd` in terms of `CountDown`:

```c#
public static IEnumerable<T> InsertEnd<T>(this IEnumerable<T> first,
    int count, IEnumerable<T> second) =>
    from seq in
        first.Index()
             .Select(e => (Index: e.Key, Element: Enumerable.Repeat(e.Value, 1)))
             .CountDown(count + 1, (e, cd) => 
                 cd < count && e.Index == 0
                 ? second.Concat(e.Element)
                 : e.Element.Concat(cd == count ? second : Enumerable.Empty<T>()))
    from e in seq
    select e;
```

Thoughts?

**Comment by atifaziz** [comment]
> I really can not understand your implementation =(

Annotated version:

```c#
public static IEnumerable<T> InsertEnd<T>(this IEnumerable<T> first,
    int count, IEnumerable<T> second) =>
    from seq in
        first.Index() // index or count-up
             // convert each element into a sequence, keeping the index
             .Select(e => (Index: e.Key, Element: Enumerable.Repeat(e.Value, 1)))
             .CountDown(count + 1, (e, cd) => 
                 cd < count && e.Index == 0 // do we need to insert before?
                 ? second.Concat(e.Element) // yes: so second comes before head element
                                            // no : insert when count-down == count + 1
                 : e.Element.Concat(cd == count ? second : Enumerable.Empty<T>()))
    from e in seq
    select e;
```

Hope it's clearer?

**Comment by leandromoh** [comment]
Ok. I Will do as soon as I can.
About your proposed name (Backsert), I think It is not obvious enough, since you had to explain that (backward + insert). I think is better mantain consistence about the pattern used

**Comment by leandromoh** [comment]
Close by mistake

**Comment by atifaziz** [comment]
>> It would be helpful for others (and future visitors) to provide a little more detail
>
> done.

Awesome job! 🎖 Thanks!

> I think better options are add the suffix "End" or "Back".

In English:

- `InsertBack` sounds like you're inserting back something that was once removed, as in “put back”.
- `InsertEnd` doesn't make much sense but if someone were to take a guess, they would image it _only_ inserts at the end and therefore could be confused with `Concat` or `Append`.

What it really does is insert _from_ the back or end but instead of introducing _from_ in the name, as in `InsertFromBack`, the next best thing seems to be to get creative; thus the proposal of `Backsert`. I took inspiration from [_upsert_](https://en.wiktionary.org/wiki/upsert), which is often used to mean _update or insert_.

> I think It is not obvious enough, since you had to explain that 

I understand so perhaps we can make a reference from the `Insert` documentation.

Another reason for proposing `Backsert` is if we ever want to add `BacksertOrPrepend`, which would prepend the second sequence if the offset identifies a position beyond the head of the first sequence.

**Comment by leandromoh** [comment]
@atifaziz I would like to define the operator name to go ahead with the implementation.

**Comment by atifaziz** [comment]
Go ahead with the PR if you're okay with the name `Backsert`. I'll take all the blame and heat for it. 😆

**Comment by leandromoh** [comment]
@atifaziz I can go with `Backsert` but how you about `BackInsert` ? Looks me a bit more expressive.

**Comment by atifaziz** [comment]
> but how you about `BackInsert` ? Looks me a bit more expressive.

I thought about it; quite a bit, in fact. English-wise, it's not any more expressive than `Backsert` so being a little creative doesn't look like it's going to hurt. I see the name as a [portmanteau](https://en.wikipedia.org/wiki/Portmanteau), like _upsert_, and [portmanteaus in computing](https://en.wikipedia.org/wiki/List_of_portmanteaus#Internet_and_computing) are more common than one might think. We will have time to debate this before the PR is merged. I wish there was a larger community here to chime in and vote but for now it's just you and me. 😜

**Comment by leandromoh** [comment]
I see, you convinced me. Let's go as `Backsert` then.
