### ISSUE TITLE
Clarify FillForward/Backward fill function arg order in docs

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#485]
The documentation for the `fillerSelector` argument of [`FillForward`][FillForward] doesn't talk about the order of its arguments:

> _`fillSelector`_
> Type: `System.Func<T, T, T>`
> The function used to produce the element that will replace the missing one. It receives the previous non-missing element as well as the current element considered missing.

This can leave someone guessing wrongly from just the signature `System.Func<T, T, T>`. It would help to clarify

> The function used to produce the element that will replace the missing one. It receives the current element considered missing as the first argument and the previous non-missing element as the second argument.

Likewise for [`FillBackward`][FillBackward]:

> _`fillSelector`_
> Type: `System.Func<T, T, T>`
> The function used to produce the element that will replace the missing one. It receives the next non-missing element as well as the current element considered missing.

/cc @PhilippeRaemy

[FillForward]: https://morelinq.github.io/2.10/ref/api/html/M_MoreLinq_MoreEnumerable_FillForward__1_2.htm
[FillBackward]: https://morelinq.github.io/2.10/ref/api/html/M_MoreLinq_MoreEnumerable_FillBackward__1_2.htm

**Comment by PhilippeRaemy** [comment]
Thanks, the new doc text will be helpful.
