### ISSUE TITLE
Strong-typed 3D+ heterogenous Cartesian

### ISSUE THREAD

**Issue by Arithmomaniac** [morelinq/MoreLINQ#491]
`Cartesian` only supports up to two arguments. It would be nice to be able to to for three or more items, all the way up to

```csharp
Cartesion<T1, T2, ..., T16, TReturn>(
   T1 object1, T2 object2, ..., T16 object16,
   Func<T1, T2, ..., T16, TReturn> resultSelector)
```

It should be possible to automate this process by generating the methods, similar to what is done for `Fold`.

(Migrated from discussions in #338. A superset of #488.)

**Comment by Arithmomaniac** [comment]
Volunteering for this one.

**Comment by atifaziz** [comment]
16D Cartesian sounds excessive. Shall we limit to 8 dimensions and expand if someone ever comes yelling & needing more? I know it's the exact same effort when the code is generated but just challenging the YAGNI argument here. And before I get challenged back for why 16 for `Fold` then I'll say up front that there even an arity of 16 isn't enough there. The use case for the two is different. There are way, way more chances of finding 16 elements or more in a sequence than 16 sequences!

**Comment by Arithmomaniac** [comment]
This is not quite done - the README needs to be updated.
