### ISSUE TITLE
Drop Concat overload extending a single element

### ISSUE THREAD

**Issue by leandromoh** [morelinq/MoreLINQ#494]
how about rename `Concat `to `Append `in the signature` Concat<T>(this IEnumerable<T> head, T tail)` and drop signature `Concat<T>(this T head, IEnumerable<T> tail)` ?

I know it is a breaking-change, but release 3.0 is a good opportunity.

This have the following pros:

- if we have `prepend`, make a lot o sense have `append`.
- avoid confusion between our `Concat `and Linq's one
- avoid extensions methods for `T`

**Comment by atifaziz** [comment]
You are raising two unrelated issues:

1. Rename `Concat `to `Append `in the signature` Concat<T>(this IEnumerable<T> head, T tail)`
2. Drop signature `Concat<T>(this T head, IEnumerable<T> tail)` 

Taking your original and opening subject line of “Drop Concat”, I'm going to only talk about point 2 here. If you want to discuss point 1 then let's take it up in a separately logged issue.

I agree with your suggestion to drop `Concat<T>(this T head, IEnumerable<T> tail)` on the basis of avoiding extension methods on non-enumerable types and 3.0 seems like a good time to do that.

The workaround is to use [`Prepend`][Prepend], which is what is doing in the single-line and simple implementation that is `Concat<T>(this T head, IEnumerable<T> tail)`:

```c#
public static IEnumerable<T> Concat<T>(this T head, IEnumerable<T> tail) => tail.Prepend(head);
```


[Prepend]: https://morelinq.github.io/2.10/ref/api/html/M_MoreLinq_MoreEnumerable_Prepend__1.htm
