### ISSUE TITLE
MinBy functionality changed by the latest updates

### ISSUE THREAD

**Issue by newmediadev** [morelinq/MoreLINQ#524]
Where:

`conditions.MinBy(x => Math.Abs((decimal)x - value))
`
used to work, it no longer does. The code has to be changed to:

conditions.MinBy(x => Math.Abs((decimal)x - value)).First()

Whilst this is a minor change on our part to add .First() to these uses of MoreLINQ, where there's a lot of code depending on these methods it's going to require people to change a lot of their code base.

**Comment by leandromoh** [comment]
@newmediadev this was a planned change for the 3.0 major release. See for background: https://github.com/morelinq/MoreLINQ/issues/328

**Comment by atifaziz** [comment]
That's correct and this was tagged as a breaking change for release 3.0. See #44.

Release 3.0 was a _major update_ after around 18 months and was the only chance to make a breaking change. Even so, care was taken not to introduce a breaking change if it wasn't absolutely needed.

Perhaps a workaround is to introduce a local `MaxBy` extension that maintains compatibility with your code base?

I'm curious, if you use Visual Studios **Find All References** on `MaxBy`, how many uses to you have across your code base. Is it in the hundreds?

**Comment by atifaziz** [comment]
Meanwhile, I'm going to close this as by-design.

What we can discuss is promoting this as a “compatibility layer” issue that would be [up-for-grabs](https://github.com/morelinq/MoreLINQ/issues?utf8=%E2%9C%93&q=label%3A%22help+wanted%22+), which can take one of two forms:

- A separate package that, called `MoreLinq3.Compatibility` as an example, that depends on MoreLINQ 3 and provides backward compatibility for code bases that may want to switch over slowly.
- A Roslyn analyzer that highlights and even provides fixes for areas of breaking compatibility.
