### ISSUE TITLE
CountBy does not work with null keys

### ISSUE THREAD

**Issue by sm-g** [morelinq/MoreLINQ#536]
`new string[] { "a", null, "a", null }.CountBy(x=>x)`

expected:
"a" - 2,
null - 2

Why I need it to work with nulls: to do `source.CountBy(x=>x).All(x => x.Value == 1)` instead of `source.GrounBy(x=>x).Count() == source.Count()`.

**Comment by atifaziz** [comment]
@sm-g Thanks for reporting this and `CountBy` should be fixed to work with `null`. The current implementation throws `ArgumentNullException` with the message, “Value cannot be null.Parameter name: key”, which is really being thrown by [`Dictionary<>.TryGetValue`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue):

https://github.com/morelinq/MoreLINQ/blob/47d6088b1b1ef15166fa7ba1206baa6fd2a0d7de/MoreLinq/CountBy.cs#L96

**Comment by jakubmaguza** [comment]
I was thinking about solution for this problem. I found out 2 ways of dealing with it:
1. Just throw an exception when item is null or..
2. Create custom Dictionary type where null value will be welcomed as a Key.

The 2nd. solution will be much better, as OP mentioned. There is an implementation of NullableDictionary in nHibernate project. It for sure could be milestone, as maybe some other methods of MoreLinq will need to handle nulls as keys. I could try to prepare pull request if you want to, but feel free to do it yourself.

**Comment by atifaziz** [comment]
Or we can special-case `null` without too much effort. 💭

**Comment by jakubmaguza** [comment]
I will be happy to see how this will be done :)
