### ISSUE TITLE
Add deconstruction of sequence types

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#538]
Consider adding extensions like the following:

```c#
public static void Deconstruct<T>(this IEnumerable<T> source, out T item1, out T item2)
{
    using (var e = source.GetEnumerator())
    {
        var more = true;
        item1 = more && (more = e.MoveNext()) ? e.Current : default;
        item2 = more && (more = e.MoveNext()) ? e.Current : default;
    }
}

public static void Deconstruct<T>(this IEnumerable<T> source, out T item1, out T item2, out T item3)
{
    using (var e = source.GetEnumerator())
    {
        var more = true;
        item1 = more && (more = e.MoveNext()) ? e.Current : default;
        item2 = more && (more = e.MoveNext()) ? e.Current : default;
        item3 = more && (more = e.MoveNext()) ? e.Current : default;
    }
}
```

that would enable that would enable deconstruction of sequence, e.g.:

```c#
var (x, y) = new[] { 123, 456 };
var (a, b, c) = "foobar";
var (name, value) = "foo=bar".Split('=', 2); 
```

For more background, see [“Deconstructing a user-defined type with an extension method”](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct#deconstructing-a-user-defined-type-with-an-extension-method).

There should be overloads of `Deconstruct` to allow deconstruction of up to first 16 elements of a sequence.

These extensions should be _exclusively_ defined in a new namespace called `MoreLinq.Deconstruction` so that they have to be imported _explicitly_. They do not need to made available in the `MoreLinq.Extensions` namespace that designed to avoid conflict in extensions.

Deconstruction shouldn't throw exceptions if the sequence is too short.

**Comment by fsateler** [comment]
I think this is a nice idea, but unfortunately, I think this:

> Deconstruction shouldn't throw exceptions if the sequence is too short

Might be the wrong choice. I'm not going to argue that the choice is per-se wrong, but that it depends on the context. Thus, I wonder if enumerable deconstruction is not general enough to fit in such a general library as MoreLINQ.

**Comment by atifaziz** [comment]
So if you want to ensure it's not too short then you can use `Pad`. If you want to ensure it's exactly the expected amount then you have [`AssertCount`](https://morelinq.github.io/3.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_AssertCount.htm). You can combine with either before deconstructing to get the desired effect. I'm open to debating being strict by default, like [`Fold`](https://morelinq.github.io/3.0/ref/api/html/Overload_MoreLinq_MoreEnumerable_Fold.htm) is.

> I wonder if enumerable deconstruction is not general enough to fit in such a general library as MoreLINQ.

You mean it's too general or not enough (wasn't sure which you meant) to belong in MoreLINQ? Not LINQ-ish enough? I do agree the use of deconstruction would be limited to termination.

**Comment by atifaziz** [comment]
@fsateler A stricter API design would have looked like this:

```c#
struct ExpectationOf2<T> : IEnumerable<T>
{
    readonly IEnumerable<T> _source;

    public ExpectationOf2(IEnumerable<T> source) =>
        _source = source;

    public void Deconstruct(out T item1, out T item2)
    {
        if (_source == null)
            throw new InvalidOperationException();

        using (var e = _source.GetEnumerator())
        {
            item1 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
            item2 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
            if (e.MoveNext())
                throw new Exception("Sequence too long.");
        }
    }

    public IEnumerator<T> GetEnumerator()
    {
        var (item1, item2) = this;
        yield return item1;
        yield return item2;
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

Then you'd have this as an extension method:

```c#
public static ExpectationOf2<T> Expect2<T>(this IEnumerable<T> source) =>
    new ExpectationOf2<T>(source);
```

But then the following reads odd, no?

```c#
var (x, y) = new[] { 123, 456 }.Expect2();
var (a, b, c) = "foobar".Expect3(); // assuming Expect3 is defined, this will throw
var (name, value) = "foo=bar".Split(new[] { '=' }, 2).Expect2();
```

You'd be forced to go over some `ExpectN` to be able to deconstruct. It does have the benefit that you can't change the left hand assignment without changing to the corresponding right version of `ExpectN` without breaking the code at compile-time.

We can also flip it such that the default deconstruction is strict and if you want the relaxed version then you compose with `TakeN`:

```c#
public static ReadingOf2<T> Take2<T>(this IEnumerable<T> source) =>
    new ReadingOf2<T>(source);
```

where `ReadingOf2<T>` would be defined as:

```c#
struct ReadingOf2<T> : IEnumerable<T>
{
    readonly IEnumerable<T> _source;

    public ReadingOf2(IEnumerable<T> source) =>
        _source = source;

    public void Deconstruct(out T item1, out T item2)
    {
        if (_source == null)
            throw new InvalidOperationException();

        using (var e = _source.GetEnumerator())
        {
            var more = true;
            item1 = more && (more = e.MoveNext()) ? e.Current : default;
            item2 = more && (more = e.MoveNext()) ? e.Current : default;
        }
    }

    public IEnumerator<T> GetEnumerator() => _source.Take(2).GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

Anyway, I thought I'd throw this out for sake of being completeness.

**Comment by fsateler** [comment]
> You mean it's too general or not enough (wasn't sure which you meant) to belong in MoreLINQ?

I meant that the extension method would not be general enough, in that "the general case" is supported because there is no such general case.

> I do agree the use of deconstruction would be limited to termination.

I have no problem with this. We do have other termination methods

**Comment by atifaziz** [comment]
> I meant that the extension method would not be general enough, in that "the general case" is supported because there is no such general case.

All that depending on whether the deconstruction policy is strict or not by default? What do you think about being strict by default and providing `TakeN` as the escape hatch?

**Comment by fsateler** [comment]
> > I meant that the extension method would not be general enough, in that "the general case" is supported because there is no such general case.
>
> All that depending on whether the deconstruction policy is strict or not by default? What do you think about being strict by default and providing `TakeN` as the escape hatch?

I prefer strict methods. So from my POV it is better to provide that one. However, the fact that you first proposed the non-strict version makes me wonder if deciding on the strict API would force too many people to add `.Pad().Take(n)` to their calls? IOW, I thought it was "obvious" it should be strict, and your proposal makes me reconsider the "obviousness", and thus makes me very uncertain about how the API should look.

**Comment by atifaziz** [comment]
> Or to put it in another way, I thought it was "obvious" it should be strict, and your proposal makes me reconsider the "obviousness", and thus makes me very uncertain about how the API should look.

I proposed a non-strict version initially because I felt that (destructuring) _assignment_ always succeeds; we never expect it to fail. That's the most "obvious" thing. Strictness is the right thing to do if we say that there is an implicit conversion going on that could succeed or fail but it bothers me that conversion would get disguised here as assignment. A conversion that could fail usually requires an explicit syntax.

My current standing on this is that it should be strict. However, when someone reads this (uses [switch expression that's new in C# 8](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions)):

```c#
var quadrant = "123,-456".Split(',').Select(int.Parse) switch
{
    var (x, y) when x > 0 && y > 0 => $"I",
    var (x, y) when x < 0 && y > 0 => $"II",
    var (x, y) when x < 0 && y < 0 => $"III",
    var (x, y) when x > 0 && y < 0 => $"IV",
    var (x, y) => null
};
```

I wonder if they can reason that something could possibly go wrong once the integer parsing is done.

A, possibly superficial, approach could be to make the deconstruction explicit. Say we introduce this:

```c#
struct Deconstructible<T> : IEnumerable<T>
{
    readonly IEnumerable<T> _source;

    public Deconstructible(IEnumerable<T> source) =>
        _source = source;

    public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

and then these extension methods:

```c#
public static Deconstructible<T> Deconstructible<T>(this IEnumerable<T> source) =>
    new Deconstructible<T>(source);

public static void Deconstruct<T>(this Deconstructible<T> source, out T item1, out T item2)
{
    using (var e = source.GetEnumerator())
    {
        item1 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
        item2 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
        if (e.MoveNext())
            throw new Exception("Sequence too long.");
    }
}

public static void Deconstruct<T>(this Deconstructible<T> source, out T item1, out T item2, out T item3)
{
    using (var e = source.GetEnumerator())
    {
        item1 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
        item2 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
        item3 = e.MoveNext() ? e.Current : throw new Exception("Sequence too short.");
        if (e.MoveNext())
            throw new Exception("Sequence too long.");
    }
}
````

Now, the earlier example will require making a cheap hop over `Deconstructible`:

```c#
var quadrant = "123,-456".Split(',').Select(int.Parse).Deconstructible() switch
{
    var (x, y) when x > 0 && y > 0 => $"I",
    var (x, y) when x < 0 && y > 0 => $"II",
    var (x, y) when x < 0 && y < 0 => $"III",
    var (x, y) when x > 0 && y < 0 => $"IV",
    var (x, y) => null
};
```

Now someone (unfamiliar with MoreLINQ) reading that will say, “Hang on! Something is happening after integer parsing. Could that go wrong? What is that?”.

**Comment by atifaziz** [comment]
So instead of introducing `Deconstructible`, we could go with `Fold`, which already exists and is strict. The extension would be a very natural addition with a nice parallel as shown next.

With `Fold` today, you go through a lambda:

```c#
var quadrant = "123,-456".Split(',').Select(int.Parse).Fold((x, y) => (x, y) switch
{
    _ when x > 0 && y > 0 => "I",
    _ when x < 0 && y > 0 => "II",
    _ when x < 0 && y < 0 => "III",
    _ when x > 0 && y < 0 => "IV",
    _ => null
});
```

With a zero-argument overload, you _deconstruct_:

```c#
var quadrant = "123,-456".Split(',').Select(int.Parse).Fold() switch
{
    var (x, y) when x > 0 && y > 0 => "I",
    var (x, y) when x < 0 && y > 0 => "II",
    var (x, y) when x < 0 && y < 0 => "III",
    var (x, y) when x > 0 && y < 0 => "IV",
    _ => null
};
```

**Comment by fsateler** [comment]
> So instead of introducing `Deconstructible`, we could go with `Fold`, which already exists and is strict.

I very much like this idea.

**Comment by atifaziz** [comment]
> I very much like this idea.

Thanks. While it seemed like a nice idea, when I got round to implementing it (see PR #586), I felt it didn't fit the same definition of folding because it _deconstructs_ the sequence elements into _separate variables_ rather than _fold_ them into a _single result_ (as `Fold` does). So `AsDeconstructible` seems more correct and honest, although I have to admit that it reads longer and uglier.

**Comment by atifaziz** [comment]
While PR #586 is in review, I'd like to give the choice of strict or non-struct deconstruction semantics another crack. If we provide a count of how many items were actually deconstructed, like so:

```c#
public static void Deconstruct<T>(this IEnumerable<T> source, out T item1, out T item2, out int count)
{
    count = 0;
    using var e = source.GetEnumerator();
    (count, item1) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item2) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
}

public static void Deconstruct<T>(this IEnumerable<T> source, out T item1, out T item2, out T item3, out int count)
{
    count = 0;
    using var e = source.GetEnumerator();
    (count, item1) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item2) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item3) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
}

public static void Deconstruct<T>(this IEnumerable<T> source, out T item1, out T item2, out T item3, out T item4, out int count)
{
    count = 0;
    using var e = source.GetEnumerator();
    (count, item1) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item2) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item3) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
    (count, item4) = e.MoveNext() ? (count + 1, e.Current) : (count, default);
}
```

then the caller has all the information and flexibility to decide what to do without having to worry about exceptions (and then also throwing an exception becomes a choice of the caller):

```c#
var result =
    from s in new[]
    {
        "12",
        "12,34",
        "12,34,56",
        "12,34,56,78",
    }
    select new
    {
        Input = s,
        Result = s.Split(',').Select(int.Parse) switch
        {
            var (x, y, _, c)    when c == 2 => $"Point2D({x}, {y})",
            var (x, y, z, _, c) when c == 3 => $"Point3D({x}, {y}, {z})",
            _ => "?"
        }
    };

result.ForEach(Console.WriteLine);

/* prints:
{ Input = 12, Result = ? }
{ Input = 12,34, Result = Point2D(12, 34) }
{ Input = 12,34,56, Result = Point3D(12, 34, 56) }
{ Input = 12,34,56,78, Result = ? }
*/
```

Notice the use of [discard](https://docs.microsoft.com/en-us/dotnet/csharp/discards) (`_`) to probe an extra element so as to capture the case when there are more elements than desired.

With this approach, we don't need to hop over an additional method like `AsDeconstructible`, [as proposed earlier](https://github.com/morelinq/MoreLINQ/issues/538#issuecomment-487918865), just for sake of communicating the potential surprise of an exception due strict semantics.

**Comment by atifaziz** [comment]
Note that the [earlier example](https://github.com/morelinq/MoreLINQ/issues/538#issuecomment-493042590) can be written with a constant pattern for the count instead of using `when`:

```c#
var result =
    from s in new[]
    {
        "12",
        "12,34",
        "12,34,56",
        "12,34,56,78",
    }
    select new
    {
        Input = s,
        Result = s.Split(',').Select(int.Parse) switch
        {
            (var x, var y, _, 2)        => $"Point2D({x}, {y})",
            (var x, var y, var z, _, 3) => $"Point3D({x}, {y}, {z})",
            _ => "?"
        }
    };

result.ForEach(Console.WriteLine);
```

While it may not be clear what 2 and 3 mean, one can use comments, as in `(var x, var y, _, /* count = */ 2)`, or revert to the `when` form and use a more meaningful variable name like `count`. Either way, the choice is up to the developer. Where immaterial, the count can be discarded.

**Comment by atifaziz** [comment]
While this seemed like a cool idea, I am beginning to think that it's best not done because `Deconstruct` should never throw an exception. Even if we go with a non-strict version, _enumeration_ can throw during deconstruction and that doesn't seem right. Moreover, each pattern matching, as in a switch expression, will cause multiple calls to `Deconstruct` and multiple enumerations of the sequence, which is not what we want. The only correct way would be to materialize the sequence and then deconstruct an array or a list, which means that `Deconstruct` needs to be an extension for those types and consequently wouldn't belong in this project. 💭

**Comment by atifaziz** [comment]
Closing because it doesn't seem like a good idea in the end based on [my previous comment](https://github.com/morelinq/MoreLINQ/issues/538#issuecomment-510951973).

**Comment by atifaziz** [comment]
> Moreover, each pattern matching case, as in a switch expression, will cause multiple calls to `Deconstruct` and multiple enumerations of the sequence, which is not what we want.

This no longer seems to true with the final release of C# 8. I am not sure how much of this is an optimisation than something that is binding from the language specification.

**Comment by andi0b** [comment]
@atifaziz: I would love to see that feature in MoreLINQ and I agree with your concerns. Two remarks from me:

_Multiple Enumerations:_ It could be implemented just for `IList<T>`, which means would work at least on lists and arrays.

_Exceptions:_ I would also be surprised if there were exceptions on deconstruct. I don't see a big usability problem if it returns  `default(T)` when running out of values. Quite often this is sufficient (nullable types), and in the other cases you can do length checks, which are easy on arrays and lists

**Comment by atifaziz** [comment]
> _Multiple Enumerations:_ It could be implemented just for `IList<T>`, which means would work at least on lists and arrays.

Right, but then as [I also said](https://github.com/morelinq/MoreLINQ/issues/538#issuecomment-510951973), if `Deconstruct` needs to be an extension for lists then it doesn't belong in this project.

> I don't see a big usability problem if it returns `default(T)` when running out of values

Unfortunately, `default(T)` generally works against nullability when used to indicate a missing value. If `T` is `string` then `default(string)` is `null` and will require asking for [forgiveness (`!`)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving) only to break the caller. It gets more complicated with arrays because if you extend on `IList<>` then you also extend arrays and nullability reference checks don't work unless everyone is being honest by always declaring the (reference) element of an array as being nullable. The only way around this that I know of is to let the caller always provide the missing value representation as an argument. In fact, there are a few areas of MoreLINQ where returning `default(T)` may need to be revised into a breaking change.
