### ISSUE TITLE
TrySingle : xs → Zero | (x, One) | (x, Many)

### ISSUE THREAD

**Issue by jimmcslim** [morelinq/MoreLINQ#540]
I'm wondering whether the community would think that `TrySingle` would be a useful addition to MoreLINQ.

    public static Cardinality TrySingle<T>(this IEnumerable<T> values, out T result)
    public enum Cardinality { Zero, One, Many }

Where the behaviour of `TrySingle` is to attempt to return the first, single element from the enumerable. If the enumerable has a single element, `out result` is populated with the item, and `Cardinality.One` is returned. However, if there are zero items in the enumerable then the method returns `Cardinality.Zero`; if there are multiple items in the enumerable then the method returns `Cardinality.Many`. In both of these cases the `out result` is null.

A consumer of this method can then distinctly handle the `Zero` or `Many` cases in whichever special way is required.

I'm happy to submit a PR if this is worthwhile.

**Comment by jimmcslim** [comment]
True, that could be the implementation perhaps.

**Comment by atifaziz** [comment]
If we are going to add this, I would like to avoid introducing the `Cardinality` enum. I think the following is a lot more generic, a pure function and avoids by-ref, output, parameters:

```c#
public static TResult
    TrySingle<T, TCardinality, TResult>(this IEnumerable<T> values,
        TCardinality zero, TCardinality one, TCardinality many,
        Func<TCardinality, T, TResult> resultSelector)
```

In other words, the caller defines the three cardinality cases and the `resultSelector` will get to know which one was the case. The [original signature and enum you proposed](https://github.com/morelinq/MoreLINQ/issues/540#issue-368906303) can then be implemented locally as follows:

```c#
public static Cardinality TrySingle<T>(this IEnumerable<T> values, out T result)
{
    Cardinality cardinality;
    (cardinality, result) =
        values.TrySingle(Cardinality.Zero,
                         Cardinality.One,
                         Cardinality.Many,
                         ValueTuple.Create);
    return cardinality;
}
```

**Comment by MkazemAkhgary** [comment]
very nice suggestion, but I think Cardinality is overkill. what about this?

```c#
public static IEnumerable<T> ExtractFirst<T>(this IEnumerable<T> values, out T result)
{
    result = default;
    using (var enumerator = values.GetEnumerator())
    {
        var move = enumerator.MoveNext();

        if (move) result = enumerator.Current;

        return GetRest();

        IEnumerable<T> GetRest()
        {
            if (move)
            {
                while (enumerator.MoveNext())
                {
                    yield return enumerator.Current;
                }
            }
        }
    }
}
```

**Comment by atifaziz** [comment]
@MkazemAkhgary Your `ExtractFirst` implementation (which appears to be [`CADR`](https://en.wikipedia.org/wiki/CAR_and_CDR)-like) has two major flaws:

1. It disposes the enumerator.
2. It changes the enumerator into an enumerable when they're not the same thing.

> If null is returned, source contains no element.
> If returned enumerable is empty, source contains single element.

If these are the rules, then it suffices to have something like this:

```c#
public static IEnumerator<T> TryMoveToFirst<T>(this IEnumerable<T> values)
{
    var enumerator = values.GetEnumerator();
    try
    {
        return enumerator.MoveNext() ? enumerator : null;
    }
    catch
    {
        enumerator.Dispose();
        throw;
    }
}
```

The `Current` property of the returned enumerator will contain the first element so you don't need a separate out-argument to capture it. Disposing the returned enumerator will be the caller's responsibility.

**Comment by atifaziz** [comment]
#590 could address this too and since there's been no further follow up from @jimmcslim, I'm going to close this issue.

**Comment by atifaziz** [comment]
Re-opening this issue now that there is a PR (#612) open for it.

**Comment by atifaziz** [comment]
I have [moved this to the experimental namespace](b77df70598ab84c28cd43dcf74594024b6d575e1) as I feel this [needs more thought in terms of naming](https://github.com/morelinq/MoreLINQ/issues/698#issuecomment-554242255).
