### ISSUE TITLE
Memoize should use List instead of IList for cache, for performance reasons

### ISSUE THREAD

**Issue by YairHalberstadt** [morelinq/MoreLINQ#546]
Indexing into an Ilist requires an interface call, and can't be inlined. This can cause as much as a 10x performance hit on simple property accesses.
Since the _cache field is private, I see no reason not to declare the field as a List rather than an IList, and gain a free performance improvement at no cost.

**Comment by atifaziz** [comment]
Good catch & suggestion! :+1:

**Comment by YairHalberstadt** [comment]
Thanks
