### ISSUE TITLE
Scan by key/group

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#563]
I would like to suggest adding `ScanBy`. The idea has floated out of review of PR #562 that proposes to add `IndexBy` (see also #560) but where `ScanBy` would be an even more general implementation.

## Prototype

```c#
public static IEnumerable<TResult>
    ScanBy<T, TKey, TState, TResult>(
        this IEnumerable<T> source,
        Func<T, TKey> keySelector,
        Func<TKey, TState> seedSelector,
        Func<T, TKey, TState, TState> accumulator,
        Func<T, TKey, TState, TResult> resultSelector,
        IEqualityComparer<TKey> comparer = null)
{
    var stateByKey = new Dictionary<TKey, TState>(comparer); 
    foreach (var item in source)
    {
        var key = keySelector(item);
        if (!stateByKey.TryGetValue(key, out var state))
            state = seedSelector(key);
        state = accumulator(item, key, state);
        stateByKey[key] = state;
        yield return resultSelector(item, key, state);
    }
}
```

## Example

As an example, here is `IndexBy` implemented in terms of `ScanBy`:

```c#
public static IEnumerable<TResult>
    IndexBy<TSource, TKey, TResult>(
        this IEnumerable<TSource> source,
        Func<TSource, TKey> keySelector,
        Func<TSource, TKey, int, TResult> resultSelector,
        IEqualityComparer<TKey> comparer) =>
    source.ScanBy(keySelector, k => -1, (e, k, i) => i + 1, resultSelector, comparer);
```

Do we need such a function? Not really, because it could be implemented ad-hoc:

```c#
foreach (var (x, k, i) in 
    Enumerable.Range(0, 20)
              .Shuffle()
              .ScanBy(x => x / 5, k => -1, (x, k, i) => i + 1, ValueTuple.Create))
{
    // do something...
}
```

Here's a running max by key/group:

```c#
foreach (var (x, k, max) in 
    Enumerable.Range(0, 20)
              .Shuffle()
              .ScanBy(x => x / 5,
                      k => int.MinValue,
                      (x, k, m) => Math.Max(x, m),
                      ValueTuple.Create);
{
    // do something...
}
```

**Comment by atifaziz** [comment]
@leandromoh, @fsateler If you agree, I propose to supersede #560 with this.

**Comment by fsateler** [comment]
This looks better to me. It avoids the problem with Index, and is more general. +1 from me

**Comment by atifaziz** [comment]
@leandromoh Do you want to take this up in favour of #560?

**Comment by leandromoh** [comment]
@atifaziz Looks a nice idea to add this since it is more generic and we can use this to create other operators, like `IndexBy`. However, I must say that I had difficult to understand this new operator, even beeing a experient LINQ user so maybe it may be not intuitive for common users too, IMHO, I am in favour to add both, `ScanBy` and `IndexBy` in terms of  `ScanBy`, changing [IndexBy's PR](https://github.com/morelinq/MoreLINQ/pull/562) after `ScanBy` be added.

**Comment by atifaziz** [comment]
@leandromoh Let's add `ScanBy` because we all seem to be in agreement there. However, I don't think `IndexBy` is common enough to merit an addition yet _especially when we can offer a more general form_ that fits in nicely. You could say that [I am changing my position](https://github.com/morelinq/MoreLINQ/issues/560#issuecomment-465543039) but sometimes, as part of a review and discussion, one idea can lead to another.

> we can use this to create other operators, like `IndexBy`

Or users can do it themselves and with much more control. Once you offer `IndexBy`, one could ask why not offer all the others, like `RunningSumBy`, `RunningMinBy`, etc., and I am not sure we want to go there.

**Comment by leandromoh** [comment]
I see. Okay, lets go with `ScanBy` so

**Comment by leandromoh** [comment]
@atifaziz do you will submit a PR?

**Comment by atifaziz** [comment]
@leandromoh I'm not planning to with any urgency since I have never needed something like `ScanBy` or `IndexBy`, but I'd be happy if you want to jump the gun and submit a PR. Let me know if you're interested.

**Comment by leandromoh** [comment]
@atifaziz [PR](https://github.com/morelinq/MoreLINQ/pull/572) created!

**Comment by atifaziz** [comment]
> However, I don't think `IndexBy` is common enough to merit an addition

I miscalculated the utility of this as it can be used to _efficiently_ answer queries like getting the top elements in a group _without complete materialization of the groups_. We should proceed with adding it.

> IMHO, I am in favour to add both, `ScanBy` and `IndexBy` in terms of `ScanBy`, changing [IndexBy's PR](https://github.com/morelinq/MoreLINQ/pull/562) after `ScanBy` be added.

See 16f2cb4911da3fb3736572bd427a23ca03799e1a in PR #562.
