### ISSUE TITLE
Bug in ToDataTable with write only properties

### ISSUE THREAD

**Issue by DanAvni** [morelinq/MoreLINQ#564]
We have a class with a write only property, calling ToDataTable throws an exception as there is no read available for this property. I know I could send a list of properties to put in the data table but I think this should be fixed internally as it is useless to try reading these properties

**Comment by atifaziz** [comment]
Fair point.

**Comment by atifaziz** [comment]
This is now fixed as released as part of [3.1.1](https://github.com/morelinq/MoreLINQ/releases/tag/v3.1.1).
