### ISSUE TITLE
Q: Why are some implementations wrapped in IIFEs?

### ISSUE THREAD

**Issue by bert2** [morelinq/MoreLINQ#569]
Some of MoreLINQ's extensions methods are implemented using immediately invoked function expressions (IIFEs) that wrap the actual logic.

For example see the implementation of [Pipe()](https://github.com/morelinq/MoreLINQ/blob/59ae9f25bccd792e003995d895957b971c8ca08a/MoreLinq/Pipe.cs#L46):

```C#
public static IEnumerable<T> Pipe<T>(this IEnumerable<T> source, Action<T> action)
{
	if (source == null) throw new ArgumentNullException(nameof(source));
	if (action == null) throw new ArgumentNullException(nameof(action));

	return _(); IEnumerable<T> _() // IIFE right here
	{
		foreach (var element in source)
		{
			action(element);
			yield return element;
		}
	}
}
```

I've seen IIFEs in JavaScript before but never in C# (except for [funny hacks](https://stackoverflow.com/a/38234028/1025555)). What is the purpose of this?

**Comment by leandromoh** [comment]
This doubt was answered on issue 480. Please see It for clarification.

https://github.com/morelinq/MoreLINQ/issues/480

**Comment by leandromoh** [comment]
But note that there is no state here after function execution. The only state is the interator block's one.

**Comment by atifaziz** [comment]
For some more background, see [my answer](https://stackoverflow.com/a/50425545/6682) to the “[Can anyone explain this enumerator syntax?](https://stackoverflow.com/questions/47990969/can-anyone-explain-this-enumerator-syntax)” question on [StackOverflow](https://stackoverflow.com/).

I'm going to consider this question as answered but feel free to re-open if you disagree.

**Comment by bert2** [comment]
That answers my question. Thanks to you both!
