### ISSUE TITLE
Assert description typo in README

### ISSUE THREAD

**Issue by nstuller** [morelinq/MoreLINQ#570]
The Assert description is missing a word.

Instead of "condition otherwise throws an object." it should be "condition otherwise throws an System.Exception object."

**Comment by atifaziz** [comment]
Thanks! Do you want to submit a PR for that so you can be credited accordingly?

**Comment by nstuller** [comment]
I believe I just created a PR. Thanks for bearing with me as this is my first contribution on GitHub.

**Comment by atifaziz** [comment]
> Thanks for bearing with me as this is my first contribution on GitHub.

That seems to have gone well and thanks for your contribution.
