### ISSUE TITLE
MoreEnumerable.AtLeast and MoreEnumerable.Exactly

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#58]
Count() enumerates the entire sequence before returning, AssertCount() asserts that there are exactly a specific number of elements and throws an exception if not, Any() tells me if there are any elements in the sequence at all, but none of these provide the simple behaviour of telling that there are or are not at least x number of elements or exactly x number of elements.

AtLeast(int x) should iterate the sequence enough to count that there are at least x elements. If there are at least x elements, it returns true, otherwise false.

Exactly(int x) should iterate the sequence just enough to count upto x or x+1, if x+1 exists. If the sequence is exactly x elements long, it returns true, otherwise false.

---
Originally reported on Google Code with ID 58

Reported by `jeffmagic` on 2010-01-29 21:28:26

**Comment by sholland1** [comment]
The `Exactly` method isn't implemented on this yet.
I was thinking I could implement `Exactly` after finishing up `AtLeast`.

**Comment by atifaziz** [comment]
@sholland1 Kindly submit that as a separate & new issue, cross-referencing this one for background & quoting if necessary. Thanks.

**Comment by Arithmomaniac** [comment]
The current AtLeast has an optimization for ICollection. It should have one for IReadOnlyCollection instead/as well.
