### ISSUE TITLE
SingleOrError

### ISSUE THREAD

**Issue by dzmitry-lahoda** [morelinq/MoreLINQ#600]
Very often I need to get single result of collection. But if it is not single, I get weird error, hard to tell what failed. So possibly to have next kind of extensions would be helpful:
```
       public static T SingleOrError<T>(this IEnumerable<T> source, Func<T, bool> predicate, string errorMessage) 
        {
            try
            {
                return source.Single(predicate);
            }
            catch (InvalidOperationException notFound)
            {
                throw new InvalidOperationException(errorMessage, notFound);
            }            
        }
```

**Comment by atifaziz** [comment]
You can actually do this today with an overload of [`AssertCount`](https://morelinq.github.io/3.1/ref/api/html/M_MoreLinq_MoreEnumerable_AssertCount__1_1.htm), e.g.:

```c#
var zero = // assuming xs is a sequence of integers...
    xs.Where(x => x == 0)
      .AssertCount(1, (cmp, count) =>
            throw new ApplicationException($"Too {(cmp < 0 ? "few" : "many")} items (expected {count})."))
      .Single();
```

I will close this for now assuming `SingleOrError` would be redundant (albeit more efficient) with the above.
