### ISSUE TITLE
Move to single CI/CD platform

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#602]
In an effort to reduce maintenance, I suggest moving to using AppVeyor for CI/CD exclusively now that it supports [building on Linux](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/) in addition to Windows.

What will be lost is validating builds against OS X and Mono, but I think that's an acceptable trade-off. If there are issues with either, we can count on people reporting them and then dealing with them on a case-by-case basis.

Another option would be to use [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) since it supports Windows, Linux and macOS but I am less familiar with that platform and it would require me to spend more time than at the moment (unless someone wants to jump in and help with that).

@fsateler Thoughts?

**Comment by fsateler** [comment]
> In an effort to reduce maintenance

How much maintenance does keeping travis require?

> What will be lost is validating builds against OS X and Mono

The Linux page on appveyor says mono is available. So if that works then it would be only OSX lost.

> Another option would be to use Azure Pipelines since it supports Windows, Linux and macOS but I am less familiar with that platform and it would require me to spend more time than at the moment (unless someone wants to jump in and help with that).

Maybe leave this as a new issue with the help wanted tag.


Anyway, I think it's fine. As time moves on, I think most non windows users be on .net core rather than full net framework.

**Comment by atifaziz** [comment]
> How much maintenance does keeping travis require?

Not much to be perfectly honest, but thinking, one is less than two. For now, I have it sorted for C# 8 for both platforms in PR #582 but it did require tweaking and effort and reading two sets of docs. The end goal is to seek _proficiency_ in one platform, especially for non-functional/infrastructural bits.

> > Another option would be to use Azure Pipelines since it supports Windows, Linux and macOS but I am less familiar with that platform and it would require me to spend more time than at the moment (unless someone wants to jump in and help with that).
> 
> Maybe leave this as a new issue with the help wanted tag.

Good idea! I already added the tags in the first place, but let's leave this as moving to Azure Pipelines.

**Comment by atifaziz** [comment]
Both [AppVeyor](https://www.appveyor.com/blog/2019/11/20/build-macos-projects-with-appveyor/) and [GitHub Actions](https://github.com/features/actions) are now an option, in addition to [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/). AppVeyor would naturally be the path of least work and resistance. 😄

**Comment by ingAlfano** [comment]
Hi @atifaziz please consider me for Azure Pipelines I am very experienced on that

**Comment by atifaziz** [comment]
@ingAlfano Thanks for your offer to help. I was quite busy on other projects so didn't get a chance to come back to you on this earlier. Is it too late? I was wondering, are you equally experienced with [GitHub Actions](https://github.com/features/actions)?
