### ISSUE TITLE
Select for two-dimensional array

### ISSUE THREAD

**Issue by leotsarev** [morelinq/MoreLINQ#610]
See that question and answer
https://stackoverflow.com/a/48290430/408666

I think that one of simple methods that should "just work"

**Comment by atifaziz** [comment]
What @ericlippert proposes in that answer is an extension method for a multi-dimensional array and therefore belongs best in a library that provides extensions for arrays. All extension methods in MoreLINQ extend `IEnumerable<>` (and potentially _deriving interfaces_).
