### ISSUE TITLE
OOM With Batch

### ISSUE THREAD

**Issue by kcragin** [morelinq/MoreLINQ#619]
The `Batch()` method allocates a bucket of the size requested for the batch. This is reasonable behavior, but when I do something unreasonable like pass in `int.MaxValue` for my batch size, an `OutOfMemoryException` occurs.

This is, to be sure, a corner case. In my usage, I have a generic piece of code that accepts a configurable batch size. In normal usage we pass in a value that won't allocate a huge buffer. In another case, I didn't want batching to occur, but didn't want to modify the generic algorithm, so I passed in `int.MaxValue`.

Consider some sort of guard against this. I recognize that could be expensive, so perhaps only kick in the guard when the batch size is ridiculously high. Perhaps inspect the underlying sequence to see if it is finite, and adjust the batch size to the size of the sequence if the specified size is larger.

The workaround on my side is to do a check on size, so I understand if you wouldn't incorporate any of the above ideas... but, please document the behavior for others.

**Comment by atifaziz** [comment]
> Consider some sort of guard against this. I recognize that could be expensive, so perhaps only kick in the guard when the batch size is ridiculously high.

As you say, this could be expensive and it's risky to attempt to guess what would be _ridiculously high_.

> Perhaps inspect the underlying sequence to see if it is finite, and adjust the batch size to the size of the sequence if the specified size is larger.

This is a reasonable but only when dealing with a collection or a list where the `Count` is available in advance and can be used to avoid over allocation. I you're dealing with pure sequences then the guard won't help.

Batching is generally used when dealing with large data sets so it's kind of hack-ish to imagine.

> please document the behavior for others.

We can do this.

**Comment by atifaziz** [comment]
I should add that it is risky to rely on implementation details such as optimisations for lists and collections, if added. These could change in the future and affect your application's behaviour. What's more, it would be impossible to implement with asynchronous streams and observables.

**Comment by kcragin** [comment]
You know what? You're right. Frame a library perspective these optimizations _are_ hackish, and they would lead to varying behavior. Thanks for your comments.

**Comment by atifaziz** [comment]
> From a library perspective these optimizations _are_ hackish,

I would say it's safe and reasonable for a library to offer an optimisation but hackish or risky for an application to rely on them for _defined behaviour_. Ultimately, it's the application developer's call. I might still go ahead and add the optimisation but I just wanted to caution that it wouldn't be binding.

> Thanks for your comments.

Thank you too.
