### ISSUE TITLE
Window, WindowLeft and WindowRight are not optimal in memory

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#627]
`Window`, `WindowLeft` and `WindowRight` take `O(sourceSize*windowSize)` in memory.
If we accept that the method returns `IEnumerable<IReadOnlyList<TSource>>` instead of `IEnumerable<IList<TSource>>`, we can go down to `O(consumedElement) < O(sourceSize)`.

**Comment by Orace** [comment]
@atifaziz is there any equivalent too WindowLeftAndRight available ?

**Comment by atifaziz** [comment]
> is there any equivalent to WindowLeftAndRight available ?

No, never needed it and no one ever asked for it. Do you have a use case?

**Comment by Orace** [comment]
I was looking for it to improve it ;)
I think a `Window(int size, bool leftExtend = false, bool rightExtend = false, bool bothExtend = false)` overload is missing here.

**Comment by atifaziz** [comment]
For dynamic behaviour? I think if someone needs that, they can achieve it like this:

```c#
var xs = Enumerable.Range(1, 5);
var windows =
    from f in new Func<IEnumerable<int>, int, IEnumerable<IList<int>>>[]
    {
        MoreEnumerable.Window,
        MoreEnumerable.WindowLeft,
        MoreEnumerable.WindowRight,
    }
    select f(xs, 3).Select(w => $"[{w.ToDelimitedString(", ")}]")
                   .ToDelimitedString(", ");
foreach (var ws in windows)
    Console.WriteLine(ws);
// output:
// [1, 2, 3], [2, 3, 4], [3, 4, 5]
// [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5], [5]
// [1], [1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]
```

**Comment by Orace** [comment]
My proposal is `Window(size, extendLeft: true)` as an alias for `WindowLeft(size)`, same thing for right. + we have a free `WindowLeftAndRight`. And all of this can fit in a single implementation.

**Comment by Orace** [comment]
`Segment` also performs data copy. I seen an issue about it but I can't find it anymore.

**Comment by Orace** [comment]
Window return a sequence of R/W enable fresh new array and there is no easy way to maintain a Read only version with memory optimisation (keep track of disposed window to free memory in the back end buffer give segmentation management problems).
With the current implementation the GC do all the job. It is O(seqLength*windowSize) instead of O(seqLength) and that's it.

We might need BigO information in the documentation.
