### ISSUE TITLE
[Proposal] CachedSelect

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#637]
This is a proposal for a cached implementation of `Select`.

```C#
  IEnumerable<TOut> CachedSelect<TIn>(this IEnumerable<TIn> source, Func<TIn, TOut> selector);
  IEnumerable<TOut> CachedSelect<TIn>(this IEnumerable<TIn> source, Func<TIn, int, TOut> selector);
  IEnumerable<TOut> CachedSelect<TIn>(this IEnumerable<TIn> source, Func<TIn, TOut> selector, IComparer<TIn> inComparer = null, bool shareCache = true);
  IEnumerable<TOut> CachedSelect<TIn>(this IEnumerable<TIn> source, Func<TIn, int, TOut> selector, IComparer<TIn> inComparer = null, bool shareCache = true);
```

The behavior is the same as `Select`, except that `selector` is called only one for element that are the same relatively to the `inComparer` (null is replaced by `DefaultComparer`).

When `shareCache` is false a new instance of the cache is used at each enumeration.

**Comment by atifaziz** [comment]
This sounds like function-caching (rather than sequence-caching) to me.

**Comment by Orace** [comment]
Yes indeed, so "not our business" ?

**Comment by atifaziz** [comment]
Yes, I'd say it's out of scope. It belongs better in a library that offers just caching at the function level (which would be cross-cutting) because otherwise you'd end up adding a cached version for just about everything that takes one or more (mostly unary) function, like `CachedWhere`.
