### ISSUE TITLE
`Subsets(0)` should return an empty set

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#645]
The 0-Subsets of a sequence should be a one item sequence, and this item should be an empty list.
Indeed there is always one subset of length 0 : the empty set.

```C#
  Enumerable.Range(1, 4).Subsets(0);  // [] instead of [[]]
```

It returns an empty sequence instead.

A call to `Subsets()` return a sequence that contains an empty list, as expected.

**Comment by atifaziz** [comment]
Thanks for reporting this. Unfortunately, since this is a breaking change and `Subsets` has been around for a long time, I am currently inclined to defer this to the next major version update.
