### ISSUE TITLE
Bug in Window with short sequences

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#648]
If the input sequence have a length smaller than the window size, the sequence is empty.
It should return a sequence with one item: the full input sequence.

```C#
Enumerable.Range(0,1).Window(10); // [] instead of [[0]]
```

**Comment by Orace** [comment]
Duplicate #152

**Comment by atifaziz** [comment]
`Window` guarantees that each window will have exactly the requested size or count of elements. If the sequence contains fewer elements then there no windows produced. This is consistent with how [`Seq.windowed` from F#](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.windowed%5b't%5d-function-%5bfsharp%5d) behaves.
