### ISSUE TITLE
Missing using instruction in Exclude and Lead

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#649]
Here the list of not disposed enumerators
Unit test should be added for it (maybe we can do a generic test like NullArgumentTest).

- [x] MoreLinq\Exclude.cs:48
- [x] MoreLinq\Lead.cs:68
~SkipUntil~

We should have test for them

**Comment by atifaziz** [comment]
I somehow doubted the list as long. Let's take your first example of line 70 of `Backsert`:

https://github.com/morelinq/MoreLINQ/blob/ce57548c166c9ad59c9c5f6712bbc42bb358ca50/MoreLinq/Backsert.cs#L70

How's the enumerator not being disposed? I see a `using` that has the scope of the method.

> maybe we can do a generic test like `NullArgumentTest`

This is tricky but if you have ideas on how then I am listening. Meanwhile, we have [`TestingSequence`](https://github.com/morelinq/MoreLINQ/blob/ce57548c166c9ad59c9c5f6712bbc42bb358ca50/MoreLinq.Test/TestingSequence.cs) that should be used to help with checking for proper disposal. You can see this is used in tests for `Backsert`:

https://github.com/morelinq/MoreLINQ/blob/ce57548c166c9ad59c9c5f6712bbc42bb358ca50/MoreLinq.Test/BacksertTest.cs#L56-L63

Now, technically, if you remove the `using` in the `Backsert` then the tests should break. What's disturbing is that they don't and so you've highlighted another issue!

As yet another issue, `Pairwise` is missing the test:

https://github.com/morelinq/MoreLINQ/blob/ce57548c166c9ad59c9c5f6712bbc42bb358ca50/MoreLinq.Test/PairwiseTest.cs#L41-L46

So you've highlighted new issues by bringing up a potential non-issue. 😄

**Comment by Orace** [comment]
Indead Reasharper doesn't handle the new inline `using`.
I will update the list.

**Comment by Orace** [comment]
SkipUntil has to be fixed and tested too.

**Comment by atifaziz** [comment]
It seems that I have introduced some leaks in 3d44f73401dd9481f04d5e375b77a80a6e70e855 from PR #621. It seems that there wasn't enough test coverage to make that refactoring confidently. I wrongly assumed that if no tests broke then no leakage was introduced. Either 3d44f73401dd9481f04d5e375b77a80a6e70e855 should be reverted or it requires a second and closer (eyeball) review. Adding code coverage is becoming crucial going forward.

**Comment by Orace** [comment]
I'm not sure it's 3d44f73 since it's about use of `??=`
Maybe this one: cdc6f76

**Comment by Orace** [comment]
I read the full diff and find two missing using.
Turn out it was for `Exclude` and `Lead`

**Comment by atifaziz** [comment]
> I'm not sure it's [3d44f73](https://github.com/morelinq/MoreLINQ/commit/3d44f73401dd9481f04d5e375b77a80a6e70e855) since it's about use of `??=`
> Maybe this one: [cdc6f76](https://github.com/morelinq/MoreLINQ/commit/cdc6f76f4bf348e860b9eaa072279ee2956d6de7)

You're right. 🤦‍♂ I copied the wrong commit hash.

**Comment by Orace** [comment]
SkipUntil dispose properly its enumerator.

**Comment by atifaziz** [comment]
> I read the full diff and find two missing using.
> Turn out it was for `Exclude` and `Lead`

Hey, thanks a ton for reviewing the diff! ⭐️
