### ISSUE TITLE
Windows of Window(Left|Right) are not isolated from each other

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#652]
List returned by Window* methods should be isolated from each other.

With current implementation, modifying one window will modify the next windows accordingly:

```C#
var sequence = Enumerable.Repeat(0, 3);
foreach (var window in sequence.Window(2))
{
  window[1] = 1; // modify the last element

  // on second iteration window[0] is 1 and this fail
  Assert.That(window[0], Is.EqualTo(0));
}
```

**Comment by atifaziz** [comment]
This is by-design. You are allowed to do what you want with the returned windows. What's important is that those windows are independent of the original sequence on which they were created such that modifying an element through the window does not modify the source.

**Comment by Orace** [comment]
> those windows are independent of each other 

That is exactly what I show here: windows are not independent from each others

**Comment by atifaziz** [comment]
I re-read the code and you're absolutely right. Sorry for closing this but your explanation and test in #653 didn't read clear enough. Thanks for persevering.
