### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#670]
Several recent refactorings have highlighted that there isn't sufficient code coverage to refactor confidently. A case in point is issue #649 that seems to be [mainly caused by me](https://github.com/morelinq/MoreLINQ/issues/649#issuecomment-552099725).

[Coverlet](https://github.com/tonerdo/coverlet) has served me well in a lot of projects as a coverage tool. We could consider using it here too.

**Comment by Orace** [comment]
I quote myself from #667 

>In unit testing pattern we should not even use TestingSequence since it tests multiple things. (Enumerator disposal, multiple enumeration, multiple MoveNext at the end of the source).
The proper (in terms of unit testing) way to work is to split TestingSequence in 3 new mock (TestingSequenceForDisposed, etc..), add one test for each of it end finally ad revelant cases.
