### ISSUE TITLE
For optimization return ICollection or IList when possible.

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#677]
Some methods (like `SkipLast`) try to cast their `IEnumerable` input parameters to an `ICollection` or an `IList` for optimization purpose.

But some methods, like `CountBy` returns an `IEnumerable` even if they internally have build the full sequence:

https://github.com/morelinq/MoreLINQ/blob/c3516e335230f2a598ea0ab8f570b3d1b45b0970/MoreLinq/CountBy.cs#L76-L77

In those cases the returned object should be an `ICollection` or an `IList`.

Impacted methods are:

- [ ] CountBy
- [ ] FallbackIfEmpty (if input sequences is an `ICollection` or an `IList`)
- [ ] FillBackward<T>(source) (if T is a value type, and source an `ICollection` or an `IList`)
- [ ] FillForward<T>(source) (dito)
- [ ] Rank
- ...

**Comment by Orace** [comment]
To manage multiple enumerations.
- should we rebuild the full sequence ?
- Should we store it ?
- Should we forget it when all active `IEnumerator` are disposed ?

**Comment by Orace** [comment]
For rank, since all the data are enumerated anyway, and a dictionary of size N is created.
We allocate at least 3xN in memory.

Based on [this](https://stackoverflow.com/questions/1964234/sorting-an-array-related-to-another-array) 
we can do something like:

```C#
var values = input.ToArray();
var indices = new [] {1 .. n}; //TODO, best way to build it ?
Array.Sort(values, indices, comparer);
var result = new int[size];
for(var i = 0 .. n)
  result[indices[i]] = i+1;

return result;
```

**Comment by atifaziz** [comment]
> But some methods, like `CountBy` returns an `IEnumerable` even if they internally have build the full sequence:
>
> In those cases the returned object should be an ICollection or an IList.

They return `IEnumerable<T>` for deferred semantics and to enable further composition (think also callers) so it's not about optimization and how the operator does its job internally (though it should be documented if they don't _stream_ the sequence production). I'm closing this because we don't want to lose the ability to compose.
