### ISSUE TITLE
Feature Request: Add an extra  optional Parameter to the methods of Split(..) to keep the separator in the generated Lists.

### ISSUE THREAD

**Issue by moh-hassan** [morelinq/MoreLINQ#685]
For the array:
```cs
string[] strArray = { 
	"x", "1", "2", "x", "3", "4", "5", "6", "7", "8","x", "9" };
```  
I can Use Split to split the list based on the separator "x" as "case1":
```
1,2
3,4,5,6,7,8
9
```
But in my Scenario, I need to keep the separator in the generated Lists as "case2":

```
x,1,2
x,3,4,5,6,7,8
x,9
```
It's better if another Optional Parameter 'KeepSeparator =true' is added to the `Split Method`.
By default it's false.

The call can be:
```cs
var result=strArray.Split( x=> x=="x" ,KeepSeparator: true); //keep separator as use case2

var result=strArray.Split( x=> x=="x" ); //The normal usage as  use case1
```

I can provide PR to this feature if you agree.

**Comment by Orace** [comment]
The solution already exists, it's Segment.
```C#
var result = strArray.Segment(s => s == "x");
```

I vote to close this issue.

**Comment by moh-hassan** [comment]
Thanks for reply.
Segment solves my scenario.
