### ISSUE TITLE
Return was a mistake

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#689]
#636 should not have been merged.

**`Return` is an awful method name**

 - `return` is a c# instruction, and use this word for a method is a really bad idea
 - `Return` doesn't give any clue of what the methods do
- Used with a `using static MoreEnumerable;` it's just not readable:
```C#
  source.Select(Return);
  return Return(x);
```

It's about building a `IEnumerable`, it can be generalized and that should be `MoreEnumerable.From` (see #690) with different overload (`param T[]` being the start point).
The single item case can be optimized later.
If we need a special name for it, it should be something like `Encapsulate`, `Wrap`, `Pack`, `Box`, ... Anything that bring the idea of building a container around the element.

**`Return` is an alias for a simple stuff**

- `MoreEnumerable.Return` is _almost_ `x => new[] { x };` it does not even shorten the summoning.

**What about immutable list stuff ?**

If the target functionality was to build immutable list, just generalize it:
```C#
IList<T> ToImmutableList<T>(this IEnumerable<T> source);  // the returned list is readonly.
```
return `IReadonlyList` is not enough since it doesn't provide `CopyTo` optimized methods.

**Comment by Orace** [comment]
We also can have a `ImmutableList.From` factory.

**Comment by Orace** [comment]
If we really want to add a specific method for the one element case, it should be something like `Encapsulate`, `Wrap` or `Pack`.

**Comment by atifaziz** [comment]
This has all been discussed, including choice of names, in #615.

/cc @MitchBodmer

**Comment by atifaziz** [comment]
/remind me about closing this in one week if there are no further comments.

**Comment by atifaziz** [comment]
Closing as there's been no follow-up.
