### ISSUE TITLE
Patch for /trunk/MoreLinq/DistinctBy.cs

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#72]
more concise although probably not recommended in pure functional-style

---
Originally reported on Google Code with ID 72

Reported by `tagir.magomedov` on 2012-04-26 19:03:29

---
 * *Attachment: [DistinctBy.cs.patch](https://storage.googleapis.com/google-code-attachments/morelinq/issue-72/comment-0/DistinctBy.cs.patch)*

**Comment by fsateler** [comment]
This patch is wrong:

	var src = new [] { 1,2,2,4 };
	var distinct = src.DistinctBy(i => i);
	distinct.Dump();  // prints 1,2,4
	distinct.Dump(); // prints empty list

This is because `knownKeys` is created not on every iteration but only once when `Distinct` is invoked. This issue should be closed.

**Comment by atifaziz** [comment]
@fsateler Thanks for reviewing and spotting that.
