### ISSUE TITLE
From doesn't throw on null parameter

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#721]
Like Interleave in #696 (see 76e3516), From doesn't throw immediately when a null element is passed via params or as classic argument in any of the overloads.

**Comment by atifaziz** [comment]
This [was discussed](https://github.com/morelinq/MoreLINQ/pull/333#pullrequestreview-53813671) in PR #333. Please see all the comments and review there.

I am closing this as by-design.
