### ISSUE TITLE
TryWhere()  TrySelectOrFallback()

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#74]
## TryWhere(predicate)

`TryWhere` should behave as regular `Where`, but also filter out the items where the predicate throws exception.

Many times a `Where` clause may be accessing a dictionary, or it may have have a long invocation chain within the item where null checks are impractical and only the "happy case" should have to be considered.

Of course it is undesirable to create a lot of exception, but the benefit in code clarity can often be worth it. This may also be the difference from using a lambda expression to using a named predicates declared elsewhere. Inlined predicates become less readable with a sprinkled `if null` , `if .ContainsKey()` and `if .Any()`.

---
Originally reported on Google Code with ID 74

Reported by `tormod.steinsholt` on 2012-06-16 12:23:07

**Comment by leandromoh** [comment]
I think `TryWhere `should receive 2 predicates of `T`: one to filter method and the other to decide if the element should be included or not in the returned sequence.

```
public static IEnumerable<TResult> TryWhere<TSource, TResult>(
    this IEnumerable<TSource> source, 
    Func<TSource, bool> predicate,
    Func<TSource, bool> include)
{
    foreach(var e in source)
    {
        try
        {
            if (predicate(e))
                yield return e;
        }
        catch(Exception e)
        {
            if (include(e))
                yield return e;
        }
    }
}
```

**Comment by atifaziz** [comment]
Catching exceptions in just about every operation that takes a lambda will violate the Single Responsibility Principle and give way to complexity. It will also bloat the library because you could add a `TryXXX` version for just about every operator.

> Many times a `Where` clause may be accessing a dictionary

It's better to have an extension method for dictionaries that doesn't throw and use that in `Where` and elsewhere (pun, pun).

> or it may have have a long invocation chain within the item where null checks are impractical and only the "happy case" should have to be considered

C# has [null-conditional operators](https://msdn.microsoft.com/en-us/library/dn986595.aspx) since version 6 and those should be used to make null checks practical. One can also resort to using combinators with _optional_ and _trial_ types if C# 6 isn't an option (pun, pun, pun).

I'm closing this as wont-fix.
