### ISSUE TITLE
Batch returns non-empty batch sequence for empty input collection

### ISSUE THREAD

**Issue by AndrewKostousov** [morelinq/MoreLINQ#741]
The following test is failing with MoreLinq v3.3.1 and was passing with MoreLinq v3.2.0:
```
new string[0].Batch(100).ToArray().Should().BeEmpty();
```

I think this is side-effect of #623 optimization. If this change in behavior was intentional it would be nice if it had been documented somewhere.

**Comment by atifaziz** [comment]
@AndrewKostousov That is certainly a bug that seems to have slipped through the cracks and thanks for reporting it!

**Comment by atifaziz** [comment]
The fix for this is now published as part of [version 3.3.2](https://github.com/morelinq/MoreLINQ/releases/tag/v3.3.2).
