### ISSUE TITLE
Flatten returns IEnumerable<object> instead of IEnumerable<T>

### ISSUE THREAD

**Issue by akoskovacs** [morelinq/MoreLINQ#745]
It would be great if the result of ```Flatten()``` wouldn't require a cast to the original type, but instead would use template parameters.

Did you have some explicit reason to go with objects?

**Comment by atifaziz** [comment]
@leandromoh Can I let you pick this up since [`Flatten` was your contribution](https://github.com/morelinq/MoreLINQ/issues/356)?

**Comment by leandromoh** [comment]
@akoskovacs since `Flatten` works over the non-generic version of  `IEnumerable`, which is basically a sequence of anything (`IEnumerable<object>`), so flatten operates regardless of any type. 

the signature `IEnumerable<T> Flatten<T>(IEnumerable source)` is also ambiguous. we dont know if will perform a cast on each object or return objects of `T` type. So we have branchs of behavior here, which would require effort of development, documentation and tests for each behavior.

To avoid all this unnecessary complexity, users can simple combine `Flatten` with `Cast` or `OfType` native operators of LINQ. 

To get all elements of a specific type

```c#
var source = new List<object>()
{
    1,
    2,
    new List<object>()
    {
        3,
        new ArrayList()
        {
            4,
            "foo"
        },
        5,
        true,
    },
   "bar",
    6
};

source.Flatten().OfType<int>() returns [1, 2, 3, 4, 5, 6] 
source.Flatten().OfType<string>() returns ["foo", "bar"]
source.Flatten().OfType<bool>() returns [true]
```

To cast all elements of especific type.

```c#
var source = new object[]
{
    1, 2, 3, 4, 5,
    new object[]
    {
        6, 7,
        new object[]
        {
            8, 9,
            new object[]
            {
                10, 11, 12,
            },
            13, 14, 15,
        },
        16, 17,
    },
    18, 19, 20,
};

source.Flatten().Cast<int>(); returns [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
``` 

To se more examples of usage you might check the [unit tests](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq.Test/FlattenTest.cs)

**Comment by GeeWee** [comment]
Isn't there a chance we can get flatten to work with the simple case of an IEnumerable<T> containing only one type? Aka the signature `IEnumerable<T> Flatten<T>(IEnumerable<T> source)` - just like a `SelectMany(i=>i)` would do?

**Comment by atifaziz** [comment]
> …, but instead would use template parameters.

@akoskovacs `Flatten` doesn't have any generic type parameters so not sure which one you're expecting to be used.

@GeeWee If you want strong-typed flattening then use [`TraverseDepthFirst`](https://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_TraverseDepthFirst__1.htm). The example from @leandromoh above can be rewritten as:

```c#
var source = new object[]
{
    1, 2, 3, 4, 5,
    new object[]
    {
        6, 7,
        new object[]
        {
            8, 9,
            new object[]
            {
                10, 11, 12,
            },
            13, 14, 15,
        },
        16, 17,
    },
    18, 19, 20,
};    

var ns =
    MoreEnumerable.TraverseDepthFirst((object)source,
                                      node => node is object[] children
                                            ? children
                                            : Array.Empty<object>())
                  .Choose(node => node is int v ? (true, v) : default);

foreach (var n in ns)
    Console.WriteLine(n);
```

The [above is available as a C# script](https://github.com/morelinq/MoreLINQ/files/5034762/demo.csx.gz) that you can run with [`dotnet script`](https://www.nuget.org/packages/dotnet-script/).

I will close this issue, but feel free to re-open if you have a concrete idea and example of how you see `Flatten` can be rendered more strict.

---
📎  [`demo.csx.gz`](https://github.com/morelinq/MoreLINQ/files/5034762/demo.csx.gz)

**Comment by akoskovacs** [comment]
@atifaziz I see that there is no type parameter and that was my original concern. Thanks to @leandromoh for explaining, why he chose this solution.

I think it is really rare that you want to flatten heterogeneously typed enumerables.
 
In my original use-case I had to partition a list into smaller list chunks, and after doing the work I could finally flatten them back. 

There are a few other use-cases when you want to partition a list of the same type into different pieces and then flattening them back. On those cases a one-liner flattening would make the code more readable.

**Comment by atifaziz** [comment]
> In my original use-case I had to partition a list into smaller list chunks, and after doing the work I could finally flatten them back.

Do you mean at arbitrary levels sub-chunks? If not, then `SelectMany` is your friend:

```c#
Enumerable.Range(1, 13)
          .Segment(x => x % 3 == 0) // break it up
          .SelectMany(xs => xs) // stitch it back
```

For when you have a tree, there's `TraverseDepthFirst`/`TraverseBreadthFirst`.

It helps helps to have a real working example of the problem you're facing otherwise we might be just shooting past by each other.

**Comment by GeeWee** [comment]
I think to me, at least, this `Flatten` implementation would just be equivalent to `SelectMany(i=>i)` - it's just a more descriptive name for it.

**Comment by atifaziz** [comment]
@GeeWee They're not equivalent, or only to a superficial extent. `SelectMany` only flattens one level of nesting. `TraverseDepthFirst`/`TraverseBreadthFirst`/`Flatten` go to any arbitrary depth.

**Comment by GeeWee** [comment]
Ah, that's a very fair point, I hadn't caught that.
