### ISSUE TITLE
Min/MaxBy documented return type incorrectly mentions singular value

### ISSUE THREAD

**Issue by GuntherStruyf** [morelinq/MoreLINQ#764]
Confusing for new users who inspect the documented return type, this stems from #328 #369 "Change MaxBy/MinBy to return all extrema elements". The summary was updated, the documented return type not.

summary:
> Returns the minimal element **_s_** of the given sequence, based on the given projection.
= plural

returns:
> The minimal element, according to the projection.
= singular

**Comment by atifaziz** [comment]
Thanks for pointing this out!

**Comment by atifaziz** [comment]
@GuntherStruyf Feel free to review and bless PR #765!

**Comment by atifaziz** [comment]
Closed via e384ba07f13d7fd15609da5348dbf4523f93c1e1 (merge of PR #765).
