### ISSUE TITLE
Batch for async stream source

### ISSUE THREAD

**Issue by Dunge** [morelinq/MoreLINQ#773]
Trying to convert my solution to async, stumbling on this issue.
I was using MoreLINQ Batch() to group yielded items in batch of 150.

Previously:
```
public IEnumerable<Log> DownloadLogs()
{
    while(!finished)
    {
        log = NetworkGet();
        yield return log;
    }
}

foreach (var s in DownloadLogs().Batch(150))
{
    .. process batch of 150 ...
}
```

Now trying to call NetworkGet in async, yield won't work unless you use the new C#8 feature called IAsyncEnumerable. So I can do that instead:

```
public async IAsyncEnumerable<Log> DownloadLogs()
{
    while(!finished)
    {
        log = await NetworkGet();
        yield return log;
    }
}

await foreach (var s in DownloadLogs().Batch(150))
{
    .. process batch of 150 ...
}
```

Unfortunately Batch doesn't exist as an IAsyncEnumerable extension.

Is supporting this something that could be added to the MoreLINQ library, or should I just restructure my method differently? Any suggestion?

**Comment by atifaziz** [comment]
> Is supporting this something that could be added to the MoreLINQ library…?

I've had this on my mind for some time and I'd hate to say that I don't know it will happen. The trouble is duplicating all the code and tests, which seems somewhat dirty. The semantics can also change in some ways and requires some thought (not saying that's the case with `Batch` specifically).

**Comment by atifaziz** [comment]
@Dunge Have a look at `Buffer` from [System.Interactive.Async](https://www.nuget.org/packages/System.Interactive.Async) meanwhile.

**Comment by atifaziz** [comment]
[MoreAsyncLINQ](https://github.com/i3arnon/MoreAsyncLINQ) by @i3arnon also [offers this](https://github.com/i3arnon/MoreAsyncLINQ/blob/deb2282dc27f21d74fd5285265d38a38c452b7ec/src/MoreAsyncLINQ/Operators/Batch.cs).

**Comment by Dunge** [comment]
Thanks! I'll close this issue if there are available alternatives.

I personally do not require it anymore, but that's nice to know.
