### ISSUE TITLE
Batch and read-only collections

### ISSUE THREAD

**Issue by jmbryan4** [morelinq/MoreLINQ#774]
Without a check for IsReadOnly the pattern matching switch statement will hit the case:
`ICollection<TSource> collection when collection.Count <= size`: and not 
`case IReadOnlyList<TSource> list when list.Count <= size:` or
`case IReadOnlyCollection<TSource> collection when collection.Count <= size:`
when the collection is read-only.

Are the cases for IReadOnlyCollection and IReadOnlyList needed?

(Batch.cs):
```
public static IEnumerable<TResult> Batch<TSource, TResult>(this IEnumerable<TSource> source, int size,
            Func<IEnumerable<TSource>, TResult> resultSelector)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (size <= 0) throw new ArgumentOutOfRangeException(nameof(size));
            if (resultSelector == null) throw new ArgumentNullException(nameof(resultSelector));

            switch (source)
            {
                case ICollection<TSource> collection when collection.Count == 0:
                {
                    return Enumerable.Empty<TResult>();
                }
                case ICollection<TSource> collection when collection.Count <= size:
                {
                    return _(); IEnumerable<TResult> _()
                    {
                        var bucket = new TSource[collection.Count];
                        collection.CopyTo(bucket, 0);
                        yield return resultSelector(bucket);
                    }
                }
                case IReadOnlyCollection<TSource> collection when collection.Count == 0:
                {
                    return Enumerable.Empty<TResult>();
                }
                case IReadOnlyList<TSource> list when list.Count <= size:
                {
                    return _(); IEnumerable<TResult> _()
                    {
                        var bucket = new TSource[list.Count];
                        for (var i = 0; i < list.Count; i++)
                            bucket[i] = list[i];
                        yield return resultSelector(bucket);
                    }
                }
                case IReadOnlyCollection<TSource> collection when collection.Count <= size:
                {
                    return Batch(collection.Count);
                }
                default:
                {
                    return Batch(size);
                }
```

With the change to this case `ICollection<TSource> collection when collection.Count <= size` to:
```
case ICollection<TSource> collection when !collection.IsReadOnly && collection.Count <= size:
```
it will execute the correct case when the collection is IReadOnlyList or IReadOnlyCollection.

Test input:
```
var input = new List<int> { 1, 2, 3, 4, 5 }.AsReadOnly();
var input = new List<int> { 1, 2, 3, 4, 5 };
var input = new ReadOnlyCollection<int>(new[] { 1, 2, 3, 4, 5 });
input.Batch(10);
```

**Comment by atifaziz** [comment]
I am not quite sure I understand the issue you're reporting. Is it a bug? If so, how does the following demonstrate it?

> Test input:
> 
> ```
> var input = new List<int> { 1, 2, 3, 4, 5 }.AsReadOnly();
> var input = new List<int> { 1, 2, 3, 4, 5 };
> var input = new ReadOnlyCollection<int>(new[] { 1, 2, 3, 4, 5 });
> input.Batch(10);
> ```

Could you please share the expected and actual output?

I might be misreading you, but I feel you are misunderstanding `IsReadOnly`. This property is neither available on `IReadOnlyCollection<>` not on `IReadOnlyList<>`.

**Comment by jmbryan4** [comment]
I'm not sure the switch cases for IReadOnly* are necessary, because the source parameter is IEnumerable<T>.
The below tests hit the ICollection<T> case
```        
    [Fact]
    public void BatchReadOnlyListSmallerThanSize()
    {
        IReadOnlyList<int> input = new List<int> { 1, 2, 3, 4, 5 }.AsReadOnly();
        var resultGroup = input.Batch(10).ToList();
        Assert.True(resultGroup[0].SequenceEqual(new[] { 1, 2, 3, 4, 5 }));
    }

    [Fact]
    public void BatchReadOnlyCollectionSmallerThanSize()
    {
        var collection = new ReadOnlyCollection<int>(new[] { 1, 2, 3, 4, 5 });
        var result = collection.Batch(100).ToList();
        Assert.True(result[0].SequenceEqual(new[] { 1, 2, 3, 4, 5 }));
    }
```
Maybe Batch() needs an overload for the IReadOnlyList optimization case?
Something like:
```
        public static IEnumerable<TResult> Batch<TSource, TResult>(this IReadOnlyList<TSource> source, int size,
            Func<IEnumerable<TSource>, TResult> resultSelector)
        {
            _ = source ?? throw new ArgumentNullException(nameof(source));
            if (size <= 0) throw new ArgumentOutOfRangeException(nameof(size));
            _ = resultSelector ?? throw new ArgumentNullException(nameof(resultSelector));

            if (source.Count <= size)
            {
                var bucket = new TSource[source.Count];
                for (var i = 0; i < source.Count; i++)
                {
                    bucket[i] = source[i];
                }
                yield return resultSelector(bucket);
            }
            else
            {
                TSource[] bucket = null;
                var count = 0;

                foreach (var item in source)
                {
                    bucket ??= new TSource[size];
                    bucket[count++] = item;

                    // The bucket is fully buffered before it's yielded
                    if (count != size)
                        continue;

                    yield return resultSelector(bucket);

                    bucket = null;
                    count = 0;
                }

                // Return the last bucket with all remaining elements
                if (bucket != null && count > 0)
                {
                    Array.Resize(ref bucket, count);
                    yield return resultSelector(bucket);
                }
            }
        }
```

**Comment by atifaziz** [comment]
The `switch` checks for the _run-time type_. The only type known statically at compile-time is `IEnumerable<>`.

**Comment by jmbryan4** [comment]
That's true, my bad. I'm mostly trying to figure out why the below test enters the switch case: ICollection<TSource> collection when collection.Count <= size. 
Is this expected?
```
    [Fact]
    public void BatchReadOnlyListSmallerThanSize()
    {
        IReadOnlyList<int> input = new List<int> { 1, 2, 3, 4, 5 }.AsReadOnly();
        var resultGroup = input.Batch(10).ToList();
        Assert.True(resultGroup[0].SequenceEqual(new[] { 1, 2, 3, 4, 5 }));
    }
```
Is this because the source input can be cast to an ICollection<> in the switch pattern match check?
In what scenario will one of the IReadOnly* switch cases be used over an ICollection case?

BTW I really appreciate your contributions to MoreLINQ! I have found many use cases for the various extension methods.

**Comment by viceroypenguin** [comment]
@jmbryan4  (@atifaziz) pattern matching switch statements are evaluated in code order. In this case, execution uses the `ICollection<T>` branch because it is tested first and finds a successful match. In the `Batch()` code as written, `IReadOnlyList<T>` and `IReadOnlyCollection<T>` branches will only be executed on items that implement those interfaces but _not_ `ICollection<T>` (which is incredibly rare). If it is important to use `IReadOnlyList<T>` and `IReadOnlyCollection<T>` branches with objects under `System.Collection.Generic`, then they should be before `ICollection<T>` in code order.

See: https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching#using-pattern-matching-switch-statements 

> When limited to constant values, no more than one `case` label could match the value of the switch expression. Combine that with the rule that every `switch` section must not fall through to the next section, and it followed that the `switch`sections could be rearranged in any order without affecting behavior. Now, with more generalized `switch`expressions, the order of each section matters. The `switch`expressions are evaluated in textual order. Execution transfers to the first `switch`label that matches the `switch`expression.

**Comment by viceroypenguin** [comment]
@jmbryan4  - I believe that the `ICollection<T>` behavior is actually more generically appropriate (`.CopyTo()` instead of manually copying one by one), which is why it is listed first. `IReadOnlyList<T>` and `IReadOnlyCollection<T>` cases are only there to cover unusual cases that may not fit the `ICollection<T>` version. As such, it's correct as written? (correct me if I'm wrong @atifaziz ?)

**Comment by atifaziz** [comment]
> correct me if I'm wrong @atifaziz

You're spot on and the order of the switch cases is indeed optimised with respect to most commonly expected scenarios. Thanks for chiming in the a detailed explanation!

I'll closed this as a non-issue now.
