### ISSUE TITLE
Provide MoreLinq as a Portable Class Library

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#78]
To widen the applicability of MoreLinq, it would be great if the library could also be provided as a Portable Class Library. I have done a first examination of what would be required in order to build a PCL out of MoreLinq, and my findings can be found in this answer to a StackOverflow question: http://stackoverflow.com/a/13700766/650012

---
Reported by @anders9ustafsson on 2012-12-04 10:28:18

Originally reported on Google Code with ID 78

**Comment by michael-freidgeim-webjet** [comment]
@atifaziz, this thread gives details how  https://www.nuget.org/packages/MoreLinq.Portable/ was created. However it will be good to have documentation page, describing what are diferences/limittions/advantages of   MoreLinq.Portable compare to main MoreLinq

**Comment by atifaziz** [comment]
@michael-freidgeim-webjet Actually you can just use [`morelinq`](https://www.nuget.org/packages/morelinq/) since as of [version 2.0](https://www.nuget.org/packages/morelinq/2.0.0), the PCL version is delivered in the same package.

**Comment by michael-freidgeim-webjet** [comment]
@atifaziz  Thanks, I suggest to add a note on https://www.nuget.org/packages/MoreLinq.Portable/,  that it's obsolete

**Comment by atifaziz** [comment]
> I suggest to add a note

@michael-freidgeim-webjet Could you open that as a new issue so we track it separately? It'll get lost here in an issue that's closed.
