### ISSUE TITLE
Batch is not lazy

### ISSUE THREAD

**Issue by maurosampietro** [morelinq/MoreLINQ#789]
`Batch` extension divides the source sequence into sized buckets.

It yields the buckets, but instead of yielding elements one by one for each element coposing the bucket, it creates an array for the bucket and load all of the elements.

The following code does yield buckets and bucket elements too. As a plus, it handles edge cases and in particular `size=0` better. (if `size=0` your extension throws an exception on purpose while it should return the whole sequence. Mine does return the whole sequence.)

If you choose to include the following code and would like to mention me i'd be grateful

```
        public static IEnumerable<IEnumerable<T>> Batch<T>( this IEnumerable<T> source, int size )
        {
            var enumerator = source.GetEnumerator();

            while( enumerator.MoveNext() )
                yield return BatchInternal();

            IEnumerable<T> BatchInternal()
            {
                int i = 0;
                do
                {
                    yield return enumerator.Current;
                    i++;

                } while( i != size && enumerator.MoveNext() );
            }
        }
```

**Comment by atifaziz** [comment]
Your implementation turns an enumerator into an enumerable, which is logically incorrect. Sharing the same enumerator across can lead to odd behaviours and bugs. When you run the following:

```c#
var batches = Enumerable.Range(1, 10)
                        .Batch(3);

Console.WriteLine(string.Join(", ", from b in batches select b.Count()));
Console.WriteLine(string.Join(", ", from b in batches select b.Sum()));
```

Your implementation gives the correct results on the count and sum of the elements in each bucket:

    3, 3, 3, 1
    6, 15, 24, 10

However, materialize to an array:

```c#
var batches = Enumerable.Range(1, 10)
                        .Batch(3)
                        .ToArray();

Console.WriteLine(string.Join(", ", from b in batches select b.Count()));
Console.WriteLine(string.Join(", ", from b in batches select b.Sum()));
```

and you get completely incorrect results:

    1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11

Here's another one that gets the first element of each bucket:

```c#
var xs =
    from b in Enumerable.Range(1, 10).Batch(3)
    select b.First();

Console.WriteLine(string.Join(", ", xs));
```

but which gives wrong results from the start:

    1, 2, 3, 4, 5, 6, 7, 8, 9, 10

I am closing this unless you find a flawless solution with passing tests to prove it.

You might also be interested in checking out issue #400 for some previous discussion around lazy buckets.

**Comment by maurosampietro** [comment]
Thanks for pointing that out. I will look into it and try to find an elegant solution if that exists!

**Comment by sdanyliv** [comment]
Just found in our library:
https://github.com/linq2db/linq2db/blob/236ec969144197900255aa8444af88d6390bd0e1/Source/LinqToDB/Common/EnumerableHelper.cs#L38

**Comment by atifaziz** [comment]
@sdanyliv Thanks for sharing, but unfortunately, it also suffers from some problems. For example, the following throws an `InvalidOperationException` saying "Cannot enumerate IBatched.Current multiple times":

```c#
var stats =
    from b in Enumerable.Range(1, 10).Batch(3)
    select new { Sum = b.Sum(), Count = b.Count() };

Console.WriteLine(string.Join(", ", stats));
```

To make it work, you have to do the following:

```c#
var stats =
    from b in Enumerable.Range(1, 10).Batch(3)
    select b.ToArray() into b
    select new { Sum = b.Sum(), Count = b.Count() };
```

An alternative would be to use [MoreLINQ's single-pass multi-aggregate operator](http://morelinq.github.io/3.3/ref/api/html/Overload_MoreLinq_MoreEnumerable_Aggregate.htm):

```c#
var stats =
    from b in Enumerable.Range(1, 10).Batch(3)
    select b.Aggregate(0, (sum, x) => sum + x,
                       0, (cnt, _) => cnt + 1,
                       (sum, cnt) => new { Sum = sum, Count = cnt });
```

Nevertheless, it's a workaround.

Perhaps this is a by-design limitation of your implementation because you are sharing an underlying source across all batches.

**Comment by maurosampietro** [comment]
I found a nice solution: make LINQ not available at all. 

This is acceptable in a lot of scenarios where what is needed is just to read all the sequence ONCE and at the same time be notified when a certain number of elements is read to react accordingly (logging, visual UI or console updates, db updates etc..). 

In my case i need to read very large CSV files where the batch is at least 50000 rows and every 50000 rows i insert the data in a database.

```
    public static class EnumerableExtensions
    {
        public static NonLINQableResult<NonLINQableResult<T>>
            Batch<T>( this IEnumerable<T> source, int size )
        {
            var batched = BatchInternal( source, size );
            return new NonLINQableResult<NonLINQableResult<T>>( batched );
        }

        private static IEnumerable<NonLINQableResult<T>> BatchInternal<T>(
            this IEnumerable<T> source, int size )
        {
            var enumerator = source.GetEnumerator();

            while( enumerator.MoveNext() )
                yield return new NonLINQableResult<T>( BatchInternal() );

            IEnumerable<T> BatchInternal()
            {
                int i = 0;
                do
                {
                    yield return enumerator.Current;
                    i++;

                } while( i != size && enumerator.MoveNext() );
            }
        }
    }

    public class NonLINQableResult<T>
    {
        private readonly IEnumerable<T> _source;

        public NonLINQableResult( IEnumerable<T> source )
        {
            _source = source;
        }

        public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();
    } 


```

it can be tested like this (LINQ is not available on the sequence):

```
            int i = 0;
            foreach( var batch in Enumerable.Range( 0, 10 ).Batch( 3 ) )
            {
                Console.WriteLine( "batch i" );

                foreach( var item in batch )
                {
                    Console.WriteLine( item );
                }
            }

```

So a little bit of an explanation: foreach only need a class to have a GetEnumerator method to work.
Linq needs IEnumerable<T> to work. So we wrap the source inside a container class exposing only the GetEnumerator method and encapsulate the elements being produced by the Batch in this wrapper class, suppressing the ability to use LINQ.

The solution i presented here works for IEnumerable<IEnumerable<T>>. If you have more sub sequences you need to modify the code accordingly.

Hope it helps someone. (Ironically i posted a question on StackOverflow asking 'How to prevent LINQ over a sequence' and i got dislikes, moderators wanting to close my question, a lot of theorists shifting the conversation offtopic talking about, 'XY problems' and other s**t. Unreal. StackOverflow was a serious site and I'm ashamed of what it has become in the last couple of years. Sorry for giving this out)
