### ISSUE TITLE
☂ Review nullability reference annotations

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#803]
This is a follow-up “umbrella issue” to track review of nullability reference annotations applied in PR #582. The annotations were slated for release [3.4.0](https://github.com/morelinq/MoreLINQ/milestone/24) but that milestone missed its _desired_ schedule by a big margin. On the positive side, C# 9 got released meanwhile with improvements that could help in revising some of the annotations to be more “honest” (especially with regards to public signatures). The review should therefore focus on:

- benefitting from [unconstrained type parameter annotations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/unconstrained-type-parameter-annotations#-annotation)
- remove uses of [null-forgiving operator (`!`)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving), if possible, based on improvements in static analysis
- pattern matches on `{}` versus `var`.

PR #582 touched on a number of methods, but the following are the priority for this review:

- [x] `Await`
- [x] `CountBy`
- [x] `EquiZip` (#908)
- [x] `FallbackIfEmpty` (#808)
- [x] `Flatten` (#847)
- [x] `Fold`
- [x] `FullGroupJoin` (#806)
- [x] `GroupAdjacent` (#809)
- [x] `Lag` (#805)
- [x] `Lead` (#805)
- [x] `LeftJoin`
- [x] `MaxBy` (#872)
- [x] `MinBy` (#872)
- [x] `Memoize`
- [x] `OrderBy`
- [x] `OrderedMerge`
- [x] `Pad` (#804)
- [x] `PadStart` (#804)
- [x] `PartialSort` (#888)
- [x] `Partition` (#881)
- [x] `Permutations`
- [x] `Rank` (#913)
- [x] `RightJoin`
- [x] `ScanBy`
- [x] `ToDataTable` (#914)
- [x] `ToDelimitedString`
- [x] `ToDictionary` (#852)
- [x] `TrySingle` (#801)
- [x] `ZipLongest` (#900)
- [x] `ZipShortest` (#908)

/cc @sid-6581

**Comment by viceroypenguin** [comment]
Await does not have any nullability concerns as far as I can tell.
