### ISSUE TITLE
Add `LongSequence` and `LongRange`

### ISSUE THREAD

**Issue by V0ldek** [morelinq/MoreLINQ#815]
Neither standard LINQ nor MoreLINQ have a way of generating a sequence of Int64s. I've noticed that because I actually needed such a method. Obviously generating a sequence from 1 to 10^18 would kill anything you'd run that on, however I have use cases where I have to generate sequences of reasonable length but of large values.

I would like the following methods added:

```
IEnumerable<long> MoreEnumerable.LongRange(long from, long count);

IEnumerable<long> MoreEnumerable.LongSequence(long from, long to);

IEnumerable<long> MoreEnumerable.LongSequence(long from, long to, long step);
```

with obvious semantics identical to those of `Enumerable.Range` and `MoreEnumerable.Sequence` but for Int64.

If this was already considered but decided to not be implemented for MoreLINQ, let me know. If not I could implement a PR for these myself.

**Comment by atifaziz** [comment]
> If this was already considered but decided to not be implemented for MoreLINQ

If memory serves right, no one has asked for it before.

>  If not I could implement a PR for these myself.

Since it's probably a very rare use case, wonder if it's even worth for you to go through the trouble of a PR and someone else having to maintain it. You could get away with using [`Generate`](http://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_Generate__1.htm) that's already there:

```c#
var longs = MoreEnumerable.Generate(1L, x => checked(x + 1));
```

In fact, it could get away with pretty thin wrapper extensions:

```c#
static class LongEnumerable
{
    public static IEnumerable<long> Range(long from, long count) =>
        Sequence(from, checked(from + count - 1), 1);

    public static IEnumerable<long> Sequence(long from, long to, long step) =>
        MoreEnumerable.Generate(from, x => checked(x + step))
                      .TakeWhile(x => x <= to);
}
```

**Comment by V0ldek** [comment]
> Since it's probably a very rare use case, wonder if it's even worth for you to go through the trouble of a PR and someone else having to maintain it.

Yup, not sure about that either. Your wrappers are actually better than what I used before, so thanks.

I don't know what's the triage process in this repo, how do you decide what to add to the API? My guess would be to leave this issue hanging and see if someone else needs this use case.

**Comment by atifaziz** [comment]
> Your wrappers are actually better than what I used before, so thanks.

Glad to hear they helped!

> I don't know what's the triage process in this repo, how do you decide what to add to the API?

Nothing officially documented yet, but apart from [one](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/ToDictionary.cs) or [two](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/ToHashSet.cs) exceptions, the criteria that I've been using for a very long time now is that an extensions/method has to do some non-trivial amount of work (and do it efficiently while maintaining correctness).

> My guess would be to leave this issue hanging and see if someone else needs this use case.

If you don't mind, I'll close it as we have enough open issues, people can search across closed issues and keeping open doesn't prevent from duplicates getting opened anyway.

If you do end up using `Generate` for `long` values then [an example would be a welcomed contribution](https://github.com/morelinq/examples/blob/master/m/generate.md).
