### ISSUE TITLE
Access previous items with Linq

### ISSUE THREAD

**Issue by mdmoura** [morelinq/MoreLINQ#817]
I have the following for loop:

    for (Int32 i = 0; i < inputs.Count(); i++)
      outputs.Add(inputs[index] * outputs[index - 1]);  

Is there any extension in MoreLinq that would allow me to do this with Linq?

    var outputs = inputs.Select(input => input * Previous Output);

**Comment by viceroypenguin** [comment]
The `.Scan` extension will do what you're looking for. It returns the first value, and then the result of the operation when provided the previous result and the current value. See this example for your case.

```csharp
var outputs = inputs.Scan((a, b) => a * b);
```
