### ISSUE TITLE
batch with index

### ISSUE THREAD

**Issue by dzmitry-lahoda** [morelinq/MoreLINQ#824]
like select with index (sure I can batch select, but for symmetry with select batch with index could be good)

**Comment by atifaziz** [comment]
You can use [Batch](http://morelinq.github.io/3.3/ref/api/html/Overload_MoreLinq_MoreEnumerable_Batch.htm) with [Index](http://morelinq.github.io/3.3/ref/api/html/Overload_MoreLinq_MoreEnumerable_Index.htm) to get the same effect.

**Comment by dzmitry-lahoda** [comment]
oh, index has start, nice. but still not sure why not to have stuff in batch.

**Comment by atifaziz** [comment]
> but still not sure why not to have stuff in batch.

For the following reason quoted from #121:

> @fsateler is absolutely right. `Index` was added to MoreLINQ to solve that problem once and for all. It not only gets tiring to provide an index-supplying version of callbacks for each operator but it also explodes the number of overloads and unit tests to write for each operator. `Index` is ready to use on anything.

I'll close this for now on the basis that `Index` is “good enough”.

**Comment by dzmitry-lahoda** [comment]
What bad happens if add Batch with index? I mean `good enough` is good when adding costs to much. But adding adds consistency to API (MoreLINQ follows LINQ) and out of box destucturing (by no means it is nice or pleasan destructur KVP, and heck - why KVP - not type?).
