### ISSUE TITLE
Pop last element in List

### ISSUE THREAD

**Issue by dzmitry-lahoda** [morelinq/MoreLINQ#825]
like in Rust or Python https://doc.rust-lang.org/std/vec/struct.Vec.html#method.pop
```csharp
 public static T? Pop<T>(this List<T> self)
        {
            if (!self.IsAny()) {
              return default;
            }
            var last = self[self.Count - 1];
            self.RemoveAt(self.Count - 1);
            return last;
        }
```

**Comment by atifaziz** [comment]
This would be an extension method for `IList<>`, not `IEnumerable<>` so it's really out of the scope for this project. I'm afraid, you'll have to look for [other projects where such extensions exist](https://github.com/atifaziz/Mannex/blob/e29856c3f3a28ec147db17d9844af2c372e01da3/src/Collections/Generic/List.cs#L71-L113) or can be added.

**Comment by dzmitry-lahoda** [comment]
oh, such nice extensions hidden in some probably will not nuget it package... more like MoreLinq.Specialized .

**Comment by dzmitry-lahoda** [comment]
.net does not hesitates to use list inside code https://github.com/dotnet/runtime/blob/f2a55e228b83df6aa6dc215e295bf3da5ab6fc17/src/libraries/System.Linq/src/System/Linq/Last.cs#L76 

i could have pop coded around enumerable so..., it will be same slow as last. so pop makes sense to be
