### ISSUE TITLE
Swap elements 

### ISSUE THREAD

**Issue by sunnamed434** [morelinq/MoreLINQ#841]
```cs
static List<T> Swap<T>(this List<T> source, int index1, int index2)
{
     T temp = list[index1];
     list[index1] = list[index2];
     list[index2] = temp;
     return source;
}
```

**Comment by atifaziz** [comment]
This would be an extension method for `IList<>`, not `IEnumerable<>`, so it's really out of the scope for this project. I'm afraid, you'll have to look for other projects to contribute this.
