### ISSUE TITLE
TrySelect

### ISSUE THREAD

**Issue by Jlobblet** [morelinq/MoreLINQ#848]
A use case I have run into multiple times in LINQ is mapping a `Try*` method (such as [`TryParse`](https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-6.0)) across a collection, and filtering to where the value was successfully processed.
At the moment, this is not well supported by either LINQ or MoreLINQ.

I propose the addition of a `TrySelect` method, with a signature along the lines of:

```cs
public delegate bool TrySelector<in TSource, TResult>(TSource value, out TResult result);
public static IEnumerable<TResult> TrySelect<TSource, TResult>(this IEnumerable<TSource> source, TrySelector<TSource, TResult> selector);
```

Names subject to improvement.

This would be analogous to F#'s [`Seq.choose`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#choose), or equivalent functions from the different F# collection libraries.

At the moment I see the following unresolved questions:

- [ ] Name of the method (and delegate)
- [ ] Whether the type signature is correct

If it's something desirable, I'd be willing to PR this addition to the library.

**Comment by viceroypenguin** [comment]
I think this is a great idea. Initially, the only adjustment I'd add to the type signature is to change the first type parameter to `in TSource`, similar to the delegate type parameter. 

Another open question to consider: what to do with the items that fail the parsing? Perhaps an alternative typing might be:
```csharp 
IEnumerable<(bool success, TSource? item)> TrySelect<in TSource, TResult>(this IEnumerable<TSource> source, TrySelector<TSource, TResult> selector);
```

This would allow the consumer to know whether or not the parsing succeeded on each item. If the consumer only cares about successful items, it could be used in conjunction with `.Choose()` as such:
```csharp
var strings = new List<string>();
var parsedInts = strings.TrySelect(int.TryParse).Choose(x => x);
```

**Comment by Saalvage** [comment]
@viceroypenguin In regards to the open question: I don't think the signature should be changed, what you are suggesting is relatively easily accomplishable via regular LINQ
```cs
enumerable.Select(x => (success: x.TryGet(out var val), val)
```
while the (probably more common) use case where you want to only get the values which could successfully be gotten requires: 
```cs
enumerable.Select(x => (success: x.TryGet(out var val), val)).Where(x => x.success).Select(x => x.val)
```
The second use case also being the original target of this proposal.

**Comment by viceroypenguin** [comment]
@Saalvage Technically, both forms are basically one-liners, but I can see the value in this one-liner specifically since it is a common enough situation to want to use `.TryParse()` in a LINQ fashion without having to add the tuples yourself. 

I would ask, however, that you take a look at the code at the end of my response; the `.Choose()` method is provided by MoreLinq and does both `.Where().Select()` in your response.

**Comment by atifaziz** [comment]
> This would be analogous to F#'s [`Seq.choose`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#choose), or equivalent functions from the different F# collection libraries.

Since MoreLINQ already has [`Choose`](https://morelinq.github.io/3.3/ref/api/html/M_MoreLinq_MoreEnumerable_Choose__2.htm), what would be the benefit/motivation of adding `TrySelect` besides as a signature adapter? While it's long, #358 provides plenty of examples and discussion around the design of `Choose`.

**Comment by atifaziz** [comment]
See also [my comment in #358](https://github.com/morelinq/MoreLINQ/issues/358#issuecomment-337466283) where you can adapt `TryParse` to work with `Choose`:

```c#
src.Choose(TryParse.Int32)
```

It doesn't get more succinct and [TryParsers](https://github.com/atifaziz/TryParsers) has been around since a decade.

**Comment by atifaziz** [comment]
Just a closing note to future visitors…

Starting with .NET 7, you'll need a single generic `TryParse` _adapter_ for [all types that support being parsed from strings](https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1):

```c#
public static (bool, T)
    TryParse<T>(string s)
    where T : IParsable<T> =>
    T.TryParse(s, null, out var val) ? (true, val) : default;

public static Func<string, (bool, T)>
    TryParse<T>(IFormatProvider formatProvider)
    where T : IParsable<T> =>
    s => T.TryParse(s, formatProvider, out var val) ? (true, val) : default;
```

And then you can use it with `Choose`:

```c#
var xs =
    "zero,one,2,3,4,five,6,7,eight,9"
        .Split(',')
        .Choose(TryParse<long>);

Console.WriteLine(string.Join(", ", xs)); // 2, 3, 4, 6, 7, 9
```

Variation with culture:

```c#
var xs =
    "zero,one,2,3,4,five,6,7,eight,9"
        .Split(',')
        .Choose(TryParse<long>(CultureInfo.InvariantCulture));

Console.WriteLine(string.Join(", ", xs)); // 2, 3, 4, 6, 7, 9
```

A similar API was request in dotnet/runtime#59463 and the approach @omariom [proposed there, that doesn't require a new delegate type](https://github.com/dotnet/runtime/issues/59463#issuecomment-926014976), is essentially how `Choose` works in MoreLINQ.
