### ISSUE TITLE
Split algorithm error

### ISSUE THREAD

**Issue by DamianMorozov** [morelinq/MoreLINQ#851]
I try to use this code for the Split:
```
IEnumerable<int> numbers = Enumerable.Range(1, 20);
Console.WriteLine($"{numbers.Count()} items input: {string.Join("\t", numbers)}");
IEnumerable<IEnumerable<int>>? split = numbers.Split(5);
foreach (IEnumerable<int>? item in split)
{
    Console.WriteLine($"{item.Count()} items output: {string.Join("\t", item)}");
}
```
But have this output result:
```
20 items input: 1       2       3       4       5       6       7       8       9       10      11      12      13     14       15      16      17      18      19      20
4 items output: 1       2       3       4
15 items output: 6      7       8       9       10      11      12      13      14      15      16      17      18     19       20
```
I think, this is the mistake. Th result mus be another:
```
4 items output: 1       2       3       4       5
15 items output: 6      7       8       9       10      11      12      13      14      15      16      17      18     19       20
```

**Comment by viceroypenguin** [comment]
@DamianMorozov The algorithm is correct, according to the semantics of the matching method in `string.Split()`. See as follows:

```csharp
var txt = "hello world, morelinq!";
var splits = txt.Split(' ');
splits.SequenceEqual("hello", "world,", "morelinq!");
```

Notice that the space (`' '`) is not provided to any of the resultant elements. The same is true for the MoreLinq `.Split()` algorithm - the item being split on is removed and not provided to either of the sequences. If you want to include the element in one of the sequences, then you should review `.Segment()`, which provides a method to split the sequence into multiple sequences, but all elements are included in the resultant sequences.
