### ISSUE TITLE
converting IEnumerable<TSource> into IEnumerable<IEnumerable<TSource>>?

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#86]
hi,

How can i convert my Source as `IEnumerable<IEnumerable<TSource>>` from `IEnumerable<TSource>` and pass it to the  `IEnumerable<IEnumerable<T>> Transpose<T>(this IEnumerable<IEnumerable<T>> source){}`

How to do this.please any help will be appriciated..

Thanks,

---
Originally reported on Google Code with ID 86

Reported by `sampath.murala` on 2013-12-11 10:04:40

**Comment by fsateler** [comment]
This doesn't look like either a bug or feature request, I think this can be closed.
