### ISSUE TITLE
Please make .NET 4 compatible distribution (or allow silent modifications)

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#88]
The background should be well known.

When including todays single morelinq distribution in a project, you cannot invoke the Zip operator in a code block that has included both the System.Linq and Morelinq namespaces.

You can work around this problem today by either not using them in the same code block or by using the "per operator" nuget packages. 

Adding all the nuget packages for the individual operators is a hassle when using ad hoc projects or LINQPad. I also think that it is somewhat excessive engineering to achieve a general solution for what is in all likelihood will be very few cases. 

Todays solution also sets it apart from regular LINQ operators as Morelinq operators will not be laying around in intellisense waiting to be used/investigated. If intellisense does not show "ToDelimitedString", would you really browse nuget for it? How would you know the exact spelling without the partial matching of intellisense? Do you expect people to frequent the project web site in search of new operators?  I have little doubt that this slows down the adoption of new operators. A project like this is also about educating people into functional thinking.

I suggest a breaking change that Zip should be removed from the main branch and available as separate nuget package. 

Alternatively a separate .NET4 distribution. It's not like .NET4 is a new novelty anymore.

Alternatively (2), the license should allow removal of source code (commenting out zip operator) without all the end user notifications requirements clicking in place.

I make dll's for tooling (mostly internal use), and the license terms that applies for modified source code (distributed notice, source code availability, help->about info) that would have to accompany every tiny .exe file is not trivial to achieve in a large company.

Thank you. I love morelinq.

---
Originally reported on Google Code with ID 88

Reported by `tormod.steinsholt` on 2014-01-30 09:07:26

**Comment by fsateler** [comment]
I don't see Zip anywhere, and my projects can use Zip (with 2.0-alpha1). Is this still valid?

**Comment by atifaziz** [comment]
This was addressed in 88c573f7bbcd15d0cd09f22e9b73b62dce9b66ed, which closed #60, but that was slated for 2.0. I think that issue was about release a 1.0 targeting 4.0 without `Zip`. This can be closed once 2.0 is out with the breaking change or closed now as wont-fix.

**Comment by fsateler** [comment]
I think marking as closed is correct then (the tag I don't have an
opinion). Unfortunately, the github tracker is not particularly good at
handling multiple (release) branches.

The usual way of dealing with issues in the github tracker is to close them
when the code is imported into mainline (ie, the master branch). For
example, github will automatically close issues when so marked in the
commit or pull request message. The alternative is to manually close all
issues at release time which would be very error prone.

(As you can see I'm walking through the issues to triage them. If I'm
creating too much noise please tell me so)



On 29 October 2015 at 14:28, Atif Aziz <notifications@github.com> wrote:

> This was addressed in 88c573f
> <https://github.com/morelinq/MoreLINQ/commit/88c573f7bbcd15d0cd09f22e9b73b62dce9b66ed>,
> which closed #60 <https://github.com/morelinq/MoreLINQ/issues/60>, but
> that was slated for 2.0. I think that issue was about release a 1.0
> targeting 4.0 without Zip. This can be closed once 2.0 is out with the
> breaking change or closed now as wont-fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morelinq/MoreLINQ/issues/88#issuecomment-152257517>.
>



-- 

Saludos,
Felipe Sateler

**Comment by atifaziz** [comment]
This will be addressed by 2.0 only.

**Comment by atifaziz** [comment]
> As you can see I'm walking through the issues to triage them. If I'm creating too much noise please tell me so

Appreciate your help so please carry on. I will try & keep up. If I go silent at times, don't lose hope; :) it's just one of the many projects I'm working on at the same time.
