### ISSUE TITLE
Interleave irregular enumerables with circular strategy

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#89]
result: `!a1!b2!c3!a4!b5!c1!a2!b3!c4!a5!b1!c2!a3!b4!c5!a1`... (Hope I got that right, you get the idea). The length of the `IEnumerables` is unknown of course and the result should be lazy-evaluated.

There may already be a way to do this but I didn't see anything obvious like this:

``` c#
public static IEnumerable<T> Interleave<T>(params IEnumerable<T>[] sequencesToInterleave)
{
 ... 
}

foreach (var item in Interleave(new string[] { "!" }, new string[] { "a", "b", "c"
}, new string[] { "1", "2", "3", "4", "5" }))
{
                    Console.Write(item.ToString());
}
```

---

Originally reported on Google Code with ID 89

Reported by `virtanena` on 2014-05-09 00:18:09

**Comment by leandromoh** [comment]
@atifaziz 
Lazy `IEnumerables `(those generated by `yield return`) [throw an exception](http://stackoverflow.com/a/2308254) when you call Reset method. 
So I dont think it is a good idea to use it here, since the `IEnumerables `passed as parameters may be lazy. 

however, now that we have the `Repeat `overload that transforms the sequence infinite, we can do the following:

```
public static IEnumerable<T> Interleave<T>(params IEnumerable<T>[] sequencesToInterleave)
{
    var sequences = sequencesToInterleave.Skip(1).Select(x => x.Repeat()).ToArray();

    return sequencesToInterleave[0].Repeat().Interleave(sequences);
}
```

**Comment by atifaziz** [comment]
@leandromoh You're right. Now that we have [`Repeat`](http://morelinq.github.io/2.2/ref/api/html/M_MoreLinq_MoreEnumerable_Repeat__1.htm) to repeat sequences forever, the effects can be achieved relatively easily:

```
Microsoft (R) Visual C# Interactive Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #r "MoreLinq.dll"
> using MoreLinq;
> var example =
.     "!".ToCharArray().Repeat()
.        .Interleave("abc".ToCharArray().Repeat(),
.                    "12345".ToCharArray().Repeat())
.                    .Take(48)
.                    .ToDelimitedString(string.Empty)
.                    + "...";
> example
"!a1!b2!c3!a4!b5!c1!a2!b3!c4!a5!b1!c2!a3!b4!c5!a1..."
```

And your implementation can be turned into a one-liner for someone who needs that behavior:

```c#
public static IEnumerable<T> Interleave<T>(this IEnumerable<T> source, params IEnumerable<T>[] others) =>
    MoreEnumerable.Interleave(source.Repeat(), others.Select(x => x.Repeat()).ToArray());
```

So I'm going to close this on the basis that it's too trivial now.

Thanks for the triage.
