### ISSUE TITLE
Implement Full Outer Join

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#92]
FullOuter Join is a relatively common operation that unfortunately is not implemented in linq. It would be great if MoreLinq could provide an implementation.

---
Originally reported on Google Code with ID 92

Reported by @fsateler on 2014-08-27 15:50:35

**Comment by fsateler** [comment]
I had a PR on [bitbucket](https://bitbucket.org/morelinq/morelinq/pull-requests/1/add-fullouterjoin-method/diff). I plan to update it to provide a FullGroupJoin instead. Comments welcome!

**Comment by fsateler** [comment]
Work in progress at branch full-outer branch on my fork https://github.com/fsateler/MoreLINQ/tree/full-outer

**Comment by atifaziz** [comment]
@fsateler [Your work](https://github.com/fsateler/MoreLINQ/tree/full-outer) is in a [branch](https://github.com/fsateler/MoreLINQ/tree/full-outer) that branches off [the one](https://github.com/fsateler/MoreLINQ/tree/mono-todelimited) for #105 and therefore assumes that PR #104 is merged. Your `full-outer` branch should really branch off from **master** at  e0d370e69cb6c8b9f2b38acbef9a220558f3cfcd. I would fix this before any further work in order to make it possible to merge in the end when it's ready.

**Comment by fsateler** [comment]
@atifaziz yes, I haven't rebased on master because otherwise it doesn't build on my linux box. When I file the PR I will rebase on top of master.

**Comment by atifaziz** [comment]
@fsateler [Your implementation](https://github.com/fsateler/MoreLINQ/blob/4f869d8034534dc150eafc76cb480b57649aa5de/MoreLinq/FullGroupJoin.cs) seems very close to the one [posted on StackOverflow](http://stackoverflow.com/a/13503860/6682) by @sehe. Did you take inspiration from it or use it as a starting point and then adapted the code to arrive at a full group join? If so, I just want to make sure that credit is at least paid where it's due (e.g. as code comment).

**Comment by fsateler** [comment]
@atifaziz I'm not sure. I certainly took inspiration from somewhere on the internet (and very likely stackoverflow), but I don't remember the original source.

It seems likely I used this as a starting point when I needed it, so I'll add a comment to the code.

**Comment by atifaziz** [comment]
@fsateler :+1: I think something as simple as the following will do:

    // Inspiration & credit: http://stackoverflow.com/a/13503860/6682

It's [what I usually do](https://bitbucket.org/raboof/mannex/src/1f2e4ac33df6759a5a8ecd2166c5bd2403ce9e17/src/Data/DataTable.cs?at=default#DataTable.cs-80).

**Comment by sehe** [comment]
@atifaziz  me too. Cheers!

**Comment by fsateler** [comment]
@atifaziz Should this pull request be done against v1 or master? I rebased against v1 but I'm not sure if new methods should instead go to v2.

**Comment by fsateler** [comment]
Doh, I now see [that comment](https://github.com/morelinq/MoreLINQ/issues/92#issuecomment-135825095) where you say off master.

**Comment by fsateler** [comment]
@atifaziz please merge into master the changes from v1, otherwise the portable project doesn't build with VS2015. BTW, is there any tool that automates the grouping of each partial class file under MoreEnumerable.cs?

**Comment by atifaziz** [comment]
@fsateler It's been building fine all along though [I did a merge](https://github.com/morelinq/MoreLINQ/commit/379ba62cb03263a6ef7baa31160960f0053467f6) that should bring things up to date with v1. What does your build output show? Mine is:

```
Microsoft (R) Build Engine version 4.6.81.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  MoreLinq -> C:\MoreLINQ\MoreLinq\bin\Debug\MoreLinq.dll
  MoreLinq.Test -> C:\MoreLINQ\MoreLinq.Test\bin\Debug\MoreLinq.Test.dll
  MoreLinq.Portable -> C:\MoreLINQ\MoreLinq\bin\Debug\MoreLinq.Portable.dll
  MoreLinq.Portable.Test -> C:\MoreLINQ\MoreLinq.Test\bin\Debug\Portable.MoreLinq.Test.dll
Microsoft (R) Build Engine version 4.6.81.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  MoreLinq -> C:\MoreLINQ\MoreLinq\bin\Release\MoreLinq.dll
  MoreLinq.Test -> C:\MoreLINQ\MoreLinq.Test\bin\Release\MoreLinq.Test.dll
  MoreLinq.Portable -> C:\MoreLINQ\MoreLinq\bin\Release\MoreLinq.Portable.dll
  MoreLinq.Portable.Test -> C:\MoreLINQ\MoreLinq.Test\bin\Release\Portable.MoreLinq.Test.dll
```

> BTW, is there any tool that automates the grouping of each partial class file under MoreEnumerable.cs?

Sorry, what do you mean by grouping? You mean generate a single file from them all?

**Comment by fsateler** [comment]
@atifaziz This is the output when building on top of master:

	1>------ Rebuild All started: Project: MoreLinq, Configuration: Debug Any CPU ------
	2>------ Rebuild All started: Project: MoreLinq.Portable, Configuration: Debug Any CPU ------
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(443,73,443,79): error CS3001: Argument type 'IEnumerable<ushort>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(465,73,465,79): error CS3001: Argument type 'IEnumerable<ushort>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(480,71,480,77): error CS3001: Argument type 'IEnumerable<uint>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(502,71,502,77): error CS3001: Argument type 'IEnumerable<uint>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(517,72,517,78): error CS3001: Argument type 'IEnumerable<ulong>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(539,72,539,78): error CS3001: Argument type 'IEnumerable<ulong>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(110,72,110,78): error CS3001: Argument type 'IEnumerable<sbyte>' is not CLS-compliant
	1>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(132,72,132,78): error CS3001: Argument type 'IEnumerable<sbyte>' is not CLS-compliant
	3>------ Rebuild All started: Project: MoreLinq.Test, Configuration: Debug Any CPU ------
	3>CSC : error CS0006: Metadata file 'C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\bin\Debug\MoreLinq.dll' could not be found
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(110,72,110,78): warning CS3001: Argument type 'IEnumerable<sbyte>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(132,72,132,78): warning CS3001: Argument type 'IEnumerable<sbyte>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(443,73,443,79): warning CS3001: Argument type 'IEnumerable<ushort>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(465,73,465,79): warning CS3001: Argument type 'IEnumerable<ushort>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(480,71,480,77): warning CS3001: Argument type 'IEnumerable<uint>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(502,71,502,77): warning CS3001: Argument type 'IEnumerable<uint>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(517,72,517,78): warning CS3001: Argument type 'IEnumerable<ulong>' is not CLS-compliant
	2>C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\ToDelimitedString.g.cs(539,72,539,78): warning CS3001: Argument type 'IEnumerable<ulong>' is not CLS-compliant
	2>  MoreLinq.Portable -> C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq\bin\Debug\MoreLinq.Portable.dll
	4>------ Rebuild All started: Project: MoreLinq.Portable.Test, Configuration: Debug Any CPU ------
	4>  MoreLinq.Portable.Test -> C:\Users\felipe\Documents\GitHub\MoreLINQ\MoreLinq.Test\bin\Debug\Portable.MoreLinq.Test.dll
	========== Rebuild All: 2 succeeded, 2 failed, 0 skipped ==========

The errors stop after pulling from the merge, thanks.

Sorry for the bad wording. I mean I had to hand edit the csproj to make the `FullGroupJoin.cs` file appear under (ie, as "generated from") `MoreEnumerable.cs`, and do this for both the MoreLinq and MoreLinq.Portable projects. What I was wondering is if there was a tool that automated this.

**Comment by fsateler** [comment]
BTW, I built via visual studio, not the build cmd file

**Comment by atifaziz** [comment]
Could you please report the build issue as new? Discussion is getting overloaded here?

**Comment by fsateler** [comment]
the build issue is resolved after the merge you did so no need for a new
issue.

On 1 October 2015 at 13:38, Atif Aziz <notifications@github.com> wrote:

> Could you please report the build issue as new? Discussion is getting
> overloaded here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morelinq/MoreLINQ/issues/92#issuecomment-144781909>.
>



-- 

Saludos,
Felipe Sateler

**Comment by atifaziz** [comment]
> I had to hand edit the csproj to make the `FullGroupJoin.cs` file appear under (ie, as "generated from") `MoreEnumerable.cs`, and do this for both the MoreLinq and MoreLinq.Portable projects. What I was wondering is if there was a tool that automated this.

See [File Nesting](https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c).
