### ISSUE TITLE
Patch for /MoreLinq/EquiZip.cs

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#94]
There was a copy-paste error in the null-checking mechanism.

---
Originally reported on Google Code with ID 94

Reported by @taneltumanski on 2014-10-07 10:29:05

<hr>
 * *Attachment: [EquiZip.cs.patch](https://storage.googleapis.com/google-code-attachments/morelinq/issue-94/comment-0/EquiZip.cs.patch)*

**Comment by yln** [comment]
This is fixed now.
