### ISSUE TITLE
MaxByOrDefault

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#96]
Currently, `MaxBy` will throw an exception if executed on an empty enumerable.  I would like a way to provide it with a default value to use, or have it use `default(Source)`.

Example usage:

```c#
var emptyEnumerable = Enumerable.Empty<Person>();
var result = emptyEnumerable.MaxByOrDefault(person => person.Age);
Assert.Equal(0, result);

result = emptyEnumerable.MaxBy(person => person.Age, 10);
Assert.Equal(10, result);
```

---
Originally reported on Google Code with ID 96

Reported by `micah@zoltu.net` on 2014-12-08 20:12:09

**Comment by fsateler** [comment]
I don't think this makes sense. One could just as well do `src.DefaultIfEmpty(value).MaxBy(p => p.Age)` plus null checks if value is null.

**Comment by JamesFaix** [comment]
After coming back to this I agree with @fsateler.  The proposed methods/overloads might be a bit redundant.

**Comment by Lechus** [comment]
Wish it was implemented MaxByOrDefualt.

**Comment by Mikhail-Korchevskiy-Shift** [comment]
This is a very strange design. "OrDefault" semantically signals "_if can't get the max -> will resort the default_". Why is an empty enumerable some sort of a special case not covered by "can't get the max"?
Might as well rename it to "MaxByOrDefaultButOnlyWhenThereAreSomeElementsInSource"
