### ISSUE TITLE
Scan should not throw on empty sequences

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#97]
The `Scan<T>` implementation throws when an empty sequence is found. I believe the correct behavior should be to yield break in that case.

This would mean a different behavior from the `Scan<T, TState>` implementation, but it is already different. Without a seed, an `IEnumerable` of size N will yield an `IEnumerable` of the same size, while the version with seed adds an extra element.

So making a 0-length `IEnumerable` result in a 0-length `IEnumerable` seems like the right behavior to me.

---
Originally reported on Google Code with ID 97

Reported by @fsateler on 2014-12-30 13:15:32

**Comment by atifaziz** [comment]
This fix is now released as [version 1.3](https://www.nuget.org/packages/morelinq/1.3.0).

**Comment by fsateler** [comment]
This issue should be closed...
