### ISSUE TITLE
`FillForward` bug when filler is `null`

### ISSUE THREAD

**Issue by viceroypenguin** [morelinq/MoreLINQ#999]
There is a slight bug in `FillForward`; though it is very obscure and unlikely to be relevant to most users.

Consider the following code:
```csharp
var result = new int?[] { null, 200, null, }
	.FillForward(x => x == 200);

// expected
result == [ null, null, null ]

// actual
result == [ null, 200, null ]
```

The first value of `null` is _not_ blank (`null != 200`); the second value is blank (`200 == 200`). Per the expectations of `FillForward`, the existing value of `null` should be carried forward to replace the `200` value. However, `is (true, { } someSeed)` rejects a `null` value, even if `true`, so we get the value of `200`.

Related: viceroypenguin/SuperLinq#372

**Comment by atifaziz** [comment]
This is indeed super obscure and probably doesn't make practical sense, but it's a bug nonetheless so thanks for reporting it.
